### ISSUE TITLE
Expiration delay for lambda.

### ISSUE THREAD

**Issue by Smanar** [ndg63276/alexa-youtube#1]
Hi, so first rly nice project and in python, thx, bored with nodeJS.
But I have problem with the pytube fonction, it take too long time to decipher the signature. and you have a "sorry something went wrong".
For the moment it works if I put 5s in Expiration delay, but I m looking for a faster way to do this part.

Do you have already tried other library/language ?

And there is a problem, the signature is made on lambda, so with the amazon IP, but when you launch the stream it s with your IP, so the link don't work, the final link is coded for only 1 IP.

**Comment by ndg63276** [comment]
Sorry, not been watching.

If you get timeouts, increase the expiration delay, and allocate more memory. If it's too slow don't use it. :-)

Final links work for me.
