### ISSUE TITLE
 The skill should support the AMAZON.PreviousIntent for the audio playback. 

### ISSUE THREAD

**Issue by Zubiee** [ndg63276/alexa-youtube#10]
An unexpected response occurred when invoking the AMAZON.PreviousIntent. When the audio playback is played, the skill should support and gracefully handle requests to the Amazon built-in intents.

**Comment by ndg63276** [comment]
Works for me as of right now. If you have deployed it yourself, please re-upload the latest lambda_function.zip to Lambda, and try again.
