### ISSUE TITLE
Issue with cancelling the skill

### ISSUE THREAD

**Issue by Steve-fr78** [ndg63276/alexa-youtube#100]
Hello,

First of all I would like to thank you for your effort.

I am french so forgive me for my english, I promise that I will do my best.

I have several issues but I will try to add one by one in order to help others if they have the same ones.

I have an issue with cancelling the skill, so I can launch the skill correctly by saying " Alexa, lance Youtube" but when I want to cancel the skill, it only pause it. 

Below is my answers to some of your pre asked questions.

Thanks for your help.

Regards

**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
I have tried many words:
Alexa, quitter
Alexa, annuler
Alexa, stop 
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
I am using my own lambda instance arn:aws:lambda:eu-west.....
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
Yes 
5. What language are you using?
French

**Comment by ndg63276** [comment]
It says "Pausing", but it is stopped. How is this a problem?

**Comment by Steve-fr78** [comment]
Thanks for your quick answer. I thought that "Pausing" means that the video has been paused so most probably the skill is still running but now you confirm that Pausing will stop and cancel the skill so there is no problem. Regards
PS. I suggest maybe to change this in French into "Merci d'avoir utilisé Youtube et à bientôt" or something like that
