### ISSUE TITLE
Not able to play my playlist: error cannot play the video 

### ISSUE THREAD

**Issue by Steve-fr78** [ndg63276/alexa-youtube#101]
Hello, 

Following my first message. Here is my second issue, I have created a playlist and cannot access it. I get a reply in French "Je ne peux pas lire la vidéo" which means "I cannot read the video".

Kindly find below the answers to your questions.

Regards
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
"Jouer my playlist [NAME OF MY PLAYLIST]"
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
My own
arn:aws:lambda:eu-west
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
Yes
5. What language are you using?
French

**Comment by ndg63276** [comment]
1. Have you set environment variable 'MY_CHANNEL_ID'?
2. What happens if you go to https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&channelId={YOUR_CHANNEL_ID}&q={NAME_OF_YOUR_PLAYLIST}&key={YOUR_API_KEY} ?

**Comment by Steve-fr78** [comment]
1. Yes, I have set the environment variable My_CHANNEL_ID
2. I get this (I have replace the chanelID):
{
 "kind": "youtube#searchListResponse",
 "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/wCtX59ZyZP13b1ljbBQU1vx6Bb8\"",
 "regionCode": "FR",
 "pageInfo": {
  "totalResults": 0,
  "resultsPerPage": 5
 },
 "items": []
}

**Comment by ndg63276** [comment]
Nothing to do with my skill then, YouTube search is not finding any results. For some reason, YouTube is very bad at searching playlists, I think it takes months to add things to search results.

**Comment by Steve-fr78** [comment]
Ok thanks for your reply so I dont have other than waiting :)
