### ISSUE TITLE
Issue with writing and reading the played videos

### ISSUE THREAD

**Issue by Steve-fr78** [ndg63276/alexa-youtube#102]
Hello,

Here is my third issue. I have authorized the application to read and write into my list in order to keep the last videos I have played but unfortunately it does not work  :( 

I have checked everything (permissions on Alexa developper consol as well as the permission on Alexa application on iPhone and Android) and couldn't find the reason why it does not work. 

Thanks for your help.

Regards
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?

**Comment by ndg63276** [comment]
1. Say "Alexa, open YouTube", when she says "Welcome to Youtube", say "Cancel".
2. Go to https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logs: and click on your YouTube skill.
3. Click on the most recent log stream, it should be the top one.
4. You should see a fairly short log (about 10 lines). About 4th line down, do you see a message that says "List created", "List already exists", or "List permissions not granted"? Or just a 3 digit number (eg 200)?

**Comment by Steve-fr78** [comment]
Hello,
Thanks for your reply. Unfortunately I did not find the log stream in the link. Do you have a screenshot please?
Thank you.

**Comment by ndg63276** [comment]
This assumes your lambda function is set up in eu-west-1 (Dublin), if not, change to the region you set up your lambda function is in.

1) Go to https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#dashboard:
2) Click on "Logs" on the left hand side
3) It should look like this
![image](https://user-images.githubusercontent.com/24956497/64054255-129b5b80-cb7e-11e9-8ac4-df203c33febc.png)
4) Click on /aws/lambda/Youtube

**Comment by Steve-fr78** [comment]
Thanks for the details. It says" "List already exists"" however when I go to my list on the application, I see nothing in the list "Achat" neither in " to do"

**Comment by ndg63276** [comment]
Very odd. It should create another list, called YouTube, which should be below the Achat and To-Do lists, in a section called My Lists. (If you have no lists, it doesn't say My Lists).

Stupid question, but is the app signed into the same Amazon account that uses the YouTube skill? What about if you open the app, press the speech bubble button at the bottom and say "Launch YouTube"?

**Comment by Steve-fr78** [comment]
I have noticed that on the home page of the application I can see the list "Youtube", however when I go to "Lists" in the left menu, I cannot see it, i see only "Achats" and "Choses à faire" (To-Do lists). That is weird! Yes, I confirm that I use the same account

**Comment by ndg63276** [comment]
Might be worth uninstalling and reinstalling the Alexa app.

**Comment by Steve-fr78** [comment]
I just did it but nothing happened still the same problem. As.soon as i find the list on the home.page it is not that problem anymore but it deserves to be investigated later on ;)
