### ISSUE TITLE
Music will just cut out after about 5 minutes and stop playing

### ISSUE THREAD

**Issue by amitdvir1122** [ndg63276/alexa-youtube#103]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
alexa launch YouTube and 80s songs
2. What video are you trying to play? Please provide the youtube URL.
https://www.youtube.com/watch?v=2CqN3mlLOpQ
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
I am using mine 
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
I its updated.
5. What language are you using?
English

**Comment by ndg63276** [comment]
I tried this this morning, and couldn't recreate the problem. Does it happen every time, or just sometimes? Is it just with this video, or with others as well?

**Comment by amitdvir1122** [comment]
Every time

**Comment by ndg63276** [comment]
Hmmm... still can't reproduce here.

If you play that video, wait until it stops, then go to https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logs:, and click on the YouTube logs. Then click on the top log, which should be the most recent one. Let me know if there are any messages saying why it stopped. It will probably just say "Playback failed" or something like that, but if you can copy/paste any messages here, that would be good.
