### ISSUE TITLE
I thre any way to use more than 1 YouTube api to have more stability 

### ISSUE THREAD

**Issue by amitdvir1122** [ndg63276/alexa-youtube#104]
Is three any way to have 2 YouTube api keys Into one endpoint to improve stability?

**Comment by ndg63276** [comment]
What error message do you get?

**Comment by amitdvir1122** [comment]
This skill is being https 420 error

**Comment by ndg63276** [comment]
420 is not a real http error.

If you mean 429, that is nothing to do with the developer key. This is an error from pytube, the library I use to get the URL of the video from YouTube. You can see it in action at https://repl.it/@ndg63276/PyTubeTester, no developer key needed. If enough requests from pytube hit youtube in a short space of time, all from the same IP (ie Amazon's server), then it gets blocked with error 429.
