### ISSUE TITLE
problem getting my playlist

### ISSUE THREAD

**Issue by puroidrogeno** [ndg63276/alexa-youtube#105]
i'm trying to ask alexa to play one of my playlist but she keep returning: non ero in grado di riprodurre un video (i wasn't able to play a video). not sure what is the problem since i can ask her to play any songs i want and she work.

Please provide the following information:

1. What are you saying to Alexa?
(after opening youtube skill) alexa riproduci la mia playlist (name of the playlist i wanted)
2. What video are you trying to play? Please provide the youtube URL.
https://www.youtube.com/playlist?list=PLP8qVrOJxVinnBWzx008UlCs-U6K6fBV4
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
arn:aws:lambda:eu-west-1:513340552192:function:youtobi
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
last update
5. What language are you using?
italian

**Comment by ndg63276** [comment]
Testing myself, it works when I type in "Initial Dork", but if I speak it, Alexa thinks I said "Initial Dock", and doesn't find any results.

But it does work if I say "Alexa, ask YouTube to play my playlist Initial".

**Comment by puroidrogeno** [comment]
after your message i tryed, it seems i have to say: alexa, chiedi a youtube di riprodurre la mia playlist initial (Alexa, ask YouTube to play my playlist Initial), but it work only if i open the app first (alexa open youtube). also it doesn't work if i ask only: riproduci la mia playlist initial (play my playlist initial) after opening the skill. i have to go throught both opening the skill and the long formulation to make it work. i think is just some problem with the italian version
