### ISSUE TITLE
Play specific youtube urls stored in alexa list

### ISSUE THREAD

**Issue by badbob001** [ndg63276/alexa-youtube#107]
I want to play public playlists in my account and others, but it's not very reliable or impossible to get to them through the normal voice search. Since the skill has access to lists, let us add a list of search words + youtube urls that the skill will first check against before falling back to searching youtube.

I know the instructions has a section on adding one' s channel ID to help access one's playlist, but I think that only works for self deployments and is useless to aid in the access in the playlist of others (imagine a central alexa echo being used by a family / roommates, with each having their own youtube accounts).

So the format of the list items could be like:
[search terms] | [youtube url to video or playlist or channel]

List: **Youtube Custom**
- Jill's Liked Videos | https://www.youtube.com/playlist?list=djsdfjsldkfjsdfdfd
- Joe's Liked Vidoes | https://www.youtube.com/playlist?list=343434345ererere
- Techno Mix | https://www.youtube.com/playlist?list=4k4kjerkdddlf
- Hard to find song | https://www.youtube.com/watch?v=hHZvUeAdzeI
- Cool channel | https://www.youtube.com/channel/UCeiwvKaeH822p

Alexa, ask youtube to play Jill's Liked Videos
Alexa, ask youtube to shuffle Techno Mix

**Comment by ndg63276** [comment]
Seems like a reasonable idea, I'll have a go when I get some time. Do you think it will be easy enough to write the youtube URLS in the list? I guess copy and paste is the way forward.

For what it's worth, I can add your channel ID to your account, as each Patreon sponsor has their own ARN address, just let me know your channel ID. Obviously it is only one per account though.

**Comment by badbob001** [comment]
Yeah, the list items will need to be done with copy and paste. No need to over-complicate this. Thanks.

**Comment by badbob001** [comment]
I think this may be a dupe of:
"Any way to read youtube video url or playlist url from shopping list? #43"

**Comment by ndg63276** [comment]
I think they are different enough to be different features. This one is for videos you want often but are hard to search, #43 is for making a custom playlist (as I see it anyway).

Unfortunately I've been super busy and haven't been able to do much work on either of them. I did make branches to work on both, but haven't got very far!

**Comment by ndg63276** [comment]
Ok, I think I've got this working. If you want to test it, you can replace the contents of your lambda_function.py file with the one at https://raw.githubusercontent.com/ndg63276/alexa-youtube/%23107/lambda_function.py

Next time you launch the skill, it will create a list called "YouTube Favorites". You can then add items to this, in the format as suggested in the original comment. Eg:

![2019-11-11 21 32 13](https://user-images.githubusercontent.com/24956497/68622779-dd3eb280-04ca-11ea-8ec2-1b345c82a2f6.png)


I will test for a few weeks and see what bugs turn up, then release into the master version.

**Comment by raj2ras** [comment]
Thank you. Working well in my tests so far :-)

When a playlist is added, it also responds properly to "next track" and plays the next item in the playlist. Awesome.

**Comment by raj2ras** [comment]
Is there a limit on how large the playlists can be? When I try to add large (say >200) playlists, it always fails. Says "there was a problem with the requested skills reponse".

Some e.g. playlists:
https://www.youtube.com/playlist?list=PLeldRic8aZMfnCA-8_auM13CWSuYukI9f
https://www.youtube.com/playlist?list=PLuFtZHCUpOe0llxIRFwgMeTpXF_ds78Fa

**Comment by ndg63276** [comment]
Yeah, elsewhere in the skill I limit it to 50 videos in a playlist. I've added that now to this branch, you can update to the version at https://raw.githubusercontent.com/ndg63276/alexa-youtube/%23107/lambda_function.py

**Comment by raj2ras** [comment]
Sorry, I did not understand. What did you add, is it the ability to play large playlists or to trim them?

**Comment by ndg63276** [comment]
It just trims them to the first 50 videos. I still need to add the ability to shuffle them, at the moment it probably just shuffles the first 50 videos, I shall make it choose a random 50 videos at least.

50 videos is basically the limit of what this skill can handle, without a significant re-write.

**Comment by ndg63276** [comment]
Ok, the latest version has the ability to shuffle any playlist or channel on the favorites list.

**Comment by raj2ras** [comment]
Playlist trimming seems to work well now and so does shuffle. Still having issue with some playlists, will investigate more.

Minor bug: It plays 1st track from playlist then shuffles; this is fine. But the "History" for 1st track played, captures the wrong item. "Next track" onwards is fine.

**Comment by raj2ras** [comment]
Is the Shuffle on by default for favorited playlists or does it need to explicitly asked? 
For e.g. 
- Alexa ask YouTube to _shuffle_ "my fave 1" vs.
- Alexa ask YouTube to _play_ "my fave 1"

**Comment by ndg63276** [comment]
By default, it doesn't shuffle, it needs to be asked. But, if a particular video fails, it just silently skips to the next track in the playlist, so it may appear to be shuffling. For example, for this playlist, https://www.youtube.com/playlist?list=PLeldRic8aZMfnCA-8_auM13CWSuYukI9f, it always starts with track 4, Hoobastank.

I've now made it announce the name of the playlist or the channel, rather than the first video, so it may seem more sensible now.
