### ISSUE TITLE
Conflict with Firestick

### ISSUE THREAD

**Issue by maranathait** [ndg63276/alexa-youtube#108]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa? **"Avvia YouTube"**
2. What video are you trying to play? **-** 
3. Are you running your own lambda instance, or are you using mine? **My own instance**
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file?  **I do**
5. What language are you using? **Italian**

I own a Firestick linked to my Echo Dot, If I try to use this skill it doesn't work. It only works if I unplug my Firestick, I think there is a conflict or something like this. Can you fix it please?

**Comment by ndg63276** [comment]
Your best bet would be to change the invocation name of the skill, from YouTube to something else.

**Comment by dober2** [comment]
Funniely even changing the invocation to "TubeYou" would still start the Fire TV Stick app. After trying a lot i found "Tuber" to be the best option for me.
