### ISSUE TITLE
SkillManifestError

### ISSUE THREAD

**Issue by Ghaiss** [ndg63276/alexa-youtube#11]
Hey,

i can't save my own arn String because of the following problem:
"The trigger setting for the Lambda arn:aws:lambda:eu-west-1:XXXXXXXXXXXXXXX:function:alexaYT  is invalid. Error code: SkillManifestError"

Settings in short:
I imported lambda_function.zip file
Set Runtime to Python 2.7
Added these envi. vars with the keys: "ALEXA_APPLICATION_ID" and "DEVELOPER_KEY".
Execution role: "lambda_basic_execution" with "Basic Lambda@Edge perm..."

I keep getting this error and don't know why :S
What different settings do you have on AWS?

**Comment by ndg63276** [comment]
Hi @Ghaiss, first thing to check, in Lambda, have you set Alexa Skills Kit as a trigger for your lambda function. If it just says "Add triggers from the list on the left", click on "Alexa Skills Kit" from the list on the left. Underneath, set Skill ID Verification to disabled, click Add, then click Save.

Then try and build your skill again.

**Comment by ndg63276** [comment]
Yeah, that's a common problem, basically this skill takes a little longer than most so you need to allow more time and memory. Go to lambda, and scroll down to "Basic Settings". Increase the memory to 512mb, and the Timeout to 10 seconds.

**Comment by Ghaiss** [comment]
Wow perfekt! Thank you very much, it works like a charm!
It would be very helpful to others also if you can put these problems/questions in a short FAQ.

Best regards
Ghaiss
