### ISSUE TITLE
Usage limit reached

### ISSUE THREAD

**Issue by ryanbacon** [ndg63276/alexa-youtube#110]
Hello there!

I am having an issue where whenever I try to use this skill on an aws that I created it comes back with an "Sorry, this skill has hit it's usage limit for today. Please consider deploying the skill yourself for unlimited use" error. Here is a list of everything that I have tried:

-Regenerating my youtube api key
-Recreating both the aws and alexa skill (several times)
-Migrating from aws us west to aws us east
-Regenerating my youtube api key on a different account

Any help with this would be extremely appreciated!

**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa? - I am using the "ask youtube to play prince" that was used in the setup instructions
2. What video are you trying to play? Please provide the youtube URL. - I am having trouble getting it to play anything
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?) - No, I am using my own lambda instance
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems. - I just made it a few hours ago, so I am on the latest version
5. What language are you using? - English

![image](https://user-images.githubusercontent.com/7819810/65174655-94103c00-da0e-11e9-8d14-0b00ec7584ce.png)

**Comment by ndg63276** [comment]
Hi there. Can you try putting in as your ARN:
arn:aws:lambda:eu-west-1:175548706300:function:YouTubeTest

This will only ever play Gangnam Style, but it goes through all the motions, might help to diagnose the problem.

**Comment by ndg63276** [comment]
Also, if you go to this web address:

https://www.googleapis.com/youtube/v3/search?part=snippet&q=prince&type=video&key={YOUR_API_KEY}

Replacing {YOUR_API_KEY} with your youtube api key, do you get an error, or some search results?

**Comment by ryanbacon** [comment]
Thanks so much for your reply, it looks like that worked!

![image](https://user-images.githubusercontent.com/7819810/65178117-4f3bd380-da15-11e9-9f12-a761ea789247.png)

So it must be a problem with aws deployment then. I followed your exact instructions, so is it possible that there this is an aws error rather than an issue with your code? 

again thank you so much for helping me out =P

**Comment by ryanbacon** [comment]
I am actually an idiot and forgot to enable the youtube v3 api when I generated my key ;-;
The good news is that im no longer getting that error! 
The bad news is that im getting a new error!

![image](https://user-images.githubusercontent.com/7819810/65179281-c4a8a380-da17-11e9-9b33-440d497140ab.png)

From what I understand, it is because aws is making so many requests to youtube. Is there any good way to get around this?

Thanks!

**Comment by ndg63276** [comment]
So, that might be because you have done so much testing, that YouTube is throttling you. Hopefully it will start working again soon.

Alternatively, you can add another Environment Variable in your lambda instance. Below the variable "DEVELOPER_KEY", add a key "youtube_dl", and set the value to "true". This will tell the skill to use a different python library to get the youtube data. In my testing it works better, but I haven't tested it as much as the original library I used.

**Comment by ryanbacon** [comment]
changing the youtube_dl to true worked! 
Thank you so much for your help!

**Comment by ndg63276** [comment]
Great to hear!
