### ISSUE TITLE
Why is time saved in the history list in EST?

### ISSUE THREAD

**Issue by raj2ras** [ndg63276/alexa-youtube#112]
> **Keeping a list of what you have played**
> ...
> 4. Say "Alexa, launch YouTube", that will create the list, and from then on, videos will be added to it. The list can be viewed in the Alexa app, click Lists from the main menu.

Using US English, AWS Lambda on US-West (Oregon), Alexa set to PST timezone.  Why is time saved in the history list in EST? Can it be set to inherit the timezone from the device.

**Comment by ndg63276** [comment]
Heh, this is because I was lazy, I just set it to look up the language, and then set all US English ones to New York time.

I'll have a go at fixing it now.

**Comment by ndg63276** [comment]
Ok, I've updated with a time zone fix, if you re-upload lambda_function.zip, and test it, let me know if it works.

**Comment by raj2ras** [comment]
hmm..still saving in EST. I tried enabling and disabling the skill too. Will try again later if it is caching issue

**Comment by ndg63276** [comment]
Hopefully this was fixed by https://github.com/ndg63276/alexa-youtube/commit/16ead7ad203146b7c36e78661e1444a49d96cb31#diff-1c9600c715669119bf71f4577630e8a4

Re-open if it isn't!
