### ISSUE TITLE
Multi Room Audio/Video 

### ISSUE THREAD

**Issue by 1liminal1** [ndg63276/alexa-youtube#113]
Hey there!

Is there anyway to play one stream to multiple devices, like multi-room groups in Spotify 
Can I play to non show devices? EG play concerts on Echo Dots 

Basically I would love to be able to play, say a Radiohead concert, all though the house. The shows and spots, fire TV, plays video and the rest just audio. 

Is this an unattainable dream lol?

**Comment by ndg63276** [comment]
I think if you want that, you'll have to pay for Amazon music!

**Comment by 1liminal1** [comment]
Thanks for that, sorry it took so long to respond :)
