### ISSUE TITLE
Sorry something went wrong - Alexa message

### ISSUE THREAD

**Issue by jvoxel** [ndg63276/alexa-youtube#114]
It looks it is having a problem with the live videos.
Alexa find the video it says playing JapaNews24 live but then says "Sorry something went wrong"

1. What are you saying to Alexa?
Play videos by ANNnews
2. What video are you trying to play? Please provide the youtube URL.
https://www.youtube.com/watch?v=coYw-eVU0Ks
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
My own 
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
Yes latest from today few hours ago
5. What language are you using?
English UK

**Comment by ndg63276** [comment]
What hardware do you have? I have a feeling live videos don't work on older Echos.

**Comment by jvoxel** [comment]
I have the echo spot the one that is like an alarm clock with an screen.
Also I couldn't make Alexa to play any other video from the annNewsCH
channel I even tried making a public list with their normal (nonlive)
videos but even after declearing an environment variable with my channel ID
in lambda I could not make it to play 🤔 alexa says didn't find any videos
to play.

**Comment by ndg63276** [comment]
Well the good news is, I can reproduce the error. The bad news is, I can't fix it. My skill is providing a URL for Alexa to play (from the original live video), but it doesn't work for some reason. I've tried two different libraries for getting the URL from youtube, but the same thing happens with either.

It only appears to be that live video though, I can get other videos to play, for example, if you set MY_CHANNEL_ID to UCGCZAYq5Xxojl_tSXcVJhiQ, which is ANNnewsCH channel. You can then say "Alexa, ask YouTube to play my latest video" and it will play some the latest video on that channel. (If you change 'audio' to 'video' on line 222 of lambda_function.py, it will play as a video as well).

The reason you get "I wasn't able to play a video", is that YouTube's search API is awful, it can take months to list new playlists. So it doesn't find the playlist you just created. You can test this yourself by going to:
```
https://www.googleapis.com/youtube/v3/search?part=snippet&channelId={MY_CHANNEL_ID}&q={NAME_OF_PLAYLIST}&type=playlist&key={DEVELOPER_KEY}
```
(change {MY_CHANNEL_ID} to your channel id, {NAME_OF_PLAYLIST} to the name of your playlist, and {DEVELOPER_KEY} to your google developer key.

**Comment by jvoxel** [comment]
I'll try with the AnnNews channel ID or maybe adding the ann videos video
to an old playlist since maybe and old playlist would be visible to the YT
API

Thanks for your help.

**Comment by jvoxel** [comment]
Updating an old public playlist worked perfectly the only thing is that
there is no video but I am happy this will help a lot my japanese passive
inmersion. Thank you so much.
