### ISSUE TITLE
ask app to play function doesn't work in hindi

### ISSUE THREAD

**Issue by Raul824** [ndg63276/alexa-youtube#116]
Alexa has launched Hindi language in india, the app works fine in English but when changed language to hindi the app works when asking alexa to launch the app and also play videos.
But when giving command "Alex ask app to play videos by the beatles" there is no response just an audio ping that's it. Could you please help me to fix this as to play anything with this app i need to launch it again and again.

**Comment by ndg63276** [comment]
What happens if you say "Alexa, youtube खोलो और play the beatles"?

I don't speak Hindi so I can't test it on a device, but it works in the test environment. I got that suggestion from https://developer.amazon.com/docs/custom-skills/understanding-how-users-invoke-custom-skills.html, you might find more info there.

**Comment by filestoreinnet** [comment]
I think Change or add your skill language to Hindi india

**Comment by Raul824** [comment]
Hello NDG263276,

Thanks a lot for your response but still no help below is the snippet from
alexa developer console test screen.

[image: image.png]

**Comment by filestoreinnet** [comment]
I was facing same problem, I just changed the skill language to Hindi india and my problem solve

No need to change anything in, just change language to Hindi

Plus add Hindi and English india both for Alexa device

Say simply "Launch youtube"

**Comment by filestoreinnet** [comment]
This is Working for Me - Alexa, Youtube Open करो

**Comment by filestoreinnet** [comment]
And Some Time - Alexa Youtube खोलो
