### ISSUE TITLE
Use other servers for youtube searches

### ISSUE THREAD

**Issue by ndg63276** [ndg63276/alexa-youtube#119]
As suggested by @filestoreinnet in https://github.com/ndg63276/alexa-youtube/pull/118, we should be able to use another server for youtube searches.

Ideally also use other servers to get the download URL as well, instead of pytube or youtube_dl.

**Comment by ndg63276** [comment]
In order to use this for youtube search results, can you add some more parameters to your server? I would need:
- q (this is already implented)
- type
- maxResults
- relatedToVideoId
- channelId
- order
- pageToken

**Comment by filestoreinnet** [comment]
In addition we can use unofficial youtube apis or regex method for results (Without Api Key) so this will totally avoid any limit

**Comment by ndg63276** [comment]
Ok, you can now add 2 more environment variables to the lambda function:

1. youtube_search_url - set this to the mirror of https://www.googleapis.com/youtube/v3/search, ie http://randomstatus.in/others/youtube_search.php
2. youtube_playlist_search_url - set this if you implement the equivalent of https://www.googleapis.com/youtube/v3/playlistItems

You don't need both if you don't have both. Number 1 needs those parameters from above, number 2 needs playlistId, maxResults and pageToken. Without them you may get funny results.

**Comment by filestoreinnet** [comment]
Wow Thanks this is working i am very happy , and waiting for mirror downloading option

**Comment by ndg63276** [comment]
So the plan is for eg http://randomstatus.in/others/download.php?id=9bZkp7q19f0 to mirror the output of youtube_dl?

Can you provide it in a json format the same as youtube_dl's extract_info function? eg if you do:
```
import youtube_dl
with youtube_dl.YoutubeDL({}) as ydl:
    ydl.extract_info('http://www.youtube.com/watch?v=9bZkp7q19f0', download=False)
```
That way I can get the download URL, the title, whether it is a live broadcast, I can play video if supported etc etc

**Comment by filestoreinnet** [comment]
Your plan is correct, add a mirror for download

 I enabled json https://randomstatus.in/others/download.php?id=9bZkp7q19f0

Note : you can't use this link with any id, i set a default id, this link is only a example

**Comment by ndg63276** [comment]
Ok, that should do it. Update to the latest lambda_function.zip, and add (or change) the environment variable "youtube_dl" to "https://randomstatus.in/others/download.php".

Is your code to mirror youtube_dl on github anywhere? It would be good to enable more mirrors.

**Comment by filestoreinnet** [comment]
This function is working properly with this server https://randomstatus.in/others/download.php
But not working with any other server, i dont know why ?
 And this method is depends upon server speed,
 frankly say this slower than lambda server, 
We can't use it with regular basis,
But this may be good help when Skill is throttled by YouTube

You should set one more method when Lambda youtube-dl fails

By the way you done a great job, i happy i wants to give you $10, give me your PayPal, I can't give you using patron there is a problem

**Comment by ndg63276** [comment]
Not sure why it doesn't work with other servers, do you see any requests in your server logs? All I do is send a get request to the server, plus the 'id' parameter, so it becomes eg https://randomstatus.in/others/download.php?id=9bZkp7q19f0

You can test if you can use python:
```
import requests, json
params = {'id': '9bZkp7q19f0'}
r = requests.get('https://randomstatus.in/others/download.php', params=params)
print(r.json())
```
Alexa skills only have 9 seconds I think before they time out, so it will always be a struggle to get the info quickly enough, unless you have a fast server.

**Comment by ndg63276** [comment]
Just running on a local raspberry pi, importing youtube_dl and getting the info for a video takes ~8s, so unless you have a server with decent processing power and/or a fast connection to your lambda instance, it will time out.

You could try running pytube instead, it is quicker to import. Though I can't get it to work locally, so who knows!

**Comment by filestoreinnet** [comment]
I am using this function sice 3 days, and I am facing server slow problem so show 1 idea come into my mind 

Add one more environment called 

youtube_dl_error_mirror for url https://randomstatus.in/others/download.php this function only work when pytube or youtube-dl get error (ip blocked)

Then we have two option 1st if we have fast server then we can use download url in youtube_dl and if we have slow server then we can use lambda youtube_dl,pytube + mirror (on download error)

**Comment by ndg63276** [comment]
Did you manage to get your server working?

**Comment by filestoreinnet** [comment]
My server which are linked through cloudflare is working but which server that does not link through cloudflare is not working, I don't know why this happened, this may be hosting problem, but overall working with server, 

I hope you will add youtube_dl_error_mirror new function, don't remove any other function related to youtube_dl url,
Because first we in sure that my server is working properly e with youtube-dl URL then  we can add youtube_dl_error_mirror

**Comment by filestoreinnet** [comment]
I am facing (skill has been throatent) problem many time, add youtube_dl_error_morror when internal youtube-dl or pytube error,

You can do it. This function give a powerful funtion to this skill

**Comment by ndg63276** [comment]
Ok, have added a check for youtube_dl_error_mirror. Make sure to start it with 'http' or 'https', otherwise it won't be used.

I've tested it with an EC2 instance, using a t2.nano setup, and it works really nicely. Will cost a little money though!
