### ISSUE TITLE
Only 1 video of a playlist plays

### ISSUE THREAD

**Issue by bgiesing** [ndg63276/alexa-youtube#12]
Everytime I ask it to `shuffle playlist _______` it only plays 1 video and then stops.

**Comment by ndg63276** [comment]
Hi @bgiesing, I've updated the version of pytube, so hopefully it should work now, let me know if it doesn't.

(If you are using your own deployment, re-upload the lambda_function.zip file)

**Comment by bgiesing** [comment]
Yep it works now!
