### ISSUE TITLE
Setup instruction guide needed to host it in my own aws lambda.

### ISSUE THREAD

**Issue by rzrokon** [ndg63276/alexa-youtube#121]
I see, you have done lot's of things, i want to host it on my own labda function.

Can you help with a instruction guide for that.

**Comment by ndg63276** [comment]
Sorry, I don't have time to support people hosting their own lambda_functions. I have a patreon if you would like me to host one for you.

**Comment by rzrokon** [comment]
Then you should not upload the repo here.
Whatever best of luck with sale !!!!
