### ISSUE TITLE
[Question] I can't see my youtube skill on mobile app.

### ISSUE THREAD

**Issue by rikusen0335** [ndg63276/alexa-youtube#127]
I know this is a stupid question but please tell me how to activate it?
It seems worked correctly on Test (still Development) but I couldn't find my youtube skill.

I'm using Amazon Echo Dot 3rd Gen, and Japanese.
I also followed all the instructions.

**Comment by ndg63276** [comment]
On the mobile app, go to the main menu, then "Skills & Games". Then in the top right press "Your Skills". Then where it shows the number of "Enabled" and "Updated", scroll to the right, past "Blueprint", and press on "Dev". YouTube should be there.

**Comment by rikusen0335** [comment]
I can't see "Your skills" in "Skills & Games". Where does it show?

**Comment by ndg63276** [comment]
For me, it's in the top right, like this:

![Screenshot_20191104-150550](https://user-images.githubusercontent.com/24956497/68131564-2d3ed780-ff15-11e9-9d41-aff05ba9d926.png)

This is on Android by the way.

**Comment by rikusen0335** [comment]
Thanks. I'm using Android too, but I can see the option is "Activated Skill". Is there to do before using my own skills?

**Comment by ndg63276** [comment]
As long as you have enabled Testing for Development mode (which it seems you have), then it should work. What happens if you press the Alexa button at the bottom of the app, and say "open youtube"?

**Comment by rikusen0335** [comment]
Alexa App says "Video skill is not enabled. In Alexa App, please find Video Skill Device and enable it."
Alexa Echo Dot says too.

**Comment by ndg63276** [comment]
This is how I got it to work in Japanese - https://www.youtube.com/watch?v=dCyfFuwCwrQ&feature=youtu.be - is that what you are saying?

**Comment by rikusen0335** [comment]
I'm not. Please watch top right of below picture and then you can see that's "有効なスキル", and it means "Enabled Skills".
![Screenshot_20191105-131340](https://user-images.githubusercontent.com/19174234/68178155-2fb13800-ffce-11e9-9fc6-10c708182f98.png)

And also when I talk "Open youtube (in Japanese "youtube wo hiraku" like your video) to Alexa, she don't react about youtube. I will give you a short video after my school is end. Thank you for your supporting!

**Comment by ndg63276** [comment]
What do you see under "Enabled Skills"?

**Comment by rikusen0335** [comment]
Enabled skill (1 [Personally I enabled a skill]) and Blueprint (0).

**Comment by ndg63276** [comment]
Where it says Enabled 1 and Blueprint 0, can you scroll to the right, to Dev? Or is there a dropdown that says Enabled, that you can change to Dev?

**Comment by rikusen0335** [comment]
![Screenshot_20191105-221108](https://user-images.githubusercontent.com/19174234/68210912-e4bd1200-0019-11ea-9461-35eb1ea33d9a.png)
I can't scroll(swipe?) to the right, and there's no dropdowns change to Dev.

**Comment by ndg63276** [comment]
What's in the dropdown? Just Enabled and Blueprint?

**Comment by rikusen0335** [comment]
Yes, Enabled or Blueprint

**Comment by ndg63276** [comment]
Are you sure you are signed into the app with the same email address as your developer account? If you go to https://developer.amazon.com/settings/console/profile/detail.html, does it match your email and phone number? If you go to Settings in the app, and select "Your Profile", does it match as well?

**Comment by rikusen0335** [comment]
Yes, the phone number is the same, and I signed in again, a result isn't changed.

**Comment by ndg63276** [comment]
I don't really know I'm afraid. Does the app need updating?

Or you could contact Amazon, see if they know where your dev apps should be? There is a form at https://developer.amazon.com/support/contact-us

**Comment by rikusen0335** [comment]
Thanks. I will contact after some trys.

**Comment by rikusen0335** [comment]
Thank you so much for your supporting! That was an issue of Amazon account (If US and JP Account is linked, I couldn't use my own skills).
