### ISSUE TITLE
YouTube is talking to me!

### ISSUE THREAD

**Issue by savergiggio** [ndg63276/alexa-youtube#129]
When i ask to alexa on my Sonos one or Echo dor 3Gn, sometimes it replys saying "Youtube is talking to me", other times it works without problem. How  can i solve this issue? thank you

**Comment by ndg63276** [comment]
How very odd. What language does she say this in? If not English, can you tell me the exact phrase?

**Comment by savergiggio** [comment]
Hello friend, i use the skill in italian for command and replies, but it says this thing in english.

**Comment by ndg63276** [comment]
Even more strange. It's definitely not my code, so it must be Amazon. If you can figure out what causes it, or get a video of it, that might be useful, but I have no idea at the moment I'm afraid.

**Comment by savergiggio** [comment]
I use Alexa on a Sonos One and an Echo Dot. Maybe is this the problem?

**Comment by ndg63276** [comment]
That may be the cause. I don't have a Sonos One to test with, I'm a little surprised it works at all!

It may be that the Sonos is trying to see if you have a YouTube Music subscription, but I don't know.

One thing you could try is changing the invocation name of the skill to something completely different, and see if it fixes the problem.

**Comment by savergiggio** [comment]
Ok i will try. Thank you mate. I will let you know 😊
