### ISSUE TITLE
playlist not working

### ISSUE THREAD

**Issue by antwal** [ndg63276/alexa-youtube#130]
1. What are you saying to Alexa?
start my playlist test

Log error:

```
{
    "header": {
        "namespace": "System",
        "name": "Exception",
        "messageId": "f61348a7-ad4f-4a87-b47e-c80ca1d48ed7"
    },
    "payload": {
        "code": "INTERNAL_SERVICE_EXCEPTION",
        "description": "Request could not be executed due to an internal service error."
    }
}
```

**Comment by ndg63276** [comment]
Can you send me the link to the playlist you are trying to play?

**Comment by antwal** [comment]
Sorry for the delay, the playlist is currently public but even so it doesn't work

https://www.youtube.com/playlist?list=PLsaY0qET5m9DUQM-c-gp156M_-R3rId9b

**Comment by ndg63276** [comment]
And what exactly do you say to Alexa? And what does she respond?

**Comment by ndg63276** [comment]
If you set an environment variable on your lambda MY_CHANNEL_ID and set it to UCN3uKQ_kZJSTNAr6ePwNerA, you should be able to say "Alexa, ask YouTube to play my playlist Creedence Clearwater Revival".

**Comment by antwal** [comment]
ok now I try, but for a single playlist, if I have to load 20 playlists can I use a separator?

**Comment by ndg63276** [comment]
That is your channel id, so it will work for all your (public) playlists. It doesn't work for private playlists, as you are not logging in, just giving your channel id.

**Comment by antwal** [comment]
ok i did some testing using the channel id, from the alexa console; I also tried to change language but it is the same.

if I insert the name of the playlist with "playlist - creedence clearwater revival" it works, if instead I rename youtube playlist to simplify in "creedence clearwater revival" then test, it not work

playlist names must be simple otherwise they do not work; I also don't understand why just renamed a playlist was not found by the youtube api

**Comment by ndg63276** [comment]
You can test the API by pointing your browser to:

https://www.googleapis.com/youtube/v3/search?part=id,snippet&channelId=UCN3uKQ_kZJSTNAr6ePwNerA&type=playlist&q={name_of_playlist}&key={your_youtube_api_key}

**Comment by antwal** [comment]
yes i'm testing on google api explorer

**Comment by antwal** [comment]
Google Test: ![google-test](https://user-images.githubusercontent.com/410736/69466024-320fe200-0d83-11ea-8a20-6d81c3f60eeb.png)

Alexa Test (Italian): 
![alexa-test-2](https://user-images.githubusercontent.com/410736/69466171-8dda6b00-0d83-11ea-9293-5769009abc94.png)

**Comment by ndg63276** [comment]
That is because Alexa is not talking to my skill. Try renaming it to something other than Youtube.

**Comment by antwal** [comment]
Same problem #133, but from mobile works well, from echo dot just say the initial part of the playlist title and it works; if you have two playlists with the same initial name it will not work anymore

**Comment by antwal** [comment]
I did tests in python locally using API, it works great to find both private and public playlists; why didn't you use Playlists and use Search for this function?

[Doc Playlists](https://developers.google.com/youtube/v3/docs/playlists/list)

API Query: https://www.googleapis.com/youtube/v3/playlists?part=snippet%2CcontentDetails&channelId=[YOUR_CHANNEL_ID]&maxResults=50&key=[YOUR_API_KEY]

**Comment by ndg63276** [comment]
There is no search for that function. You can give it a channelId, as you have, but not a playlist title.

**Comment by antwal** [comment]
Yes you can get playlist title, this is example

![image](https://user-images.githubusercontent.com/410736/69674704-53cbda80-109d-11ea-91d5-861978544314.png)

**Comment by ndg63276** [comment]
But you haven't searched by title, so you just get a list of all the playlists. Then what? You have to loop through every playlist and see if the title matches precisely. Or use some sort of fuzzy text matching. It's all possible, but it's not straightforward.

**Comment by antwal** [comment]
I understand your point of view, I will make a copy of it to implement private playlists

**Comment by ndg63276** [comment]
Long implemented using fuzzy text matching.
