### ISSUE TITLE
YouTube Mix 

### ISSUE THREAD

**Issue by raj2ras** [ndg63276/alexa-youtube#131]
> YouTube Mix (https://support.google.com/youtube/answer/9011078?hl=en)
> A YouTube Mix is a nonstop playlist tailored to you. You can find YouTube Mixes:
> 
> In search results
> On your home page
> On Music cards
> In the Suggested section on certain watch pages

Can this skill work with "Youtube Mix" auto generated playlists?

**Comment by ndg63276** [comment]
No, they don't turn up in search results.

You can search related videos to the currently playing one, by "Alexa, ask YouTube to play more like this"

**Comment by raj2ras** [comment]
I guess the solution is to save the auto-generated mix as a playlist.
