### ISSUE TITLE
Question: What is Fuzzy matching?

### ISSUE THREAD

**Issue by raj2ras** [ndg63276/alexa-youtube#136]
Can someone explain in brief what is the "Fuzzy matching" that has been enabled on Dec 2, 2019?
Will it enable better searches/matching on YouTube, as I think? Does it apply to all languages?

**Comment by ndg63276** [comment]
It only applies to searching for your own playlists, using the MY_CHANNEL_ID environment variable. If a youtube search for a playlist on your channel gives no results, it will now get the full list of your playlists, and choose the one with the closest matching title. It will apply to all languages.

**Comment by raj2ras** [comment]
Never had success my "My Playlists". 
_Ask YouTube to play "xyz" from MY Playlist_  Does not work for my public playlists :-(
I have set the channel ID correctly. What is the best to invoke?

**Comment by ndg63276** [comment]
Can you give me a link to your playlist?

**Comment by raj2ras** [comment]
Lets say these ones for e.g.:

https://www.youtube.com/playlist?list=PLSXHQo_2iQnzNIlFKdz6Myxspv6ZbgaMG
https://www.youtube.com/playlist?list=PLSXHQo_2iQnyX_tcTVO_Srd5Ne5nn2e-y
https://www.youtube.com/playlist?list=PLSXHQo_2iQnzq0fuuQUR21BDOCK_h39Gu

**Comment by ndg63276** [comment]
Yeah, so none of those would work under the old system. Eg, if you go to https://www.googleapis.com/youtube/v3/search?type=playlist&part=id,snippet&channelId=UCfDZEMPAdO4lTrsBEZBpJFw?q=audiobooks&key=[YOUR_DEV_KEY} you get no results.

But if you go to https://www.googleapis.com/youtube/v3/playlists?part=id,snippet&channelId=UCfDZEMPAdO4lTrsBEZBpJFw&maxResults=50&key=[YOUR_DEV_KEY] you can see all your playlists. So the new system uses fuzzy matching to work out which of those playlists you want to play.

So now, if you set MY_CHANNEL_ID to UCfDZEMPAdO4lTrsBEZBpJFw, and say "Alexa, ask youtube to play my playlist audiobooks", she should play the Benjamin Franklin audiobook :-)

**Comment by raj2ras** [comment]
Excellent worth with adding the ability for playing off 1. Alexa lists and 2. YouTube Playlists. Opens up so many ways to save favorites :-).
