### ISSUE TITLE
How to Set up Lambda Function

### ISSUE THREAD

**Issue by HeIp** [ndg63276/alexa-youtube#137]
Trying setting it up myself, even specified the api key environment variable as well as setting youtube_dl to true. However, couldn't get it to work as there's no official guide. If anyone can help, thank you so much.

**Comment by HeIp** [comment]
As more people will probably ask themselves this, I figured it out going through a couple of opened issues. In the root folder there is "lambda_function.zip" use that and upload it to the lambda function.

Helpful points:
1) add the environment variable "MY_CHANNEL_ID" for playing personal playlists.
2)environment variable "youtube_dl" to "true"
3) environment variable ""DEVELOPER_KEY" to use your api key.
4)If you have the ability and knowhow to run youtube_dl on your own server, you can set the youtube_dl variable to the server address, and it will call that any time it fails. eg youtube_dl=http://myserver.com/cgi-bin/youtube_dl

**Comment by YendiGB** [comment]
@HeIp could you share with me the .zip so I can upload it to my own Lambda Server? I would really appreciate it, if it is possible.
