### ISSUE TITLE
Deployment to Heroku ?

### ISSUE THREAD

**Issue by HeIp** [ndg63276/alexa-youtube#138]
Way to deploy to Heroku Instead of Deployment to AWS server ?
Or anywhere else.

**Comment by BopItFreak** [comment]
Sorry, this won't work. Unfortunately AWS has you make skills as "modules" (at least in nodejs) on their server. You can't even see the backend code of what happens with your skill. So no, heroku is not possible, at least not that I know of.

**Comment by HeIp** [comment]
Any other platform ?

**Comment by ndg63276** [comment]
I know nothing about Heroku, but this skill is written in Python, not Nodejs. I think as long as you can make a http request with JSON, and receive JSON back, it should work.

**Comment by HeIp** [comment]
Is there a guide on how to deploy(as intended) ?

**Comment by ndg63276** [comment]
No, sorry.

**Comment by HeIp** [comment]
No problem, thank you.
