### ISSUE TITLE
Using my own endpoint, yields different results

### ISSUE THREAD

**Issue by tal9000v2** [ndg63276/alexa-youtube#14]
Hey. Got your skill working and it's great. Trying to setup my own endpoint and I got that working however, I am getting very different search results back from youtube. For example, when using your endpoint and I search for "prince", I get back "Playing Prince - Purple Rain (Official Video)".  When I use my endpoint (which is using your stuff and my own google api key) I am getting very different results like : "Playing Prince Reveals His Favorite Song, Why He Doesn't Have A Cell Phone & More" or "Playing HOW THE HUMBLE MAID WON THE HEART OF THE PRINCE {ZUBBY MICHAEL} - NIGERIAN MOVIES 2018/2019". I am on the West coast so my Lamba function is setup to  US East (N. Virgina). Not why the search results are different like that. Any ideas?

**Comment by Smanar** [comment]
Same for me, It's normal, I dont remember, but make a try with the youtube API instead of youtube itself.

**Comment by tal9000v2** [comment]
What I dont understand is why when using my endpoint I get different results then when using @ndg63276 endpoint.  The only difference I see is @ndg63276 endpoint is arn:aws:lambda:eu-west  and my end point is arn:aws:lambda:us-east. That is the only difference. Why would that change the results of what is returned from search results?

**Comment by tal9000v2** [comment]
@ndg63276  by the way, thanks so much for putting this together. Been wanting to get some YouTube albums to play through Alexa for a long time and now I can.

**Comment by ndg63276** [comment]
Hi @tal9000v2 , thanks for your comments, and for @'ing me in, I hadn't seen all these issues because I hadn't realised I wasn't watching!

I don't think the lambda endpoint will affect your YouTube search results, but we can test that quite easily. If you go to https://repl.it/@ndg63276/YouTubeSearchTester, and press Run at the top, it will install some python libraries, and then ask you for your YouTube API key. Then it will ask you what to search for, if I put in "prince", I get:

Prince - Purple Rain (Official Video)
Prince - When Doves Cry (Official Music Video)
Prince - Kiss (Official Music Video)
Prince - Let's Go Crazy (Official Music Video)
Prince - Raspberry Beret (Official Music Video)
Prince - Little Red Corvette (Official Music Video)
Prince - I Wanna Be Your Lover (Official Music Video)
Prince - Crimson and Clover
Prince - U Got The Look (Official Music Video)
Prince - Nothing Compares 2 U (Official Music Video)
 
If you still get Nigerian stuff, I guess it must be something with your API key.

**Comment by tal9000v2** [comment]
Neat test. Guess it's not the API key. I get the same results as you when using my API key

What would you like to search for?  prince
These are the top 10 YouTube search results:
Prince - Purple Rain (Official Video)
Prince - When Doves Cry (Official Music Video)
Prince - Kiss (Official Music Video)
Prince - Let's Go Crazy (Official Music Video)
Prince - Raspberry Beret (Official Music Video)
Prince - Little Red Corvette (Official Music Video)
Prince - I Wanna Be Your Lover (Official Music Video)
Prince - Crimson and Clover
Prince - U Got The Look (Official Music Video)
Prince - Nothing Compares 2 U (Official Music Video)

Want to try testing against my endpoint versus yours?

**Comment by tal9000v2** [comment]
here's my endpoint if you want to see.: arn:aws:lambda:us-east-1:450393429787:function:YouTube

I disabled skillID verification

**Comment by tal9000v2** [comment]
when I search for "prince" on mine, I get "Playing Prince Reveals His Favorite Song, Why He Doesn't Have A Cell Phone & More". But with yours, I get "Purple Rain".

**Comment by ndg63276** [comment]
Yeah if I use your endpoint, I get "Prince Reveals His Favorite Song".

It seems like it's slower than mine as well, so maybe lots of videos are timing out? I set my tester to load 50 results, and "Prince Reveals His Favorite Song" is number 13.

Can you see anything in your Cloudwatch logs?

**Comment by ndg63276** [comment]
Oh and I just updated the pytube version in the lambda_function.zip, so maybe try uploading that one to Lambda. I hadn't really thought anyone was deploying it themselves so it got out of date.

**Comment by tal9000v2** [comment]
Good call. Let me check the logs. Also, what do you have your memory allocation setting and timeout set too on your lambda function. I'll updating as well. :)

**Comment by ndg63276** [comment]
512Mb, and 10 seconds.

**Comment by tal9000v2** [comment]
Ahhh. I have mine set to 128. That could be it. I'll try updating each item incrementally to see which does it.

**Comment by tal9000v2** [comment]
Ok. Looks like it wasn't memory or timeout settings.  I was at 128 and 3minutes. When I changed to 512 and 10 seconds it bombed out altogether. Which means it was related to timeout. So I just updated to the latest lamba_function.zip and wallah. Getting the same results as yours now. So I guess it was pytube. Thanks man! You rock.

**Comment by tal9000v2** [comment]
I have mine set to 128 and 30 seconds and it's still working good.

**Comment by ndg63276** [comment]
Good to hear. I think Alexa may time out after about 10 seconds, so anything more than that makes no difference.
