### ISSUE TITLE
how do I add my channel id?

### ISSUE THREAD

**Issue by ObTeks** [ndg63276/alexa-youtube#141]
I am not much of a programmer so i need some help with adding my channel id

**Comment by ndg63276** [comment]
First, you need your channel id from youtube. Go to youtube.com, click on your icon in the top right, and click "Your channel". It will take you to a page with an address like https://www.youtube.com/channel/UCDVYQ4Zhbm3S2dlz7P1GBDg?view_as=subscriber. Your channel id is the bit between channel/ and ?view, in this case UCDVYQ4Zhbm3S2dlz7P1GBDg.

If you sponsor me on Patreon, just send me the channel id and I will add it your lambda.

If not, go to your lambda skill, there is a section called "Environment variables". You should already have one called DEVELOPER_KEY. Underneath, add another one, with the key MY_CHANNEL_ID, and the value of your channel id.

Hope that helps.
