### ISSUE TITLE
Lambda File

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [ndg63276/alexa-youtube#142]
Were is the Lambda file so we can host it our self instead.

**Comment by ndg63276** [comment]
Unfortunately more people were stealing my code and trying to profit off of it, than were trying to collaborate to help improve it. So I've removed the code. Sorry about that.

**Comment by TWIISTED-SHOPS** [comment]
Oh ok then so you no longer allow us to host the lambda file ourself then

**Comment by ndg63276** [comment]
No, sorry.
