### ISSUE TITLE
Since you removed the code files it's normal to get a blank screen in EC2?

### ISSUE THREAD

**Issue by roiniti** [ndg63276/alexa-youtube#145]
I've get the code before the removal and i stopped using the private EC2 a few months, now when I try to setup the cgi-bin/ydl.py i get a blank screen, is it normal since the code removal?

**Comment by ndg63276** [comment]
You probably need to update youtube_dl. Log in to your EC2, then:

1. sudo /bin/bash
2. cd /var/www/lighttpd/cgi-bin
3. pip install youtube_dl --upgrade -t .

**Comment by roiniti** [comment]
it worked! thank you!
