### ISSUE TITLE
Is it possible to use Firebase Serverless?

### ISSUE THREAD

**Issue by CocoaCrispies** [ndg63276/alexa-youtube#147]
As title says. I need to use Firebase serverless because I can't verify with AWS. Is this possible?

**Comment by ndg63276** [comment]
I don't follow. This repo now just has some json files.

**Comment by CocoaCrispies** [comment]
> I don't follow. This repo now just has some json files.

Yes, but if i code a Firebase serverless function that replaces lambda, will it work?

**Comment by ndg63276** [comment]
I mean, if you code a function that works, sure.
