### ISSUE TITLE
Video is not playing for this

### ISSUE THREAD

**Issue by kaygeeyem16** [ndg63276/alexa-youtube#149]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa? Alexa launch my youtube
2. What video are you trying to play? Please provide the youtube URL. default gangnam style
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?) same url from the demo
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?

**Comment by ndg63276** [comment]
YouTubeTest ARN set to always play video.
