### ISSUE TITLE
Help with creating Lambda Instance

### ISSUE THREAD

**Issue by Proxyn17** [ndg63276/alexa-youtube#150]
If anyone knows how to deploy this skill on my own Lambda instance and is willing to help out please let me know! I have the lambda_function.zip file however i get a few errors running the code, like importing email.utils or stuff like that, i am unsure what to put in the emails.utils.py file i think i have to create. Python newb here but i feel like i can taste this skill im that close xD Thanks!

**Comment by ndg63276** [comment]
Or you could just sponsor me :)

**Comment by Proxyn17** [comment]
would i be able to edit how alexa responds? like when it's opened i just want her to say "Welcome to youtube" or something like that

**Comment by Proxyn17** [comment]
> Or you could just sponsor me :)

tbh when i get my fourth canadian dollar i will but until then:
https://c.tenor.com/vE7cfU6WUmcAAAAC/spongebob-squarepants-3dollars.gif

Even if i do succeeding at running it own my own instance i'll still sponsor you for as long as i use it, you tried to let people use it for free until you started getting charged, so 100% respect (maybe less since i asked people to help me run my own lol)
