### ISSUE TITLE
alexa error on playing skill

### ISSUE THREAD

**Issue by 79812b** [ndg63276/alexa-youtube#152]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?

1.WHEN I SAY PLAY MR.BEAST VIDEO OR PLAY DESPACITO FROM (NAME OF SKILL )  IT SAY PLAYING MUSIC IS NOT SUPPORTED ON THE SKILL
I AM RUNING MY SERVER

**Comment by justinh998** [comment]
@79812b  can you help me with me isseu here:https://github.com/ndg63276/alexa-youtube/issues/154?

**Comment by Raul824** [comment]
When trying to use your Test Lambda it isn't even playing gangnam style and giving instead below error.

There was a problem with the requested skill's response.


Me:alexa launch custom songs

Alexa:Welcome to Youtube. Say, for example, play videos by The Beatles.

Me:play gangnam style

Alexa:There was a problem with the requested skill's response

**Comment by ndg63276** [comment]
@Raul824 Here's the request I see in the logs:
```
{
    "request": {
        "type": "IntentRequest",
        "requestId": "amzn1.echo-api.request.589e3e3c-b546-4644-995a-684a9f34b6d7",
        "locale": "en-IN",
        "timestamp": "2024-07-20T05:57:28Z",
        "intent": {
            "name": "StartAudioIntent",
            "confirmationStatus": "NONE",
            "slots": {
                "songName": {
                    "name": "songName",
                    "value": "Gangnam style",
                    "confirmationStatus": "NONE",
                    "source": "USER",
                    "slotValue": {
                        "type": "Simple",
                        "value": "Gangnam style"
                    }
                }
            }
        }
    }
}
```
The skill complains because StartAudioIntent is not supported, and I've never seen it documented anywhere. Can you double check your interaction model, and copy-paste in the contents of https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_en.json, deleting anything that is already there?

**Comment by Raul824** [comment]
I created another skill from scratch and I get below error now.

There was a problem with the requested skill's response. Below is the output if this helps.

```{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "Playing PSY - GANGNAM STYLE() MV"
			},
			"card": {
				"type": "Simple",
				"title": "Youtube",
				"content": "Playing PSY - GANGNAM STYLE(?????) M/V"
			},
			"directives": [
				{
					"type": "AudioPlayer.Play",
					"playBehavior": "REPLACE_ALL",
					"audioItem": {
						"stream": {
							"token": "s=0&sr=0&a=1&i=Search&query=gangnam_style&l=0&v0=9bZkp7q19f0&p=0&v1=cGc_NfiTxng&v2=o1YYh9AvxA8&v3=CVxMTl6cUSE&v4=DzivgKuhNl4&v5=iSF26HsmeRI&v6=wcLNteez3c4&v7=y0e6DlfPrYE&v8=IZtKlDQsehI&v9=52fgfXjW2rA&v10=84vyCo8vFHc&v11=wMMp-09BHa0&v12=jjPlqrGv-lA&v13=mj8nMfxa1mQ&v14=AV1biKT426I&v15=NeLnqJGhq_Q&v16=CZvMLsdUiGI&v17=ikCa3Lr9pKU&v18=Jo7VgscvGvE&v19=3MaQ2qgzmzM&v20=0ZVhTrJ65ds&v21=8ZMCFzq37iQ&v22=1ntxO2ZLth8&v23=pjAZSNeyUhI&v24=39V916pgfOQ&v25=lXiZqSTREgw&v26=HUqf84AZ0mM&v27=QZmkU5Pg1sw&v28=KxW4T_S5_ns&v29=3bGZCDK6HT0&v30=_0p3UoVS0HM&v31=ly4fjh01Auo&v32=zl-mEWqnIYs&v33=_cG7ZVBXQII&v34=H2SreagnDXM&v35=mjejk5vlPfQ&v36=HHTiYs8GZco&v37=bSuWLVMvbJM&v38=2ZaFuoIsFkc&v39=9HPiBJBCOq8&v40=qSdKDGLM9E4&v41=90kLSwth0s8&v42=BrUoA7qQEuk&v43=s7QE62FDn08&v44=AJahpUP2Ofc&v45=nF9WdXSL0V8&v46=DEpQaydVSyw&v47=vovdZ8tSCUE&v48=tKwdDbdPego&v49=JUDlvtj03q0",
							"url": "https://rr3---sn-q0cedn7s.googlevideo.com/videoplayback?expire=1721637402&ei=usWdZrOIL8G46dsP5qz1OQ&ip=108.128.39.221&id=o-APOBs26ZLdLNotJ24gwly7sZLLKOGbIbajx15HZqu1lH&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=hJ&mm=31%2C29&mn=sn-q0cedn7s%2Csn-q0c7rn7d&ms=au%2Crdu&mv=u&mvi=3&pl=22&bui=AXc671LWyMVAzv10U6kJ_YxjzQwi4QeSqpvUrWn7l3XSkNvlzPc6YOmKUAWxZCz1b3SlZ7qgzQ9xeqz3&spc=NO7bASMU7ws1v4X5nYoZzm0hQiaW55yihfJ6EJlyjP7PtTHlOe9C4hBPlj7s&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=V_q8ARGlwCxklRXRFiib2VAQ&rqh=1&gir=yes&clen=4083640&dur=252.261&lmt=1712653867474717&mt=1721615109&fvip=3&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=TgkfQSBSEUMHNg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHlkHjAwRgIhAIejirPQeJQ8qhXhOjM5dhAV9eC-3BsGhIGmc0iPs9UsAiEAgXM1wsU-lV1iD6hVmXxY10LZT-d2ICaLjp1OZXdl2z4%3D&sig=AJfQdSswRAIgdD4MgRUTkF3ZOlCaVagJfI52_ziWhVfzKw-6Rvyi0wMCIHjcNZg9zB9tILEiri06EqQrqxQdD4q8UyqteNlFic3P",
							"offsetInMilliseconds": 0
						}
					}
				}
			],
			"shouldEndSession": true,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {}
	}
}```

**Comment by ndg63276** [comment]
That all looks totally normal, and there are no errors in my logs. It won't play any audio if you are running it via the dev console, but should have played if you were using an Alexa device.

**Comment by Raul824** [comment]
Thanks when I ran it via alexa I got the error that the app is not set as AudioPlayer so I enabled it in interface and now it worked.
Thanks

**Comment by ndg63276** [comment]
Ah fantastic!
