### ISSUE TITLE
Suddenly not recognize most playlists

### ISSUE THREAD

**Issue by jimrin** [ndg63276/alexa-youtube#153]
I had playlists listed in my Alexa YouTube Favorites list which has been working flawlessly since I signed up but over the last couple of days, it now tells me "The playlist (such and such) hasn't work. Shall I try the next one?"

I created an entry called "Test music" pointing to one of the other playlists, so when it announces the error message, it is properly identifying the right playlist on YouTube.

Also, I used to be able to say "play videos by the Beatles", but now, it seems not to respond... Or last least out of several tries, I only got it to respond once. Not sure how much this might be due to Alexa or the routine.

PS. Now for a request like "play videos by the Beatles", the Alexa response is "there was a problem with the requested skills response."

**Comment by ndg63276** [comment]
I think this was caused by https://github.com/ytdl-org/youtube-dl/issues/32314, so I've updated youtube-dl, and the fix is rolling out now.

**Comment by jimrin** [comment]
Thank you for the quick response!! It's working great now!
