### ISSUE TITLE
alexa - cant play any song

### ISSUE THREAD

**Issue by justinh998** [ndg63276/alexa-youtube#154]
**Questions you need to answer**
Please provide the following information:

1.  I said to alexa start youtube , then I said: play videos of the Beatels.Alexa then show me (Skill response was marked as failure request identifier:.... the target lamba application returned a failure response.
2. Please provide the youtube URL.   I can't provide a url because this problem actually occurs with all videos.
3.  Running own lambda instance (I have attached my zip that I uploaded to lambda)(my endpoint: arn:aws:lambda:eu-west-1:569398079354:function:allerletzterversuch)
5. Pyton , i take my zip from here :https://github.com/crd/jukebox(an earlier version of this project here , when it was still open))
6. I hope someone can help me.
7. i didnt find a way to debug lambda

the only thing i can get is the json input from the alexa developer test site.

{ "version": "1.0", "session": { "new": false, "sessionId": "amzn1.echo-api.session.3b871408-7a29-4001-b79a-d91864f3b119", "application": { "applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94" }, "attributes": {}, "user": { "userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q" } }, "context": { "Viewports": [ { "type": "APL", "id": "main", "shape": "RECTANGLE", "dpi": 213, "presentationType": "STANDARD", "canRotate": false, "configuration": { "current": { "mode": "HUB", "video": { "codecs": [ "H_264_42", "H_264_41" ] }, "size": { "type": "DISCRETE", "pixelWidth": 1280, "pixelHeight": 800 } } } } ], "AudioPlayer": { "playerActivity": "IDLE" }, "Viewport": { "experiences": [ { "arcMinuteWidth": 346, "arcMinuteHeight": 216, "canRotate": false, "canResize": false } ], "mode": "HUB", "shape": "RECTANGLE", "pixelWidth": 1280, "pixelHeight": 800, "dpi": 213, "currentPixelWidth": 1280, "currentPixelHeight": 800, "touch": [ "SINGLE" ], "video": { "codecs": [ "H_264_42", "H_264_41" ] } }, "Extensions": { "available": { "aplext:backstack:10": {} } }, "Advertising": { "advertisingId": "00000000-0000-0000-0000-000000000000", "limitAdTracking": true }, "System": { "application": { "applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94" }, "user": { "userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q" }, "device": { "deviceId": "amzn1.ask.device.AMA7XWK3IECNKWAIOIJBZXSBRX2UCZ7OTQTOS4VL2L5FHZDZKCEDIKPD2KUKOVSULCLVVGLZPNUZZMH4NNSEYE7JWZBX5BSBSAZC2TADOT3KKSZKHXOGWPN4G5GRCE3QJZYSN5OSASD6J6RECDCX6LKRVHJPAGAEKYF2GWCNJ74EDJ2SXMCABC7FMUQRZFROSX2M4YWK6VE57VQ", "supportedInterfaces": { "AudioPlayer": {} } }, "apiEndpoint": "https://api.eu.amazonalexa.com", "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5ldS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmViNmVjZjQxLThiZWUtNDY3MC04OWU3LTdiMzQ3MDJkY2I5NCIsImV4cCI6MTY4NzY5OTQ0NSwiaWF0IjoxNjg3Njk5Mzg1LCJuYmYiOjE2ODc2OTkzODUsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFDSy96T3U0MnlEbXR5SWZqcTZ3WnNES2dFQUFBQUFBQUNpbDBKZVYxVHlVTlhuWXNHb21JYWxiaHB2akFWTXkybElaM1ArMGxxNVM1bDNkR1FCNXM5dW5jUHBpbUhwOTAwQlJZZ1JyQ3JoRFlnck5reVZ3bk4xYWlBYzZVck9BNDFVRmVVa0RxT1NmUlBKZjgyNU5CR3hTNDVLTWpnOWNXclF6RkJaU1ZKMk1DSXhLZFhHRDBXbmtFMFEwckVGNHVSUFlCMUdyL2p3R1MvZGRHYXNwVDRkNUxDRWRlUmlCWkQrc0F1VnZQaStpWTdtZUxyWTJNNHR1TGg3MHRITFVXWUorazdwbCtMNXJzTUl0MENNQytwQVBsOHQwLzBQTzBiQmxzTzJlN1FURzdtU0JCa0I2ZmVVVWg0S2c4aFpvcFJ2VWsrUGV1eWJwQUxERHFQazQ5ekpESHBIbnVFSGJxcE5HWGE5UTdyL2JiRXdTNmNvN09YN3hIRmkwdkc3L1d2eHN3bnE3cTIycW1qM1JtbGdaVEVGZ1l5NlJLQkUwb00rSFp2ekEzTmJPVUc4IiwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFNQTdYV0szSUVDTktXQUlPSUpCWlhTQlJYMlVDWjdPVFFUT1M0VkwyTDVGSFpEWktDRURJS1BEMktVS09WU1VMQ0xWVkdMWlBOVVpaTUg0Tk5TRVlFN0pXWkJYNUJTQlNBWkMyVEFET1QzS0tTWktIWE9HV1BONEc1R1JDRTNRSlpZU041T1NBU0Q2SjZSRUNEQ1g2TEtSVkhKUEFHQUVLWUYyR1dDTko3NEVESjJTWE1DQUJDN0ZNVVFSWkZST1NYMk00WVdLNlZFNTdWUSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFNQVpDSUdESUtaVDdKSlRDVDVSVFhVUEdTUFpVRVFNQlBOS0ZBTDVYSEJNMlVVM0NUUkNLU1kzV0xKSVYzRFlEUlAyRVVTUkpDVExIWElIVzdOWUZPTUdVMzNTRUVQTTVCWFNQU0xETkpRWTNPMlY1M1kzNklGNkhHWk5FRVdPVk5aUU1WRFhHWlc0RE1DQUxBUkdKR1BWUks0VjZSSFQ0NVVMRjJIU1VRVllaTkEzRFYyUEdEWE1DTEZWVzRISEpGVDZXWERHSUFSVlpRQ1NCTDVHU1ZaS05ZWjdYSFJGQ05ONVZSRVZCUDZRIn19.Q9Ys68biYiwOzBoJZEW6AjSYqXPNEs3Lc-bcRR0iNivImrVptGImNOsPqtSlw5J10i9S7iVmmaobsoGXapyBI6CGYR3j67YNhnTARXNQ81_E0gEUG2QYXblq_8eJmrb7qIKzZVkcSLcGfPrvZV2pIWSxDGLDyZ9LUWaCOiWN0yD9XHaflGO8wpzjDIjjmmHrAQdf2hWZ72Qqwc5HRcURCTW9QAW26EDAAYsOLFbUgxuLXYm6cfk7CwLNa32OU4RbubYhadoLZUAD-St7pRo6hipq92ANxqHLULvlg_zpnV2jK4Ap9dtk6rWytwRV-PXz13MybibND-t9eNsmbCsj9w" } }, "request": { "type": "IntentRequest", "requestId": "amzn1.echo-api.request.653d8cf5-e60c-4210-b279-52e78985d862", "locale": "de-DE", "timestamp": "2023-06-25T13:23:05Z", "intent": { "name": "SearchIntent", "confirmationStatus": "NONE", "slots": { "query": { "name": "query", "value": "abba", "confirmationStatus": "NONE", "source": "USER", "slotValue": { "type": "Simple", "value": "abba" } } } } } }

{ "version": "1.0", "session": { "new": false, "sessionId": "amzn1.echo-api.session.3b871408-7a29-4001-b79a-d91864f3b119", "application": { "applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94" }, "attributes": {}, "user": { "userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q" } }, "context": { "Viewports": [ { "type": "APL", "id": "main", "shape": "RECTANGLE", "dpi": 213, "presentationType": "STANDARD", "canRotate": false, "configuration": { "current": { "mode": "HUB", "video": { "codecs": [ "H_264_42", "H_264_41" ] }, "size": { "type": "DISCRETE", "pixelWidth": 1280, "pixelHeight": 800 } } } } ], "AudioPlayer": { "playerActivity": "IDLE" }, "Viewport": { "experiences": [ { "arcMinuteWidth": 346, "arcMinuteHeight": 216, "canRotate": false, "canResize": false } ], "mode": "HUB", "shape": "RECTANGLE", "pixelWidth": 1280, "pixelHeight": 800, "dpi": 213, "currentPixelWidth": 1280, "currentPixelHeight": 800, "touch": [ "SINGLE" ], "video": { "codecs": [ "H_264_42", "H_264_41" ] } }, "Extensions": { "available": { "aplext:backstack:10": {} } }, "System": { "application": { "applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94" }, "user": { "userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q" }, "device": { "deviceId": "amzn1.ask.device.AMA7XWK3IECNKWAIOIJBZXSBRX2UCZ7OTQTOS4VL2L5FHZDZKCEDIKPD2KUKOVSULCLVVGLZPNUZZMH4NNSEYE7JWZBX5BSBSAZC2TADOT3KKSZKHXOGWPN4G5GRCE3QJZYSN5OSASD6J6RECDCX6LKRVHJPAGAEKYF2GWCNJ74EDJ2SXMCABC7FMUQRZFROSX2M4YWK6VE57VQ", "supportedInterfaces": { "AudioPlayer": {} } }, "apiEndpoint": "https://api.eu.amazonalexa.com", "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5ldS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmViNmVjZjQxLThiZWUtNDY3MC04OWU3LTdiMzQ3MDJkY2I5NCIsImV4cCI6MTY4NzY5OTQ0NSwiaWF0IjoxNjg3Njk5Mzg1LCJuYmYiOjE2ODc2OTkzODUsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFDSy96T3U0MnlEbXR5SWZqcTZ3WnNES2dFQUFBQUFBQUNpbDBKZVYxVHlVTlhuWXNHb21JYWxiaHB2akFWTXkybElaM1ArMGxxNVM1bDNkR1FCNXM5dW5jUHBpbUhwOTAwQlJZZ1JyQ3JoRFlnck5reVZ3bk4xYWlBYzZVck9BNDFVRmVVa0RxT1NmUlBKZjgyNU5CR3hTNDVLTWpnOWNXclF6RkJaU1ZKMk1DSXhLZFhHRDBXbmtFMFEwckVGNHVSUFlCMUdyL2p3R1MvZGRHYXNwVDRkNUxDRWRlUmlCWkQrc0F1VnZQaStpWTdtZUxyWTJNNHR1TGg3MHRITFVXWUorazdwbCtMNXJzTUl0MENNQytwQVBsOHQwLzBQTzBiQmxzTzJlN1FURzdtU0JCa0I2ZmVVVWg0S2c4aFpvcFJ2VWsrUGV1eWJwQUxERHFQazQ5ekpESHBIbnVFSGJxcE5HWGE5UTdyL2JiRXdTNmNvN09YN3hIRmkwdkc3L1d2eHN3bnE3cTIycW1qM1JtbGdaVEVGZ1l5NlJLQkUwb00rSFp2ekEzTmJPVUc4IiwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFNQTdYV0szSUVDTktXQUlPSUpCWlhTQlJYMlVDWjdPVFFUT1M0VkwyTDVGSFpEWktDRURJS1BEMktVS09WU1VMQ0xWVkdMWlBOVVpaTUg0Tk5TRVlFN0pXWkJYNUJTQlNBWkMyVEFET1QzS0tTWktIWE9HV1BONEc1R1JDRTNRSlpZU041T1NBU0Q2SjZSRUNEQ1g2TEtSVkhKUEFHQUVLWUYyR1dDTko3NEVESjJTWE1DQUJDN0ZNVVFSWkZST1NYMk00WVdLNlZFNTdWUSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFNQVpDSUdESUtaVDdKSlRDVDVSVFhVUEdTUFpVRVFNQlBOS0ZBTDVYSEJNMlVVM0NUUkNLU1kzV0xKSVYzRFlEUlAyRVVTUkpDVExIWElIVzdOWUZPTUdVMzNTRUVQTTVCWFNQU0xETkpRWTNPMlY1M1kzNklGNkhHWk5FRVdPVk5aUU1WRFhHWlc0RE1DQUxBUkdKR1BWUks0VjZSSFQ0NVVMRjJIU1VRVllaTkEzRFYyUEdEWE1DTEZWVzRISEpGVDZXWERHSUFSVlpRQ1NCTDVHU1ZaS05ZWjdYSFJGQ05ONVZSRVZCUDZRIn19.Q9Ys68biYiwOzBoJZEW6AjSYqXPNEs3Lc-bcRR0iNivImrVptGImNOsPqtSlw5J10i9S7iVmmaobsoGXapyBI6CGYR3j67YNhnTARXNQ81_E0gEUG2QYXblq_8eJmrb7qIKzZVkcSLcGfPrvZV2pIWSxDGLDyZ9LUWaCOiWN0yD9XHaflGO8wpzjDIjjmmHrAQdf2hWZ72Qqwc5HRcURCTW9QAW26EDAAYsOLFbUgxuLXYm6cfk7CwLNa32OU4RbubYhadoLZUAD-St7pRo6hipq92ANxqHLULvlg_zpnV2jK4Ap9dtk6rWytwRV-PXz13MybibND-t9eNsmbCsj9w" } }, "request": { "type": "SessionEndedRequest", "requestId": "amzn1.echo-api.request.1d0fe6ee-607b-4acc-8e13-acfb892683de", "timestamp": "2023-06-25T13:23:08Z", "locale": "de-DE", "reason": "ERROR", "error": { "type": "INVALID_RESPONSE", "message": "An exception occurred while dispatching the request to the skill." } } }

**Comment by justinh998** [comment]
the only thing i can get is the json input from the alexa developer test site.








`{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.3b871408-7a29-4001-b79a-d91864f3b119",
		"application": {
			"applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94"
		},
		"attributes": {},
		"user": {
			"userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q"
		}
	},
	"context": {
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 213,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"mode": "HUB",
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1280,
							"pixelHeight": 800
						}
					}
				}
			}
		],
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 346,
					"arcMinuteHeight": 216,
					"canRotate": false,
					"canResize": false
				}
			],
			"mode": "HUB",
			"shape": "RECTANGLE",
			"pixelWidth": 1280,
			"pixelHeight": 800,
			"dpi": 213,
			"currentPixelWidth": 1280,
			"currentPixelHeight": 800,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Extensions": {
			"available": {
				"aplext:backstack:10": {}
			}
		},
		"Advertising": {
			"advertisingId": "00000000-0000-0000-0000-000000000000",
			"limitAdTracking": true
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94"
			},
			"user": {
				"userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AMA7XWK3IECNKWAIOIJBZXSBRX2UCZ7OTQTOS4VL2L5FHZDZKCEDIKPD2KUKOVSULCLVVGLZPNUZZMH4NNSEYE7JWZBX5BSBSAZC2TADOT3KKSZKHXOGWPN4G5GRCE3QJZYSN5OSASD6J6RECDCX6LKRVHJPAGAEKYF2GWCNJ74EDJ2SXMCABC7FMUQRZFROSX2M4YWK6VE57VQ",
				"supportedInterfaces": {
					"AudioPlayer": {}
				}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5ldS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmViNmVjZjQxLThiZWUtNDY3MC04OWU3LTdiMzQ3MDJkY2I5NCIsImV4cCI6MTY4NzY5OTQ0NSwiaWF0IjoxNjg3Njk5Mzg1LCJuYmYiOjE2ODc2OTkzODUsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFDSy96T3U0MnlEbXR5SWZqcTZ3WnNES2dFQUFBQUFBQUNpbDBKZVYxVHlVTlhuWXNHb21JYWxiaHB2akFWTXkybElaM1ArMGxxNVM1bDNkR1FCNXM5dW5jUHBpbUhwOTAwQlJZZ1JyQ3JoRFlnck5reVZ3bk4xYWlBYzZVck9BNDFVRmVVa0RxT1NmUlBKZjgyNU5CR3hTNDVLTWpnOWNXclF6RkJaU1ZKMk1DSXhLZFhHRDBXbmtFMFEwckVGNHVSUFlCMUdyL2p3R1MvZGRHYXNwVDRkNUxDRWRlUmlCWkQrc0F1VnZQaStpWTdtZUxyWTJNNHR1TGg3MHRITFVXWUorazdwbCtMNXJzTUl0MENNQytwQVBsOHQwLzBQTzBiQmxzTzJlN1FURzdtU0JCa0I2ZmVVVWg0S2c4aFpvcFJ2VWsrUGV1eWJwQUxERHFQazQ5ekpESHBIbnVFSGJxcE5HWGE5UTdyL2JiRXdTNmNvN09YN3hIRmkwdkc3L1d2eHN3bnE3cTIycW1qM1JtbGdaVEVGZ1l5NlJLQkUwb00rSFp2ekEzTmJPVUc4IiwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFNQTdYV0szSUVDTktXQUlPSUpCWlhTQlJYMlVDWjdPVFFUT1M0VkwyTDVGSFpEWktDRURJS1BEMktVS09WU1VMQ0xWVkdMWlBOVVpaTUg0Tk5TRVlFN0pXWkJYNUJTQlNBWkMyVEFET1QzS0tTWktIWE9HV1BONEc1R1JDRTNRSlpZU041T1NBU0Q2SjZSRUNEQ1g2TEtSVkhKUEFHQUVLWUYyR1dDTko3NEVESjJTWE1DQUJDN0ZNVVFSWkZST1NYMk00WVdLNlZFNTdWUSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFNQVpDSUdESUtaVDdKSlRDVDVSVFhVUEdTUFpVRVFNQlBOS0ZBTDVYSEJNMlVVM0NUUkNLU1kzV0xKSVYzRFlEUlAyRVVTUkpDVExIWElIVzdOWUZPTUdVMzNTRUVQTTVCWFNQU0xETkpRWTNPMlY1M1kzNklGNkhHWk5FRVdPVk5aUU1WRFhHWlc0RE1DQUxBUkdKR1BWUks0VjZSSFQ0NVVMRjJIU1VRVllaTkEzRFYyUEdEWE1DTEZWVzRISEpGVDZXWERHSUFSVlpRQ1NCTDVHU1ZaS05ZWjdYSFJGQ05ONVZSRVZCUDZRIn19.Q9Ys68biYiwOzBoJZEW6AjSYqXPNEs3Lc-bcRR0iNivImrVptGImNOsPqtSlw5J10i9S7iVmmaobsoGXapyBI6CGYR3j67YNhnTARXNQ81_E0gEUG2QYXblq_8eJmrb7qIKzZVkcSLcGfPrvZV2pIWSxDGLDyZ9LUWaCOiWN0yD9XHaflGO8wpzjDIjjmmHrAQdf2hWZ72Qqwc5HRcURCTW9QAW26EDAAYsOLFbUgxuLXYm6cfk7CwLNa32OU4RbubYhadoLZUAD-St7pRo6hipq92ANxqHLULvlg_zpnV2jK4Ap9dtk6rWytwRV-PXz13MybibND-t9eNsmbCsj9w"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.653d8cf5-e60c-4210-b279-52e78985d862",
		"locale": "de-DE",
		"timestamp": "2023-06-25T13:23:05Z",
		"intent": {
			"name": "SearchIntent",
			"confirmationStatus": "NONE",
			"slots": {
				"query": {
					"name": "query",
					"value": "abba",
					"confirmationStatus": "NONE",
					"source": "USER",
					"slotValue": {
						"type": "Simple",
						"value": "abba"
					}
				}
			}
		}
	}
}`









`{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.3b871408-7a29-4001-b79a-d91864f3b119",
		"application": {
			"applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94"
		},
		"attributes": {},
		"user": {
			"userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q"
		}
	},
	"context": {
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 213,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"mode": "HUB",
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1280,
							"pixelHeight": 800
						}
					}
				}
			}
		],
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 346,
					"arcMinuteHeight": 216,
					"canRotate": false,
					"canResize": false
				}
			],
			"mode": "HUB",
			"shape": "RECTANGLE",
			"pixelWidth": 1280,
			"pixelHeight": 800,
			"dpi": 213,
			"currentPixelWidth": 1280,
			"currentPixelHeight": 800,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Extensions": {
			"available": {
				"aplext:backstack:10": {}
			}
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.eb6ecf41-8bee-4670-89e7-7b34702dcb94"
			},
			"user": {
				"userId": "amzn1.ask.account.AMAZCIGDIKZT7JJTCT5RTXUPGSPZUEQMBPNKFAL5XHBM2UU3CTRCKSY3WLJIV3DYDRP2EUSRJCTLHXIHW7NYFOMGU33SEEPM5BXSPSLDNJQY3O2V53Y36IF6HGZNEEWOVNZQMVDXGZW4DMCALARGJGPVRK4V6RHT45ULF2HSUQVYZNA3DV2PGDXMCLFVW4HHJFT6WXDGIARVZQCSBL5GSVZKNYZ7XHRFCNN5VREVBP6Q"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AMA7XWK3IECNKWAIOIJBZXSBRX2UCZ7OTQTOS4VL2L5FHZDZKCEDIKPD2KUKOVSULCLVVGLZPNUZZMH4NNSEYE7JWZBX5BSBSAZC2TADOT3KKSZKHXOGWPN4G5GRCE3QJZYSN5OSASD6J6RECDCX6LKRVHJPAGAEKYF2GWCNJ74EDJ2SXMCABC7FMUQRZFROSX2M4YWK6VE57VQ",
				"supportedInterfaces": {
					"AudioPlayer": {}
				}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5ldS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmViNmVjZjQxLThiZWUtNDY3MC04OWU3LTdiMzQ3MDJkY2I5NCIsImV4cCI6MTY4NzY5OTQ0NSwiaWF0IjoxNjg3Njk5Mzg1LCJuYmYiOjE2ODc2OTkzODUsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFDSy96T3U0MnlEbXR5SWZqcTZ3WnNES2dFQUFBQUFBQUNpbDBKZVYxVHlVTlhuWXNHb21JYWxiaHB2akFWTXkybElaM1ArMGxxNVM1bDNkR1FCNXM5dW5jUHBpbUhwOTAwQlJZZ1JyQ3JoRFlnck5reVZ3bk4xYWlBYzZVck9BNDFVRmVVa0RxT1NmUlBKZjgyNU5CR3hTNDVLTWpnOWNXclF6RkJaU1ZKMk1DSXhLZFhHRDBXbmtFMFEwckVGNHVSUFlCMUdyL2p3R1MvZGRHYXNwVDRkNUxDRWRlUmlCWkQrc0F1VnZQaStpWTdtZUxyWTJNNHR1TGg3MHRITFVXWUorazdwbCtMNXJzTUl0MENNQytwQVBsOHQwLzBQTzBiQmxzTzJlN1FURzdtU0JCa0I2ZmVVVWg0S2c4aFpvcFJ2VWsrUGV1eWJwQUxERHFQazQ5ekpESHBIbnVFSGJxcE5HWGE5UTdyL2JiRXdTNmNvN09YN3hIRmkwdkc3L1d2eHN3bnE3cTIycW1qM1JtbGdaVEVGZ1l5NlJLQkUwb00rSFp2ekEzTmJPVUc4IiwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFNQTdYV0szSUVDTktXQUlPSUpCWlhTQlJYMlVDWjdPVFFUT1M0VkwyTDVGSFpEWktDRURJS1BEMktVS09WU1VMQ0xWVkdMWlBOVVpaTUg0Tk5TRVlFN0pXWkJYNUJTQlNBWkMyVEFET1QzS0tTWktIWE9HV1BONEc1R1JDRTNRSlpZU041T1NBU0Q2SjZSRUNEQ1g2TEtSVkhKUEFHQUVLWUYyR1dDTko3NEVESjJTWE1DQUJDN0ZNVVFSWkZST1NYMk00WVdLNlZFNTdWUSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFNQVpDSUdESUtaVDdKSlRDVDVSVFhVUEdTUFpVRVFNQlBOS0ZBTDVYSEJNMlVVM0NUUkNLU1kzV0xKSVYzRFlEUlAyRVVTUkpDVExIWElIVzdOWUZPTUdVMzNTRUVQTTVCWFNQU0xETkpRWTNPMlY1M1kzNklGNkhHWk5FRVdPVk5aUU1WRFhHWlc0RE1DQUxBUkdKR1BWUks0VjZSSFQ0NVVMRjJIU1VRVllaTkEzRFYyUEdEWE1DTEZWVzRISEpGVDZXWERHSUFSVlpRQ1NCTDVHU1ZaS05ZWjdYSFJGQ05ONVZSRVZCUDZRIn19.Q9Ys68biYiwOzBoJZEW6AjSYqXPNEs3Lc-bcRR0iNivImrVptGImNOsPqtSlw5J10i9S7iVmmaobsoGXapyBI6CGYR3j67YNhnTARXNQ81_E0gEUG2QYXblq_8eJmrb7qIKzZVkcSLcGfPrvZV2pIWSxDGLDyZ9LUWaCOiWN0yD9XHaflGO8wpzjDIjjmmHrAQdf2hWZ72Qqwc5HRcURCTW9QAW26EDAAYsOLFbUgxuLXYm6cfk7CwLNa32OU4RbubYhadoLZUAD-St7pRo6hipq92ANxqHLULvlg_zpnV2jK4Ap9dtk6rWytwRV-PXz13MybibND-t9eNsmbCsj9w"
		}
	},
	"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.1d0fe6ee-607b-4acc-8e13-acfb892683de",
		"timestamp": "2023-06-25T13:23:08Z",
		"locale": "de-DE",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "An exception occurred while dispatching the request to the skill."
		}
	}
}`

**Comment by ndg63276** [comment]
It works if you pay :)

**Comment by justinh998** [comment]
I had because of @79812b comment here:https://github.com/ndg63276/alexa-youtube/issues/152
Hope that I will be helped here even if I have my own lambda instance, I mean under point 3 is even asked whether man uses your or his own instance.
