### ISSUE TITLE
Cannot add a new playlist to Alexa YouTube Favorites list?

### ISSUE THREAD

**Issue by jimrin** [ndg63276/alexa-youtube#155]
It's been working flawlessly ever since signing up. I then decided to put the Unicode music symbol 🎵 in my playlist name (for example 🎵Foxtrot music) to make it easier to recognize my YouTube playlists which are songs.  Unfortunately, the skill when reading the name gets confused and stops while reading the name and doesn't play any songs...

I placed the name in the YouTube playlist name and not in the Alexa YouTube Favorites list.

But that's not what I am writing about (although it would be great if the above can be fixed).

I decided that in the meantime, I'll copy the playlist to another playlist on another YouTube account without the music symbol. However, when I tried to replace the old URL with the new one, I get the error "There was a problem with the requested skills response." I also created a routine which would say the command so that I can simplify what I tell Alexa to "I want to listen to Foxtrot music" and when I hit the play button to test the skill, I get the same error. Note that it used to work ok... and all the other playlists work ok except for the fact the skill stops when having problems with 🎵 in the playlist name.  I have one playlist where I had not done that yet, and it plays ok.  Also, all other commands to the skill work ok (such as Play videos by the Beatles)

I then tried to create a new entry in YouTube Favorites with the same URL, and I got the same error. Then I tried a brand new playlist and added it and still got the same error.

PS. This is my mom's account. I also have an account, but I haven't tried to see if I experience the same problems as she does.

Please provide the following information:

1. What are you saying to Alexa? "Ask YouTube playlist [my name for the skill] to play Foxtrot music"
2. What video are you trying to play? Please provide the youtube URL. https://www.youtube.com/playlist?list=PLj4AA94NBavpGV2xcaLOIpnDb6xjyCPSL
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?) arn:aws:lambda:us-east-1:175548706300:function:yokogolferecho
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems. n/a
5. What language are you using? English although I have Japanese also enabled. Again, nothing has changed in months...

**Comment by ndg63276** [comment]
One problem is that your new playlist isn't public, so the skill can't see it (I should probably make it say something to that effect).

**Comment by jimrin** [comment]
Ugh! Sorry, user error! I had not realized that even though I specified Unlisted for the playlist, since I used a different YouTube account, it was not saving the Unlisted designation until I first create a public channel for the account...  It's working now! Thanks!

Now if it's possible to have the music symbol in the playlist, I wouldn't need to create these duplicate playlists...? Here is an example: https://www.youtube.com/playlist?list=PLcOl0UgBbJgwp_z3SNJ_P1ikiyOdWEWa2

**Comment by ndg63276** [comment]
I don't see the Foxtrot music playlist on https://www.youtube.com/@msyokogolfer/playlists although I can see the playlist itself. Is it "unlisted" perhaps. The Alexa app works ok with your West Coast Swing playlist which also has the musical note symbol.
