### ISSUE TITLE
Latest Lambda_Function.zip too large so cant do inline editing

### ISSUE THREAD

**Issue by tal9000v2** [ndg63276/alexa-youtube#16]
@ndg63276  Just an fyi. Doesn't really impact me but with the latest update, it looks like the zipfile exceeds 3mb so inline editing is disabled in the Lambda Functions. 
![image](https://user-images.githubusercontent.com/7674619/50059504-9e7a6e00-013c-11e9-9251-0a0a3fd0aba3.png)
This does NOT impact any functionality. It all still works. Just need to add the DEVELOPER_KEY variable with your Google API key.
I haven't attempted to see if Cloud9 can be used with Lambda functions. But just making folks aware that inline editing will not be available (not that most will need it, since you've already taken care of everything). Thanks!

**Comment by ndg63276** [comment]
Yes, I noticed that, not sure why the latest version is so much bigger, it was <1mb before. Will have a look tomorrow.

**Comment by ndg63276** [comment]
Ah, that makes sense, I'm no good with zip on linux. See https://xkcd.com/1168/.

Have updated the zip.
