### ISSUE TITLE
Stop or Pausing?

### ISSUE THREAD

**Issue by christ59** [ndg63276/alexa-youtube#17]
I understood that putting a pause allowed to resume a music. Alas, it interferes with commands other than this Skill.
Example: with my Echo, I start a music with this Skill. I say "STOP", Skill pauses and says "pausing". I ask Alexa to turn on my plug connected, and if I misunderstood my request, she said "pausing"! So she should tell me "I did not understand ...". As a result, we do not know if our request was poorly formulated !!!
It is impossible to end this Skill.
What should I change in the code to replace the "pause" with a "stop" that leaves the skill?
Thank you.

**Comment by ndg63276** [comment]
Not possible as far as I know. When you say "Alexa, Stop", I send an AudioPlayer.Stop directive, with shouldEndSession set to True.

Do you get the same issue with other audio skills, eg Spotify, TuneIn?

**Comment by christ59** [comment]
I only have Amazon Music. And I do not have this problem with it. According to the forums, there would be a problem with the AudioPlayer.Stop which would return a "pause" instead of a "stop".

I can not reproduce this problem when I test in my browser. The "stop" seems to work. But not with an Echo.

**Comment by christ59** [comment]
I bypassed the problem by adding the attention words "quit" and "go out" in the intent "stop". Now it works.

**Comment by ndg63276** [comment]
Sorry, where did you add the words `quit` and `go out`?

**Comment by christ59** [comment]
Intents : AMAZON.StopIntent
Add 3 utterances (here I put the words I wanted to leave the Skill (French allows you to have more choice than the language of Shakespeare, so I can not translate them :))

**Comment by tal9000v2** [comment]
Try saying "cancel". That will do what you want.
