### ISSUE TITLE
Default ARN uses french language by default

### ISSUE THREAD

**Issue by dragos240** [ndg63276/alexa-youtube#18]
I recently started hearing "lecture de NAME" whenever playing a video and "en pause" when stopping/pausing using the default ARN despite the fact that it was previously using English. I see you have added a French language option, but it looks like it selects it by default.

**Comment by ndg63276** [comment]
Strange, I don't get that here. It defaults to English, and only goes into French if the 'locale' received from Amazon is set to "fr-*".

Can you check, if you go to https://developer.amazon.com/alexa/console/ask#/skills, the YouTube skill is not set to any French language option?

**Comment by dragos240** [comment]
It says "English (US)" under "Language".

**Comment by ndg63276** [comment]
Hmmm... I managed to make it happen for me in testing, not sure how. Something is misbehaving...

**Comment by ndg63276** [comment]
Ok, I think if your session was still in memory, it could get stuck in French, as it never checked the default. It now is forced to choose every time. Reopen if you still get the problem.
