### ISSUE TITLE
Setting up Lambda

### ISSUE THREAD

**Issue by tony4212** [ndg63276/alexa-youtube#2]
When uploading the lambda_function.zip into AWS it indicates that the index.js does not exist. I don't know if this is directly impacting the Alexa skill that I've made, but when testing it I get "There was a problem with the requested skill's response".  On another note when using your Lambda I don't have a problem.

**Comment by LunarstarPony** [comment]
Hai

**Comment by LunarstarPony** [comment]
Im just asking where is environment variable DEVELOPER_KEY

**Comment by LunarstarPony** [comment]
Did this mean the Skill ID?
