### ISSUE TITLE
Title output, but no Music

### ISSUE THREAD

**Issue by FlorianMathis** [ndg63276/alexa-youtube#20]
Hi all,

I'm getting the response of a query from my test environemnt but my Alexa just says the title without playing the music afterwards. When I ask directly my alexa it says: "I couldn't find any enabled video skills that can play that. Go to the Alexa App to manage your video skills and devices.".

Anyone got the same problem + a solution?

Best,
flo

**Comment by tydell** [comment]
I got the same or got silence, but no music at all. So at the moment it doesn't work for me :(

**Comment by FlorianMathis** [comment]
@tydell Did it work some time ago? I set it up yesterday and could it never get working :(

**Comment by FlorianMathis** [comment]
@tydell I got it to work by changing my language settings to EN (UK). Does that help in your case as well?

**Comment by tydell** [comment]
On Test tab in Alexa Developer Console i get proper output, however with adnotation 'Unsupported Directive AudioPlayer is currently an unsupported namespace. Check the device log for more information.'
On my Amazon Echo device i got nothing or it says, that Spotify account can't handle this :(

**Comment by ndg63276** [comment]
@tydell - 'Unsupported Directive AudioPlayer is currently an unsupported namespace. Check the device log for more information.' - This is normal, the Developer Console doesn't play audio.

**Comment by ndg63276** [comment]
Anyone getting messages about Spotify, or "I couldn't find any enabled video skills", that's on Amazon's side. Make sure you are in this skill by starting with "Alexa, open YouTube". Then ask for whatever you want. If you still have problems, please post exactly what you are saying to Alexa, so I can try and reproduce it.

**Comment by ndg63276** [comment]
@aNNdr58 - can you go to https://developer.amazon.com/alexa/console/ask, click on the YouTube skill, then click Test at the top. If it says "Test is disabled for this skill", then change the dropdown to Development. Hopefully that will fix it.

**Comment by aNNdr58** [comment]
It is already set to development. It works in the simulator online, but when i try it on my own Alexa, "I couldn't find any enabled video skills" comes up.

**Comment by ndg63276** [comment]
@aNNdr58 - Make sure the language in the skill setup at https://developer.amazon.com/alexa/console/ask is the same as your Alexa is set to. So if you are in Canada, make sure it is English (CA).

If it is not, go to that link, go into YouTube, click the language drop down, and select Language Settings. Then you can Add a New Language. Save it, then click Build at the top, select the new language from the dropdown, go to JSON Editor, and copy in the InteractionModel_en.json file from this repository. There are also French and Italian versions available.

**Comment by aNNdr58** [comment]
Had to change the language on my Echo Dot to make it work, but everything works fine now. Thank you!

**Comment by FlorianMathis** [comment]
@ndg63276 Thanks for your support! :)
