### ISSUE TITLE
Issues with Skipping Playlists

### ISSUE THREAD

**Issue by coot66** [ndg63276/alexa-youtube#21]
I'm having issues with it skipping playlists instead of going to the next song. I'm not sure if it thinks there are fewer songs in the playlist than there actually are or if it's a different type of issue. Playlist has 100+ songs.

Steps to reproduce: 

I say "Alexa, ask YouTube to shuffle playlist XXXX" It plays the a few songs (at best) from the play list and then will move to the new playlist. 

The same thing can happen when I say "Alexa, next" after initiating the shuffle.

I have the latest version from 6 days ago installed.

**Comment by ndg63276** [comment]
Can you tell me the exact playlist you are trying to play? Title, and URL on youtube.com. It makes it easier to reproduce.

**Comment by coot66** [comment]
OK, I think that my issue was on my end @FlorianMathis + @ndg63276 

I thought it was skipping playlists but I think it was just going to the next song and announcing the title. My songs are in a different language with mostly Cyrillic titles which resulted in it saying things like "Now Playing -". 

One thing I'm still curious about is how the "shuffle" function works. Does it actually track what songs were played previously or does it just pick a random one from the playlist each time? I had several occurrences where I had ask to shuffle the playlist and then it repeats a song a few songs later (either organically or after I skip it).

**Comment by ndg63276** [comment]
@coot66 - Shuffle doesn't keep track of what has been played, it just picks a random number and goes to that item in the playlist. So it should keep going forever in theory.

I did find a bug, where the items in the playlist were numbered eg 0-9, and it would choose a random integer from 1-10, so when number 10 came up it would fail. That has now been fixed. Let me know if you still have problems.
