### ISSUE TITLE
No Audio Playback On SONOS speaker

### ISSUE THREAD

**Issue by roccafrancesco** [ndg63276/alexa-youtube#22]
Hello Everybody
after tested different skill Alexa founded on github I can say that no one works well. I mean that all skill that use only Lambda function has the same problem: no audio playback on speaker(for exaple sonos). Everything works if it si reproduced on android smartphone but when you call alexa from speaker, alexa answer well "i m playing" but nothing happen.
With the last modification,is this problem solved?
thanks in advance  
Francesco

**Comment by ndg63276** [comment]
Hi, I'm the developer here, I can tell you it does work. Does it work flawlessly? No.

Can you tell me what video you are trying to play?

**Comment by roccafrancesco** [comment]
hi
i tested again the skill with your endpoint: nothing to do; the audio playback is absent. Alexa continue answering well "i'm playing" but the audio is missing. i think the problem is that the lambda function doesn't bufferize the stream. 
what can i do?
Francesco

**Comment by ndg63276** [comment]
Lambda doesn't bufferize anything, it just sends a URL to an audio file, your Alexa device then plays it. 

Can you tell me what video you are trying to play?

**Comment by roccafrancesco** [comment]
hi, in URL what kind of file is present? mp4, mp3....ecc? File format could be not supported by the speaker; i don't think the speaker can transcode the source.
I saw other version of alexa skill where it was involved also dropbox repository as a temporary URL ;in this way the youtube original url was converted in line  in mp3  format and put in dropbox URL..
Did you try your skill also with alexa speaker echo or whatever? Or Did you try the skill only with android system?
Thank you

**Comment by ndg63276** [comment]
The URL is an mp4 link. If you would like to see an example, go to https://repl.it/@ndg63276/PyTubeTester, press the Run button at the top, then on the right it will ask you for a YouTube URL (eg https://www.youtube.com/watch?v=C6MOKXm8x50). It will then give you a very long URL which should work in a browser to play just the audio. They only work for a limited time, so you have to generate them in this way.

From your link, it looks like Sonos doesn't support mp4. The only other option would be webm, which isn't supported either.

**Comment by roccafrancesco** [comment]
ok.  i will try other solution.
thank you
