### ISSUE TITLE
Add fast forward and rewind?

### ISSUE THREAD

**Issue by raj2ras** [ndg63276/alexa-youtube#23]
Is it hard to add a feature to "Fast Forward & Rewind"; by number of minutes, or to a point in the track?

**Comment by ndg63276** [comment]
Yep, good idea, have done it elsewhere, so starting to add it.

**Comment by ndg63276** [comment]
OK, I've implemented this. Firstly, you need to re-upload the file https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_en.json to the JSON editor in Amazon Developer Console. Steps 6,7,8 & 14 from the Readme.

Then you have to say, for example, (when a video is playing):
"Alexa, **ask YouTube to** skip forward 10 minutes" or
"Alexa, **ask YouTube to** skip backward 10 minutes" or
"Alexa, **ask YouTube to** skip to 30 minutes"

You can say x hours, y minutes, and z seconds, or any combination of the three.

It's really easy to forget the Ask YouTube part, and then she just says "Sorry, I'm not sure".

**Comment by ndg63276** [comment]
At the moment, this is only available in English. So I need to ask @mariodmmariodm and @christ59 if they are able to translate to Italian and French? I need the following translations:

"Sorry, I didn't hear how much to skip by."
"Sorry, I didn't hear where to skip to."
"OK"

And also a lot of sample phrases in InteractionModel_en.json.

**Comment by christ59** [comment]
Hello. Super the option to move forward or backward.
These two sentences can be translated into French in the same way.
"**Désolé, je n'ai pas compris de combien je devais avancer ou reculer.**"

**Comment by mariodmmariodm** [comment]
Json file in italian is here https://drive.google.com/open?id=1EAhyPU-QKa3Ak5SXRK82w0S1lo2lIuRb

also corrected other things, now you can chide "Alexa, chiedi a TouTube di riprodurre ..."

Then? have you tried to publish it in the store?

**Comment by mariodmmariodm** [comment]
here new json file!!  https://drive.google.com/open?id=1axIuChgct1WhFWKRPaaiBOyOwXyDP5fO

**Comment by ndg63276** [comment]
OK changed :)

**Comment by raj2ras** [comment]
Thank you so much!  Updated the skills json -> did not work, but then realised that I have to update my AWS Lambda function too :-) Works perfectly now

**Comment by ndg63276** [comment]
@christ59 - Would you be able to translate the InteractionModel_en.json into French? I realise I added loads of sample phrases, feel free to cut it down a bit!

**Comment by christ59** [comment]
OK.
[InteractionModel_fr.zip](https://github.com/ndg63276/alexa-youtube/files/2723123/InteractionModel_fr.zip)
I think there should be some timing for the Skill to stop itself because, 2 days after launching the Skill, I realized that she was still active.
Thanks.

**Comment by raj2ras** [comment]
@ndg63276 - Does not skip forward or rewind! Just says "OK", but does resumes from old point. Trying to figure out what's going on. Tried the following:
-Changing Lambda regions
-Trying your lambda vs. mine
-Switching alexa languages from Eng_US and UK

I am in Canada hence use US English and AWS US East

**Comment by ndg63276** [comment]
@raj2ras - How odd, it works here. If you use your lambda instance, then go to lambda, click Monitoring in the top left, and then View Logs in Cloudwatch, it should take you to some logs. Have a look and see if you can see any errors?

**Comment by raj2ras** [comment]
Here is part of the log, cannot make sense more thant seeing that Request is registered!

`REPORT RequestId: 314f9d50-0fb1-11e9-a320-2f4f57d2d561	Duration: 0.27 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 52 MB	
START RequestId: 33b811f1-0fb1-11e9-950b-05bd8128782e Version: $LATEST
[INFO]	2019-01-03T23:42:16.311Z	33b811f1-0fb1-11e9-950b-05bd8128782e	{u'slots': {u'hours': {u'name': u'hours', u'confirmationStatus': u'NONE'}, u'seconds': {u'name': u'seconds', u'confirmationStatus': u'NONE'}, u'minutes': {u'source': u'USER', u'name': u'minutes', u'value': u'10', u'confirmationStatus': u'NONE'}}, u'name': u'SkipForwardIntent', u'confirmationStatus': u'NONE'}
[INFO]	2019-01-03T23:42:16.312Z	33b811f1-0fb1-11e9-950b-05bd8128782e	Getting url for https://www.youtube.com/watch?v=VhkfnPVQyaY
[INFO]	2019-01-03T23:42:17.548Z	33b811f1-0fb1-11e9-950b-05bd8128782e	https://r4---sn-tt1e7nel.googlevideo.com/videoplayback?c=WEB&mm=31,26&ipbits=0&source=youtube&dur=3500.338&clen=55594515&ei=2J0uXKiOGZDGhgaxrI2wAg&keepalive=yes&itag=140&signature=10B38BFA718F96C310C434C07F1AB740C474427A.5C622995FAFA689F7120745FF7F74B3700D570E6&requiressl=yes&expire=1546580536&lmt=1537647740774677&gir=yes&ip=3.84.149.184&key=yt6&mn=sn-tt1e7nel,sn-q4flrn7r&fvip=4&ms=au,onr&mt=1546558598&sparams=clen,dur,ei,gir,id,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,expire&mv=u&id=o-ACKr7N3dqd_O0frRDHZ5P6QSAlxJ57ycqPR20X9vLyTC&mime=audio/mp4&pl=24
END RequestId: 33b811f1-0fb1-11e9-950b-05bd8128782e
REPORT RequestId: 33b811f1-0fb1-11e9-950b-05bd8128782e	Duration: 1237.58 ms	Billed Duration: 1300 ms Memory Size: 512 MB	Max Memory Used: 52 MB	
START RequestId: 357dde8e-0fb1-11e9-9f5a-6fc246e470cf Version: $LATEST
[INFO]	2019-01-03T23:42:19.266Z	357dde8e-0fb1-11e9-9f5a-6fc246e470cf	Started
END RequestId: 357dde8e-0fb1-11e9-9f5a-6fc246e470cf
REPORT RequestId: 357dde8e-0fb1-11e9-9f5a-6fc246e470cf	Duration: 0.53 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 52 MB	
START RequestId: 357fd989-0fb1-11e9-9eea-b3538ea6ba7b Version: $LATEST
END RequestId: 357fd989-0fb1-11e9-9eea-b3538ea6ba7b
REPORT RequestId: 357fd989-0fb1-11e9-9eea-b3538ea6ba7b	Duration: 0.25 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 52 MB	`

**Comment by ndg63276** [comment]
No, no errors seemingly. And it recognised you wanted to fast forward by 10 minutes. I will try it on that video later on my Echo, see if I get any problems.

**Comment by christ59** [comment]
Maybe the video is less than 10 minutes long?

**Comment by mariodmmariodm** [comment]
Hi, how does it behave with google ads?

can you also try this video if it goes into actual play on echo? Ask "Kashmir Kashmir"...

https://youtu.be/6hfGdLPTQpg

Thanks

**Comment by raj2ras** [comment]
@christ59 , no it is longer than 10mins https://www.youtube.com/watch?v=VhkfnPVQyaY

Same results on all videos. Everything works except Rewind/Forward. I am using my own Youtube API code, my own lambda (used the new zip).

@mariodmmariodm 
The API data does not serve Ads (IMO). Also I doubt if having or not having YouTube premium affects the API?

**Comment by mariodmmariodm** [comment]
did you try that video? the song does not start.

**Comment by ndg63276** [comment]
@mariodmmariodm - That video doesn't play for me. If you put the address into https://repl.it/@ndg63276/PyTubeTester, you'll get "This video is unavailable". I don't know why, and I can't fix it, sorry.

**Comment by ndg63276** [comment]
@raj2ras - I get the same error as well now. Not sure why...

**Comment by mariodmmariodm** [comment]
thanks, is it perhaps limited to Italy?... mmmm

**Comment by ndg63276** [comment]
@raj2ras - I get the problem on my 1st Gen Echo, but not on my Echo Dot. Which do you have?

Weirdly, the pause and resume functions work in the same way as the fast forward function, and that works fine on both.

**Comment by raj2ras** [comment]
@ndg63276 - I have the tall Echo. i.e. Gen 1 (2 of them). Could it be related to a certain version of pyTube that does not assemble the URL in a way YouTube API wants?

**Comment by raj2ras** [comment]
@ndg63276 - so are you saying the problem of "Rewind/Forward" not working is limited only to Gen 1 echos? Perplexing.

**Comment by ndg63276** [comment]
Certainly seems that way. And other skills I write have the same code, and work fine, but they play mp3s. (eg https://www.amazon.com/dp/B07JHQS63V/).

Not sure there is anything else I can do at this point.

**Comment by raj2ras** [comment]
@ndg63276 - does the skill always play mp4a streams? Does Youtube offer mp3 audio streams (for e.g. for older videos)? I would like to test this skill on Gen 1 with a mp3 stream. 

That way we can be sure that mp4a playback on Gen 1 is different from the newer echoes.

**Comment by ndg63276** [comment]
Youtube doesn't offer mp3 streams. Some videos have webm audio streams, I will try and test one later.

**Comment by ndg63276** [comment]
In another ticket, I have found that Gen 1 Echos don't work with m3u8 files, for live streaming. So it definitely seems like some functions behave differently on different models.

I've put a comment in the README that this doesn't work on Gen 1 Echos. Closing the ticket.
