### ISSUE TITLE
Spanish/German Translations

### ISSUE THREAD

**Issue by ndg63276** [ndg63276/alexa-youtube#24]
If anyone can translate English to Spanish for me, that would be great. Currently we have French and Italian.

First you would need to translate part of this file:
https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_en.json
Anything that is in a "samples" section needs translating, apart from anything in {curly brackets}.

Then you would need to go to this file:
https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/lambda_function.py
and translate all the sentences in the section that says "strings_en = { ... }"

**Comment by tydell** [comment]
Translation to any other language will be the same work to do? I would like to do German translation, there is no such translation at the moment.

**Comment by ndg63276** [comment]
Yes, exactly the same, German would be great, thanks!

**Comment by DAVIDPATRICIO** [comment]
LUEGO DE TRADUCIR AL ESPAÑOL DONO PONGO LOS CÓDIGO

**Comment by tydell** [comment]
Here you go, german translation:
[https://raw.githubusercontent.com/tydell/alexa-youtube/master/InteractionModel_de.json](url)
[https://github.com/tydell/alexa-youtube/raw/master/lambda_function.py](url)

I hope that there are no syntax errors

**Comment by ndg63276** [comment]
Brilliant, thanks, that's great, and I've put them in my repo.

The only 2 things I found were, in the json file, on 3 lines (139, 146, 153) there were different speech marks, ” instead of ". And in the lambda file, I had to add 2 lines to make it use strings_de, eg
```
    elif event['request']['locale'][0:2] == 'de':
        strings = strings_de
```
If you want to use it, go to the Developer Console (https://developer.amazon.com/alexa/console/ask), add German as a language, and upload my json file (https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_de.json). Make sure to Save and Build it.

If you have deployed your own Lambda instance, you'll also need to re-upload the lambda_function.zip file to Lambda.

**Comment by DAVIDPATRICIO** [comment]
HOLA PUEDES TRADUCIRLO AL ESPAÑOL

**Comment by ndg63276** [comment]
@DAVIDPATRICIO - no puedo hablar espanol.

**Comment by ndg63276** [comment]
Spanish is now available, thanks to @leoyodar for the translations.

**Comment by katshun0307** [comment]
Can I add Japanese translation? (also for me to use )

**Comment by ndg63276** [comment]
@katshun0307 - absolutely. I have created a new issue, #47 for this.
