### ISSUE TITLE
enable multiroom

### ISSUE THREAD

**Issue by mabadil** [ndg63276/alexa-youtube#27]
could you enable a multi room function?

**Comment by ndg63276** [comment]
Sorry, no, Amazon doesn't provide this ability to 3rd parties, unless your a massive deal like Spotify or Apple Music.

**Comment by mabadil** [comment]
also whit music skill api?

https://developer.amazon.com/it/docs/music-skills/understand-the-music-skill-api.html

Il giorno dom 6 gen 2019 alle ore 15:14 ndg63276 <notifications@github.com>
ha scritto:

**Comment by ndg63276** [comment]
I guess, maybe. But that would require me to rewrite the entire skill. So no.
