### ISSUE TITLE
Help with playing to groups

### ISSUE THREAD

**Issue by mcc05** [ndg63276/alexa-youtube#28]
Firstly let me say this skill is great.....

So can't get it to play to a multi echo group for example. 

If I say ask youtube play "music" "everywhere", it takes "everywhere as being the song title, is it possible to add a new intent or something to allow this?

**Comment by ndg63276** [comment]
Sorry, this isn't possible, as far as I know.

**Comment by mcc05** [comment]
Ok, but that strange because I'm in the UK and I can say for example play "radio 1" " everywhere" or "upstairs" etc and it works so if the MS API is not available here then it shouldn't work??

**Comment by ndg63276** [comment]
Yeah I think Amazon works with big companies like TuneIn and Spotify to get that stuff to work.

**Comment by ndg63276** [comment]
Not going to happen I'm afraid.
