### ISSUE TITLE
Live video playback

### ISSUE THREAD

**Issue by ThatOneCalculator** [ndg63276/alexa-youtube#29]
Hey, about a week ago, live videos stopped working. Regular videos still work, but when I want to listen to 24/7 study beat livestreams  (which is the only reason i use this skill) it gives me an error :( Any help?

**Comment by ndg63276** [comment]
Yep, sorry, looks like Google changed something. Hopefully someone smarter than me can figure it out eg on https://github.com/rg3/youtube-dl/issues/18802.

**Comment by ndg63276** [comment]
@navid1981 - thanks, that's awesome. I ended up bastardizing some code from youtube-dl, as it was python, but yours is a lot neater.

Now I'm finding that Alexa plays the first few seconds of the video, and then stops, as I don't think she refreshes the m3u8 file. The video works ok on my Echo Spot, but audio only on my Gen1 Echo and Echo Dot fails. Will keep looking, but test and see if it works for you.

**Comment by ThatOneCalculator** [comment]
Hey, on my echo Dot gen 3, it started working again 😀

**Comment by ndg63276** [comment]
Yep, working again on my gen 2 Dot. I guess the 1st Gen Echo's don't like m3u8 files, but anything newer does.

I'm going to change it tonight to use navid's code, it still works for me, but if it breaks for you, re-open the ticket.
