### ISSUE TITLE
Where ia the environment variable DEVELOPER_KEY,

### ISSUE THREAD

**Issue by LunarstarPony** [ndg63276/alexa-youtube#3]
Skill ID ? Or

**Comment by Smanar** [comment]
In the lambda management Console, Under the code.

**Comment by LunarstarPony** [comment]
i know 
i mean type what?

**Comment by LunarstarPony** [comment]
@Smanar i mean what should i type in key and Value? 
Skill ID?

**Comment by Smanar** [comment]
> youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)

It's the youtupe api key.

**Comment by LunarstarPony** [comment]
So wut should i type in that two box  or where can i get it

**Comment by Smanar** [comment]
Oups, sorry, I haven't see it's not on the "How to".
You have more information here > https://www.slickremix.com/docs/get-api-key-for-youtube/

But this github code is rly hard to use as it.

**Comment by LunarstarPony** [comment]
That shout type in Value Right?

**Comment by Smanar** [comment]
On environemnt variables:
left box (key):  DEVELOPER_KEY
right box (value): ASH88GG4455GGH

**Comment by LunarstarPony** [comment]
Done its working

**Comment by LunarstarPony** [comment]
And can i let this skill just stop playing after finish one song?

**Comment by Smanar** [comment]
I think no, even the classic search, look for 50 result, so I think you have a music list at every try.

**Comment by LunarstarPony** [comment]
I search for a music and when That music is done its just go to anoyher random music and get back to old one

**Comment by changetotower** [comment]
Hi. 
After uploading the lambda_function.zip, I received the following error message: 
"Could not open file: /index.js The file could not be found on the file system.".
Thanks.

**Comment by ndg63276** [comment]
Have added that link for getting a YouTube API key, thanks @Smanar.

If you want it to just play one song each time, after you have uploaded the zip file, edit lambda_function.py to change `maxResults=50` to `maxResults=1`. You may get times when nothing plays, not every video works for some reason.
