### ISSUE TITLE
Cannot get YouTube to open on Echo Dot; Works fine testing online

### ISSUE THREAD

**Issue by jonathanaltman** [ndg63276/alexa-youtube#31]
When trying to open YouTube on Alexa, it works through development testing on the Alexa Development website, but does not work through my 3rd-generation Echo Dot. I have tried switching the invocation to other commands, such as youtube player, and while everything works on the website, nothing works on my Dot. I get "I don't know that one" or the video skills error. My Dot is in English, and I can see the program in the Alexa app on my phone. I am using the default lambda instance. I am in Canada if that affects anything.

**Comment by jonathanaltman** [comment]
I tried remaking the program in English (Canada) and it worked. Closing the issue.

**Comment by wb1234** [comment]
Hi jonathan, I am also in Canada and i am having the same problem setting up the "youtube skill" for my Alexa dot. Could you please tell me how you were able to make this work on your Alex echo dot 3rd gen device?

**Comment by jonathanaltman** [comment]
> Hi jonathan, I am also in Canada and i am having the same problem setting up the "youtube skill" for my Alexa dot. Could you please tell me how you were able to make this work on your Alex echo dot 3rd gen device? My "testing" is also enabled as per the #15 instruction.

You have to make sure that the language of your program is set to English (Canada), not English (US). If it isn't, remake the program and ensure the new program is set to Canadian English.
