### ISSUE TITLE
Add the ability to ask Alexa the current time in the video

### ISSUE THREAD

**Issue by jonathanaltman** [ndg63276/alexa-youtube#32]
It would be useful to be able to ask how far through a video I am.

**Comment by ndg63276** [comment]
OK, now available in English.

1. Go to https://developer.amazon.com/alexa/console/ask, and go to your Youtube skill.
2. On the left, scroll down and click JSON Editor.
3. Copy and paste in the contents of https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_en.json
4. Click Save Model, and then Build Model.
5. If you have deployed your own lambda instance, re-upload the lambda_function.zip file.
6. When a video is playing, say "Alexa, ask YouTube what is the current timestamp"
