### ISSUE TITLE
no function - alexa says no video playback device

### ISSUE THREAD

**Issue by mc-chick** [ndg63276/alexa-youtube#35]
The skill doesn't work. alexa says eyery time - there is no video skill for playback ... :(

**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
> starte youtube
or
> starte youtube spiele ...

2. What video are you trying to play? Please provide the youtube URL.
e.g. https://www.youtube.com/watch?v=LsgTXKba6wI

3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
> using your lambda instance

4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?
> german

**Comment by ndg63276** [comment]
Make sure you have followed step 15, making the skill available for testing in development mode.

**Comment by mc-chick** [comment]
double checked ... testing is enabled :(

**Comment by ndg63276** [comment]
What device are you using?

**Comment by mc-chick** [comment]
echo dot second and third generation ... and the smartphone app ...

**Comment by mc-chick** [comment]
strange is the fact that alexa says "there is no activated video skill ..." already if i say "alexa starte youtube" - seems like the skill doesn't start ?!

**Comment by ndg63276** [comment]
If you go to the place you enabled testing for step 15, and type in the box 'öffne youtube', what does it say? When I test in German, it fails if I type 'starte youtube', but works when I type 'öffne youtube'.

**Comment by mc-chick** [comment]
it works !!! "öffne youtube" was the "key" :) ... but one question, if i say "Alexa stop" the answer ist "pausieren" (paused) - how do i really stop the playing? or is it a feature from the skill only to pause the track?

**Comment by ndg63276** [comment]
That is normal. It doesn't really pause, just remembers where it got to, so you can resume, as long as you don't use any other audio skill.
