### ISSUE TITLE
Cannot get YouTube to open on Echo Dot; Works fine testing online 

### ISSUE THREAD

**Issue by wb1234** [ndg63276/alexa-youtube#36]
When trying to open YouTube on Alexa, it works through development testing on the Alexa Development website, but does not work through my 3rd-generation Echo Dot. I have tried switching the invocation to other commands, such as youtube player, and while everything works on the website, nothing works on my Dot. I get "I don't know that one" or the video skills error. My Dot is in English, and I can see the program in the Alexa app on my phone. I am using the default lambda instance. I am in Canada if that affects anything.

**Comment by ndg63276** [comment]
Have you set the skill to "English (CA)". That was the problem someone else had.

**Comment by wb1234** [comment]
Is there a way to remove the amazon prime skill from the echo dot.

**Comment by ndg63276** [comment]
Not as far as I know.

**Comment by sherlockthegreat** [comment]
When trying to open YouTube on Alexa, it works through development testing on the Alexa Development website but does not work through my 3rd-generation Echo Dot.  I get "I couldn't find any video-enabled skills" I don't know that one" or the video skills error. My Dot is in English (IN), and I can see the program in the Alexa app on my phone. I am using the default lambda instance. I am in India. if that affects anything.

**Comment by ndg63276** [comment]
If you go to https://developer.amazon.com/alexa/console/ask#/skills, does your YouTube skill say it's language is "English (IN)"?

**Comment by sherlockthegreat** [comment]
yes

**Comment by ndg63276** [comment]
Try saying "Alexa, launch YouTube", instead of "Alexa, open YouTube", that seems to work better for my Spot.

**Comment by sherlockthegreat** [comment]
Okay..let me check again

**Comment by sherlockthegreat** [comment]
Worked...great...Thanks a lot
