### ISSUE TITLE
a way to play only one video then stop

### ISSUE THREAD

**Issue by Dennispandea** [ndg63276/alexa-youtube#37]
at night I enjoy listening to podcasts as I fall asleep but the issue I've found is that through the night, Alexa is still playing videos.

**Comment by JosephChristianAnderson** [comment]
I also share this pain, if anyone has any possible solutions, I'd appreciate it.

**Comment by ndg63276** [comment]
Yeah, seems like a good idea.

I've added this (in English), you'll need to:

1. Go to https://developer.amazon.com/alexa/console/ask, and login
2. Click on your YouTube skill
3. Scroll down and find on the left the JSON Editor
4. Delete everything in the box, then copy the contents of https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_en.json into the box
5. Click Save Model at the top, then Build Model

If you are using your own lambda instance, you'll need to re-upload the lambda_function.zip file.

I've not tested it thoroughly, so let me know if it works.

**Comment by ndg63276** [comment]
I should add, you need to say something like:

Alexa, ask YouTube to play the video The Beatles Hey Jude
Alexa, ask YouTube to play one video The Beatles Hey Jude

Or replace video with song or track.

**Comment by Dennispandea** [comment]
this works for me once in a while but I think being able to say "Alexa, ask YouTube to turn autoplay on/off" would be way more intuitive

**Comment by ndg63276** [comment]
Ok, I've added the autoplay on/off functionality. Same instructions as before, let me know how you get on.
