### ISSUE TITLE
alexa-skills-color-expert-python not available in AWS Console for Mumbai

### ISSUE THREAD

**Issue by rituraj841** [ndg63276/alexa-youtube#39]
alexa-skills-color-expert-python is not avaibale under lambda blueprints for mumbai...Help me out...

**Comment by ndg63276** [comment]
Hi there. Alexa skills are not supported in Mumbai lambda skills. Change your lambda region to one of:

- US East (N. Virginia)
- EU (Ireland)
- US West (Oregon)
- Asia Pacific (Tokyo)

Then you should see the alexa-skills-color-expert-python blueprint.

Don't worry, it won't affect how your skill works, it's just the server it runs on.

**Comment by rituraj841** [comment]
okay!Thanks

**Comment by rituraj841** [comment]
![image](https://user-images.githubusercontent.com/18161437/52530484-533f9e80-2d2c-11e9-8126-41e8c1601862.png)

When selecting langulage ENG(IN) it says "Unsupported locale.
en-IN is currently not supported."

**Comment by ndg63276** [comment]
At what stage does it say this?
