### ISSUE TITLE
Help me with guide on how to get most of it

### ISSUE THREAD

**Issue by hasnogaems** [ndg63276/alexa-youtube#40]
So far it really improve my alexa user expirience but I want more.  Is there any more detailed guide somewhere?

I guess it just play first result under the search request. And if I say "next" it goes to the next result? Is there an ability to remember where I stop listening for multiple videos?

**Comment by ndg63276** [comment]
The only guide is in the README, ie https://github.com/ndg63276/alexa-youtube/blob/master/README.md#skill-commands

You're right that it plays the first search result, and "next" goes to the next search result. Or you can play playlists, or channels.

There is no way to remember where you stop listening on multiple videos. Alexa handles the resume position, and she only stores one position. If you even play something on Spotify, she will forget where you are on YouTube.
