### ISSUE TITLE
Any way to make it play from youtube by default?

### ISSUE THREAD

**Issue by hasnogaems** [ndg63276/alexa-youtube#41]
Currently I need to ask alexa to open yt before every request.

**Comment by ndg63276** [comment]
"Alexa, ask YouTube to play Gangnam Style" usually works for me.

**Comment by kunicmarko20** [comment]
Didn't want to open a new issue, I took a quick glance (never created a skill) for this to be possible this yo would need to be a music skill instead of a custom one? And that would require a lot of code changes?

**Comment by ndg63276** [comment]
Probably, I've never made a music skill. In fact, when I last looked, Music Skill wasn't available to me, but it is now, so maybe I should look into it again. No promises though!

**Comment by ndg63276** [comment]
After a quick look, there are 2 problems:

1) Music is only supported for the US, so I wouldn't be able to test it myself.
2) You have to create a catalog of all the music you have available. There's no way to do that for YouTube. Also you are limited to 500000 entities, and YouTube has way more than that.

So I would say that using the Music skill is beyond the scope of this project.
