### ISSUE TITLE
Is there any way to see history?

### ISSUE THREAD

**Issue by hasnogaems** [ndg63276/alexa-youtube#45]
Sometime Alexa start playing something random but its good and I have no way to find what it is especially if it played by order alexa next. How exactly next work? Exactly like pressing next on youtube or maybe it press next in search list or next mean first video from recommended?

**Comment by hasnogaems** [comment]
Is there any way maybe to give a command to save url or name of currently playing video somewhere?

**Comment by hasnogaems** [comment]
With a timestamp maybe too it would be briliant for bookmarking podcasts for example.

**Comment by hasnogaems** [comment]
I mean It should be possible because it already give you needed info with "Alexa ask youtube what is currently playing". Just other action must be done with this info.

**Comment by ndg63276** [comment]
Seems like a custom list might work for this. I'll have a look into it.

**Comment by ndg63276** [comment]
OK, I've released a new version. What you need to do:

1. Go to https://developer.amazon.com/alexa/console/ask, then click on your YouTube skill
2. Scroll to the bottom, click Permissions. Turn on "Lists Read" and "Lists Write".
3. Click "Custom" on the left, then "Invocation" on the left, then click "Save Model", and then "Build Model"
4. If you use your own lambda instance, you need to re-upload this zip file to it: https://github.com/ndg63276/alexa-youtube/raw/master/lambda_function.zip
5. Go to the Alexa app on your phone. In the menu, go to "Skills & Games", then "Your Skills", then scroll to the right and click on "Dev". Then click on your YouTube skill.
6. You should see a button marked "Settings", click that. Then press on "Manage Settings", and tick the boxes marked "Lists Read Access" and "Lists Write Access", and press "Save Settings".

Next time you say "Alexa, launch YouTube", it will create a list in the Alexa app, you can see it under the Lists option in the main menu. Then it will add videos that are played to that list.

2 things to note: I only get your country, so I guess the time zone. Apologies if it is wrong. Also, the list will become a maximum size of 90 videos, after that it will delete the oldest ones.

Let me know how you get on.

**Comment by hasnogaems** [comment]
Im not yet tested it but thank you so much!

**Comment by hasnogaems** [comment]
> OK, I've released a new version. What you need to do:
So far not working. I need to reinstall with new code probably on top of this instructions?
