### ISSUE TITLE
Any way to make it repeat song?

### ISSUE THREAD

**Issue by hasnogaems** [ndg63276/alexa-youtube#46]
When I start using it I remember it repeat everything by default and skip to next only if you ask next. Now it skip to next by default. How to force repeat?

**Comment by FireFace30** [comment]
I would also like to know how to get it to loop audio.

**Comment by Fantasymerlin** [comment]
I think it is only to say "Alexa, ask youtube, back". In German I say "Alexa, frage youtube, zurück" when the music plays. Then I can get to previous titel. But this works only with this session which are playing. The First titel is everytime this titel which it plays at first in this session. If are there titel before I can only hear again when I playing the playlist from the beginning (It is possible after the cache are deleted again, I think)!

**Comment by rybot666** [comment]
You can say "Alexa, restart" and it'll start the video again
