### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by ndg63276** [ndg63276/alexa-youtube#47]
@katshun0307 has offered to help with a Japanese translation.

Here are the first set of translations I need. These are things you would say to Alexa. Don't change anything in {curly brackets}, that is where you would say a video title or similar. 

                        "play music by {query}",
                        "play songs by {query}",
                        "play videos by {query}",
                        "search for {query}",
                        "Play {query}"
                        "play the song {query}",
                        "play the video {query}",
                        "play the track {query}",
                        "play one song {query}",
                        "play one video {query}",
                        "play one track {query}"
                        "shuffle {query}",
                        "shuffle songs by {query}",
                        "shuffle music by {query}",
                        "shuffle videos by {query}"
                        "Start playlist {query}",
                        "Listen to playlist {query}",
                        "Play playlist {query}"
                        "Shuffle playlist {query}"
                        "Start my playlist {query}",
                        "Listen to my playlist {query}",
                        "Play my playlist {query}"
                        "Next playlist"
                        "Shuffle my playlist {query}"
                        "Listen to channel {query}",
                        "Start channel {query} ",
                        "Play channel {query}"
                        "Shuffle channel {query}"
                        "Who is this",
                        "What video is playing",
                        "What song is playing",
                        "What is this",
                        "What is playing"
                        "Play more like this",
                        "Play videos like this",
                        "Play similar videos"
                        "Turn on autoplay",
                        "Turn autoplay on",
                        "Switch autoplay on",
                        "Switch on autoplay"
                        "Turn off autoplay",
                        "Turn autoplay off",
                        "Switch autoplay off",
                        "Switch off autoplay",
                        "Play this one video"
                        "How far into this video are we",
                        "What is the current timestamp",
                        "What is the time",
                        "What is the timestamp"

There will be more, but that is enough to get started.

**Comment by katshun0307** [comment]
I will send you a pull request containing translations as `InteractionModel_ja.json` copied from `InteractionModel_en.json` once it's finished.
Is this OK?

**Comment by ndg63276** [comment]
Yes that would be great.

There are also some phrases at the top of lambda_function.py that would need translating as well, for what Alexa replies to you.

**Comment by katshun0307** [comment]
#48

**Comment by ndg63276** [comment]
Great work.

Also see this commit https://github.com/ndg63276/alexa-youtube/commit/9e66894f9c1c7d92d78544857829b331ff9b283d #

**Comment by katshun0307** [comment]
I got it to work on the simulator, but I haven't succeeded on my echo device yet.
I'll try to get it working on my echo too, and let you know if I succeed.

**Comment by katshun0307** [comment]
I still can't get it to run on a real echo device...
Should it run without any configurations if the echo device and developer account is registered under the same e-mail address?

**Comment by ndg63276** [comment]
As long as testing is enabled, it should work. What does it say if you say "Alexa, launch YouTube" (in Japanese)? Can you teach me that phrase phonetically so I can test it here?

Make sure your Echo is set to Japanese, go to the Alexa app, Settings, Device Settings, go to your Echo, and scroll down to Language.

**Comment by katshun0307** [comment]
When I set the invocation word to `youtube` or `player` (something related to playing music), it says `audio device is not enabled`.
However, if I set the invocation name to a totally irrelevant word (for example `insect`), alexa tells me something like `I can't help you`, and *not* `audio device is not enabled`

`youtube を開く` is `open youtube` in Japanese, and you can check the pronunciation [here](https://translate.google.com/?hl=ja#view=home&op=translate&sl=ja&tl=en&text=youtube%20を開く).

**Comment by ndg63276** [comment]
It seems to work ok for me. I just set my device language to Japanese and it worked, see https://www.youtube.com/watch?v=dCyfFuwCwrQ&feature=youtu.be

What type of Echo device do you have? This is a 2nd generation Echo Dot.

**Comment by ndg63276** [comment]
Works for me, re-open if still having problems.
