### ISSUE TITLE
I have a playlist that I want to continue to listen to every day from where I stop last time

### ISSUE THREAD

**Issue by hasnogaems** [ndg63276/alexa-youtube#49]
How do I achieve it? Currently it is not possible, correct?
I wonder maybe there is a possibility to copy current url with timestamp in some "position1" list, and then like "youtube read from position1" and read url with timestamp and resume it this way. Could be more than 1 positions like that. Is it possible?

**Comment by ndg63276** [comment]
I don't understand. Play the playlist, then say "Alexa, pause". The next day, say "Alexa, play", and she will carry on from the same place in the same playlist.

**Comment by hasnogaems** [comment]
But is there any way to preserve this position while listening to some other stuff? 
For example:
 I listened podcast playlist for 5 hours straight and this is playlist with 10-15 min videos. Now Im in a mood to listen "Englishman in New York" 1 time. Now I have an issue if I want to comeback to listening this playlist where I left. I cannot find a way to do it.

**Comment by ndg63276** [comment]
Sorry, that's not possible with the way the skill currently runs. I just use Alexa's built in 'token' system to manage the playlist, and the token transfers to the most recently used audio skill.
