### ISSUE TITLE
other languages support

### ISSUE THREAD

**Issue by dioskey** [ndg63276/alexa-youtube#5]
Hi, is it possible to support other languages? Thanks!

**Comment by nakuable** [comment]
Dear Friend,

I'm trying to translate to Spanish if it is good for you because I'm Spanish.

But I don't know how I have to upload the skill.

When I have some reply from developer, I will put in touch with you and I will help you.

Thank you very much.

Best regards.

**Comment by ndg63276** [comment]
See #6.
