### ISSUE TITLE
works on mobile,PC and reverb but not on echo dot.

### ISSUE THREAD

**Issue by thrylosthyra7** [ndg63276/alexa-youtube#50]
hello and sorry for the dummy question!I tried everything you are describing.It works perfectly when I try from my PC,or from my mobile,or through reverb.ai but it won't work through Amazon echo dot gen2.any ideas??thanks in advance!!

**Comment by ndg63276** [comment]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?

**Comment by thrylosthyra7** [comment]
hello and thanks for your help!
1) I'm trying "Alexa open YouTube"
or launch or even "Alexa ask YouTube to play me and Bobby mac gee by Janis Joplin"
every time the answer is the same.not enabled video skills.
3)I'm using your eu one.
5)I'm using English us.

thing is that I have this app that connects my mobile to Alexa (reverb) and it works absolutely perfect..
that's what I don't get..

**Comment by ndg63276** [comment]
If you go to https://developer.amazon.com/alexa/console/ask, then click on your YouTube skill, then click Test at the top, it should say "Skill testing is enabled in Development". Type "Open YouTube" in the box on the top left, does it work there?

**Comment by qmiloo** [comment]
Hi All,

Sorry for adding something from me but i have the same problems. Instaed of "youtube" i have "test"
I tried on Echo 2 and Echo Dot 2 without positive results.
When i'm testing as, you describe above, its working without no issue, even when i'm trying to say not only typing in the box :(
![test](https://user-images.githubusercontent.com/48759219/54685793-fe0b5f80-4b17-11e9-813e-ab0caf85d355.JPG)

Thank You and KR's,
Kamil

**Comment by ndg63276** [comment]
Unfortunately that suggests the skill is working fine, but you are not managing to invoke it correctly on your real Echo's.

You are both using English (US) as your skill language. I assume that means you are in America, and your Echo's are American? If not, you need to set the language to whatever country you are in.

The best phrase to use seems to be "Alexa, launch YouTube". Try just saying that, see if you can get her to say "Welcome to YouTube, Say, for example, play videos by The Beatles". Once you get that far, the rest should work fine.

**Comment by qmiloo** [comment]
I'm using Alexa in Poland :)...this language is not supported by Alexa. 
I'm using English(US) with Alexa but i put your Lambda for EUR. Maybe this is the problem? But it shouldn't because in UK for sure is English and Lambda will be EUR.
I will change Lambda to US and will see what will happen, will let you know

Thank you!

**Comment by ndg63276** [comment]
The Lambda instance (EU or US) doesn't matter, it's just slightly faster to use one closer to you.

But the language setting of your skill must match the language of your Echo. If you go to the Alexa app, open the main menu and press Settings, then Device Settings. Then press on the Echo you are trying to use. Scroll down and it will say Language. Whatever that says, must match what you see in the Test tab, which in your case qmiloo is English (US).

**Comment by ndg63276** [comment]
Cool. If you find other skills stop working, you may have to change the language back. In which case, you can re-build this skill in English (UK), and hopefully it will work still.

I have added an extra line in the instructions to help others.

**Comment by qmiloo** [comment]
i did :), i created new one because i couldn't find option to change language on existing one.
Have to "play" with this skill a little bit to check how its working :).
BTW what to tell to Alexa when she's playing music from youtube to play music on all of my devices?
I was trying "Alexa, ask youtube to play "[song_name]"  in/on/at homegroup - its not working and changing to another song from spotify :)
With Spotify is working correctly on all of the devices

**Comment by ndg63276** [comment]
Unfortunately it is not possible to play on multiple devices. See #28 .

**Comment by qmiloo** [comment]
Ahh, clear. 
Sorry and thank you!

With this additional line in the instruction shouldn't be aby problems for anybody to ceate :)
