### ISSUE TITLE
Is there a way to make it "next" multiple times at once?

### ISSUE THREAD

**Issue by hasnogaems** [ndg63276/alexa-youtube#51]
Some videos is hard to dictate, but I know if I dictate "alexa ask youtube to play %certain keyword%" and then "alexa next" 5 times it will play what I looking for.
The issue is, it take alot of time.
Is there a way to make alexa go to the fifth position on the search directly?

**Comment by hasnogaems** [comment]
Also maybe there is a way to implement this functionality through "alexa ask yt forward %time%". As I understand currently if you as to skip too much time, it just lag and stop, but if it can skip forward to next videos by correct amount of time it would be great.
For example I search:
"relaxing music"
and all videos in search list for example 10 minutes and I am interested in 10th video, so instead of "alexa next 9 times" I just "alexa ask yt forward 1hour30min" and it start playing 10th video.

**Comment by ndg63276** [comment]
Why not make your own playlist?
