### ISSUE TITLE
Only plays on my iPhone Alexa App

### ISSUE THREAD

**Issue by hemanshumehta** [ndg63276/alexa-youtube#53]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?

**Comment by hemanshumehta** [comment]
Thanks for this skill!! After a couple of tries, I used the Host function in Alexa Developer and also created my own Lambda on AWS. I'm not a developer but the instructions were great.

I was super excited when the skill worked on my iPhone so I ran to my living room where I have the Echo Dot setup and all my Smart Home integrated. Unfortunately, the Echo Dot keeps saying that it cannot find the video skill and that I need to go the Alexa app to Enable Video Skill in Devices. 

Please help - I'm doing this for my two year old who is obsessed with Alexa and wants to play Gummy Bears and Taki Taki all the time :) I have a YouTube Premium Subscription and don't want to subscribe to Amazon Music Unlimited.

**Comment by hemanshumehta** [comment]
What are you saying to Alexa?

Alexa, launch YouTube launches and plays successfully on my phone but not the Echo Dot.

What video are you trying to play? Please provide the youtube URL.

Anything.. all 

Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)

Using my own as per the step-by-step directions of Lambda on AWS.

If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.

Yes, latest version.

What language are you using?

English Canada

**Comment by ndg63276** [comment]
If you go to https://developer.amazon.com/alexa/console/ask#/skills, and click on your YouTube skill, and then click Test at the top, does it say "Skill testing is enabled in: Development"? If it says "Test is disabled for this skill", then select "Development" from the dropdown.

Underneath that, does it say "English (CA)" under "Alexa Simulator"? If it says "English (US)" or "English (GB)" or any other, it won't work, Amazon thinks we speak different languages.

In the Alexa app, if you go to Settings, then Device Settings, then click your Echo Dot, scroll down to Language, does it also say "English (CA)". This must match the language from the question above.

**Comment by ndg63276** [comment]
Closing, re-open if still a problem.
