### ISSUE TITLE
lamdba error 

### ISSUE THREAD

**Issue by tony4212** [ndg63276/alexa-youtube#57]
when setting lambda to python 2.7 I get the following error after testing

START RequestId: 28f147a6-aec8-4ba4-b0d5-03ac4c1d15cc Version: $LATEST
'request': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 208, in lambda_handler
    if event['request']['locale'][0:2] == 'fr':
KeyError: 'request'

**Comment by ndg63276** [comment]
What test are you doing?

**Comment by tony4212** [comment]
the test that runs for lambda that basically runs through the code.

**Comment by ndg63276** [comment]
Sounds like a crap test. Ignore it.

**Comment by tony4212** [comment]
I still get the error from alexa that there is a problem with the requested skills response

**Comment by ndg63276** [comment]
In Lambda, click Configure Test Events in the top right, and then paste in this code:

```
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session",
    "application": {
      "applicationId": "amzn1.ask.skill"
    },
    "user": {
      "userId": "amzn1.ask.account"
    }
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill"
      },
      "user": {
        "userId": "amzn1.ask.account"
      },
      "device": {
        "deviceId": "amzn1.ask.device",
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "apiEndpoint": "https://api.eu.amazonalexa.com",
      "apiAccessToken": ""
    }
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "amzn1.echo-api.request",
    "timestamp": "2018-12-20T13:43:01Z",
    "locale": "en-GB",
    "shouldLinkResultBeReturned": false
  }
}
```
Then click Save, then Test, and let me know what it says.

**Comment by tony4212** [comment]
Yep figured it out. I set up lambda wrong originally in the be beginning steps.
