### ISSUE TITLE
Price on AWS

### ISSUE THREAD

**Issue by Tukks** [ndg63276/alexa-youtube#58]
Hello,
I want to self host this skill on my lambda instance.
I wanted to know if the skill will cost me something if I play videos? 
the stream came from a youtube link, so I think not, but i'm not sure.
Can you add it to readme?

thank's for the skill and good work.

**Comment by ndg63276** [comment]
Each time you talk to Alexa, it will use about 5 seconds of lambda processing. The first 3.2 million seconds per month are free, so you won't get charged!

I'll put it in the FAQ if I remember when I get home.

**Comment by Prog423** [comment]
Hello ndg63276,
if I do not register in the amazon aws portal.
I do not want self host this skill can I use this arn.aws address for free in your faq ?

Is this your AWS address ? Or Public AWS ? Or how do i understand that ?
Is this service free ?

**"Your Location | What to put in "Default Region"
-- | --
EU/Ireland | arn:aws:lambda:eu-west-1:175548706300:function:YouTube
Asia/Tokyo | arn:aws:lambda:ap-northeast-1:175548706300:function:YouTube
US East | arn:aws:lambda:us-east-1:175548706300:function:YouTube
US West | arn:aws:lambda:us-west-2:175548706300:function:YouTube"**

**Comment by ndg63276** [comment]
Yes, you can use my AWS. It is free. Use whichever is closest to you.

**Comment by Prog423** [comment]
Ok thank you that is very nice!
Why it is not possible to create for Spotify Free Account like you Youtube Skill for an new Skill?
I think the code needs to be changed slightly for spotifiy.

And the amazon developer account is too for free ?

Greetings
Prog423

**Comment by Tukks** [comment]
Thank for the response, ok it's free. 
I've seen an other implementation who was not free with AWS instance.
I can close the issue.
