### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by nakuable** [ndg63276/alexa-youtube#6]
Dear Friend,

I'm from Spain, and I speak spanish. 
I think about your alexa-youtube is really nice and I used in English but now I'm interested on translate it to Spanish. But... I need you help. Because I'm not a developer.

I have seen the greeting in your lambda_function.py from line 251.

But I don't understant how I can upload your skill translated.

Please, can you help me?

Thank you very much for your help.

Best regards.

**Comment by ndg63276** [comment]
Thanks @wankes2000, that's really all that is needed. Obviously Alexa will say things like "Playing The Beatles" in English still, I'm sure everyone can cope with that.
