### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by Joshiloveyou** [ndg63276/alexa-youtube#61]
this was working fine a couple hours ago and now she is saying 
There was a problem with the requested skill's response
or she will say, the playlist metal gear solid 4 guns of the patriots ost hasn't worked should i try the next one, if i say she will say There was a problem with the requested skill's response
or she says nothing

1. ask YouTube to play attic monkeys do i wanna know official video.
    ask YouTube to play metal gear solid guns of the patriots complete soundtrack
    ask YouTube to play playlist metal gear solid 4 guns of the patriots
2. https://www.youtube.com/watch?v=bpOSxM0rNPM
    https://www.youtube.com/watch?v=yzgpY9Fx2xE
    https://www.youtube.com/watch?v=-VYoBMGuqCk&list=PL34D3BCBECE15374D

3. i am running off yours with 
arn:aws:lambda:eu-west-1:175548706300:function:YouTube
4. not using my own
5. English
It was all working fine a couple hours ago, plz help

**Comment by Joshiloveyou** [comment]
update i did a test in the Alexa developer console and i get this 
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.1a5fe6b7-ef82-4e35-91a6-4e3cf6438ddc",
		"application": {
			"applicationId": "amzn1.ask.skill.7d830339-5dd2-46a6-9335-9edb004c48d2"
		},
		"user": {
			"userId": "amzn1.ask.account.AFD5QCHAING4EGQ4KKXA6QPOPAOGBRNN3TXZU7DZZFXIQKSQYNWKNFVFVG7NTJWJFRCYV3J6QJZDTXELFOMMBEZ5FGZOGYDDWCK5VC3BGBZII3TTVUTLDFLAHQW6F7RANFU3SBJCVBJ3PAZQ4FUPG3A2744N75CSMKFFEMUE6RC7SBZ5JXQZ6HGMHCQ2LRJG7JRVLUN6AC7FKZY",
			"permissions": {
				"consentToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjdkODMwMzM5LTVkZDItNDZhNi05MzM1LTllZGIwMDRjNDhkMiIsImV4cCI6MTU1NjA2NzYyOCwiaWF0IjoxNTU2MDY3MzI4LCJuYmYiOjE1NTYwNjczMjgsInByaXZhdGVDbGFpbXMiOnsiaXNEZXByZWNhdGVkIjoidHJ1ZSIsImNvbnNlbnRUb2tlbiI6IkF0emF8SXdFQklJdlMtNFJyb05neVhYSkpmdHNDSEx1enNIRURabDkyOV80Slp1VU5La0lIWVFWRmQ1VzRLZWdPYUNNNjFOU0ExNExTY054ZklWYS1MTGNzRnVFTGt6THNOOGp2bVBjb295RDEzUXE2NFd4Z1Y5OVBWeGYyR013WGpVSWduMzJxdDVHUE5wZEdDYWxvRVljcGJaQ0plOHB3TFVhMVRjU1lpU2p1d2JDdFdfNVJ1YlduYWxCc0N1Q19YdnIyWXVWOU1adHRPMTZaMTRVQi1udWM4dFphNWRPTG1FaGptRlpETmhpT1Jocm5xWmIzRU1BNXRaaF9oeVVRNXV5Rjk1MVFSenBhWGotTjhzWHJmWUljQnFXRW9iUHdCclUwXzBYNGZxLVpCZWRaelN4Vk9jdThOZmROeHhfbV9CSWJKNmNYejhxek5YX2pyQjFtc2tMOUpteXBoZy1BaE5PTlhkcENkRVZ4c2kyaXAycFZuWWJPVE4wV3JQdldwVk9pMDI0Vm9MSm1VZk5kQWJnX3ZpbEdzZXFVRzZ3Nlo3MWR5Q2RrWGw2RVhkRUt4blR4N2E5OVd2X0dIX0oxd25sb0xNa0hZa1I1ZXMycll4VTlRalhQTDVuUHNuZVBqZnFtaE56dkNUTTE0cVd4OEd5UE81Wl8wSjk5VXpIUlJmLUhyclhPeWNKMUVuTVo5azAtd2lDRmdmZ0pCdkVhalQ4RklMekNaalZkX0swejRndzFRUSIsImRldmljZUlkIjoiYW16bjEuYXNrLmRldmljZS5BR01WTkNMVFRRV0JQTkoyWFI1TkZPM0dHWDZOVlFFWFo3NEpKRVdBR1pCQlhGUUZJSFM0V0tJTUVONVk3QVNYTFpDVVA3TTJSSDM0NzVWSTdISlM1RVBLS01CS0ZGQVlMVFBBTkVaSlQyWlBPNjUyUU1MV1VNSU5MNUQ1N0FHVFJMTkE0QkRNRDU0M0kyRlJSVFhXQVo0QVNIU01HNVdGRlRPQlZKRTdBVVNKQ0xCU1BKR1JDIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUZENVFDSEFJTkc0RUdRNEtLWEE2UVBPUEFPR0JSTk4zVFhaVTdEWlpGWElRS1NRWU5XS05GVkZWRzdOVEpXSkZSQ1lWM0o2UUpaRFRYRUxGT01NQkVaNUZHWk9HWUREV0NLNVZDM0JHQlpJSTNUVFZVVExERkxBSFFXNkY3UkFORlUzU0JKQ1ZCSjNQQVpRNEZVUEczQTI3NDRONzVDU01LRkZFTVVFNlJDN1NCWjVKWFFaNkhHTUhDUTJMUkpHN0pSVkxVTjZBQzdGS1pZIn19.aJbeDeQp-izNoe8knp6faLITcs5g3B2NiUb7Xun2hdhwP5qpSb3VzfNjk3lqAP9PBpBBW2vlYU1bBQvNhQG1rFCLo0xmdGFcq3YH9mLoduHLfX6Zf1i4yuYZnifsRpn_pgli4bseiTsHte57ugvDVvrRONpyEDcz3ZtbJkTQsR8QdYC_-3ziTJhWX3mgSZ_8fskbf8MBu3zZZSq-PGs_MjkhnLwBeLLifLCAkY7aMJLXbPw6ir98q3Lw70_bRdwzVtHEZfCAoUOJDOQOd3Od6YYVbCMkwdQhzuQLSxeJsmAHb3NSaxNRpZLoxLGVuB434GgYhrkuPj7LLoEARKykeA"
			}
		}
	},
	"context": {
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.7d830339-5dd2-46a6-9335-9edb004c48d2"
			},
			"user": {
				"userId": "amzn1.ask.account.AFD5QCHAING4EGQ4KKXA6QPOPAOGBRNN3TXZU7DZZFXIQKSQYNWKNFVFVG7NTJWJFRCYV3J6QJZDTXELFOMMBEZ5FGZOGYDDWCK5VC3BGBZII3TTVUTLDFLAHQW6F7RANFU3SBJCVBJ3PAZQ4FUPG3A2744N75CSMKFFEMUE6RC7SBZ5JXQZ6HGMHCQ2LRJG7JRVLUN6AC7FKZY",
				"permissions": {
					"consentToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjdkODMwMzM5LTVkZDItNDZhNi05MzM1LTllZGIwMDRjNDhkMiIsImV4cCI6MTU1NjA2NzYyOCwiaWF0IjoxNTU2MDY3MzI4LCJuYmYiOjE1NTYwNjczMjgsInByaXZhdGVDbGFpbXMiOnsiaXNEZXByZWNhdGVkIjoidHJ1ZSIsImNvbnNlbnRUb2tlbiI6IkF0emF8SXdFQklJdlMtNFJyb05neVhYSkpmdHNDSEx1enNIRURabDkyOV80Slp1VU5La0lIWVFWRmQ1VzRLZWdPYUNNNjFOU0ExNExTY054ZklWYS1MTGNzRnVFTGt6THNOOGp2bVBjb295RDEzUXE2NFd4Z1Y5OVBWeGYyR013WGpVSWduMzJxdDVHUE5wZEdDYWxvRVljcGJaQ0plOHB3TFVhMVRjU1lpU2p1d2JDdFdfNVJ1YlduYWxCc0N1Q19YdnIyWXVWOU1adHRPMTZaMTRVQi1udWM4dFphNWRPTG1FaGptRlpETmhpT1Jocm5xWmIzRU1BNXRaaF9oeVVRNXV5Rjk1MVFSenBhWGotTjhzWHJmWUljQnFXRW9iUHdCclUwXzBYNGZxLVpCZWRaelN4Vk9jdThOZmROeHhfbV9CSWJKNmNYejhxek5YX2pyQjFtc2tMOUpteXBoZy1BaE5PTlhkcENkRVZ4c2kyaXAycFZuWWJPVE4wV3JQdldwVk9pMDI0Vm9MSm1VZk5kQWJnX3ZpbEdzZXFVRzZ3Nlo3MWR5Q2RrWGw2RVhkRUt4blR4N2E5OVd2X0dIX0oxd25sb0xNa0hZa1I1ZXMycll4VTlRalhQTDVuUHNuZVBqZnFtaE56dkNUTTE0cVd4OEd5UE81Wl8wSjk5VXpIUlJmLUhyclhPeWNKMUVuTVo5azAtd2lDRmdmZ0pCdkVhalQ4RklMekNaalZkX0swejRndzFRUSIsImRldmljZUlkIjoiYW16bjEuYXNrLmRldmljZS5BR01WTkNMVFRRV0JQTkoyWFI1TkZPM0dHWDZOVlFFWFo3NEpKRVdBR1pCQlhGUUZJSFM0V0tJTUVONVk3QVNYTFpDVVA3TTJSSDM0NzVWSTdISlM1RVBLS01CS0ZGQVlMVFBBTkVaSlQyWlBPNjUyUU1MV1VNSU5MNUQ1N0FHVFJMTkE0QkRNRDU0M0kyRlJSVFhXQVo0QVNIU01HNVdGRlRPQlZKRTdBVVNKQ0xCU1BKR1JDIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUZENVFDSEFJTkc0RUdRNEtLWEE2UVBPUEFPR0JSTk4zVFhaVTdEWlpGWElRS1NRWU5XS05GVkZWRzdOVEpXSkZSQ1lWM0o2UUpaRFRYRUxGT01NQkVaNUZHWk9HWUREV0NLNVZDM0JHQlpJSTNUVFZVVExERkxBSFFXNkY3UkFORlUzU0JKQ1ZCSjNQQVpRNEZVUEczQTI3NDRONzVDU01LRkZFTVVFNlJDN1NCWjVKWFFaNkhHTUhDUTJMUkpHN0pSVkxVTjZBQzdGS1pZIn19.aJbeDeQp-izNoe8knp6faLITcs5g3B2NiUb7Xun2hdhwP5qpSb3VzfNjk3lqAP9PBpBBW2vlYU1bBQvNhQG1rFCLo0xmdGFcq3YH9mLoduHLfX6Zf1i4yuYZnifsRpn_pgli4bseiTsHte57ugvDVvrRONpyEDcz3ZtbJkTQsR8QdYC_-3ziTJhWX3mgSZ_8fskbf8MBu3zZZSq-PGs_MjkhnLwBeLLifLCAkY7aMJLXbPw6ir98q3Lw70_bRdwzVtHEZfCAoUOJDOQOd3Od6YYVbCMkwdQhzuQLSxeJsmAHb3NSaxNRpZLoxLGVuB434GgYhrkuPj7LLoEARKykeA"
				}
			},
			"device": {
				"deviceId": "amzn1.ask.device.AGMVNCLTTQWBPNJ2XR5NFO3GGX6NVQEXZ74JJEWAGZBBXFQFIHS4WKIMEN5Y7ASXLZCUP7M2RH3475VI7HJS5EPKKMBKFFAYLTPANEZJT2ZPO652QMLWUMINL5D57AGTRLNA4BDMD543I2FRRTXWAZ4ASHSMG5WFFTOBVJE7AUSJCLBSPJGRC",
				"supportedInterfaces": {
					"AudioPlayer": {}
				}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjdkODMwMzM5LTVkZDItNDZhNi05MzM1LTllZGIwMDRjNDhkMiIsImV4cCI6MTU1NjA2NzYzOSwiaWF0IjoxNTU2MDY3MzM5LCJuYmYiOjE1NTYwNjczMzksInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjoiQXR6YXxJd0VCSUl2Uy00UnJvTmd5WFhKSmZ0c0NITHV6c0hFRFpsOTI5XzRKWnVVTktrSUhZUVZGZDVXNEtlZ09hQ002MU5TQTE0TFNjTnhmSVZhLUxMY3NGdUVMa3pMc044anZtUGNvb3lEMTNRcTY0V3hnVjk5UFZ4ZjJHTXdYalVJZ24zMnF0NUdQTnBkR0NhbG9FWWNwYlpDSmU4cHdMVWExVGNTWWlTanV3YkN0V181UnViV25hbEJzQ3VDX1h2cjJZdVY5TVp0dE8xNloxNFVCLW51Yzh0WmE1ZE9MbUVoam1GWkROaGlPUmhybnFaYjNFTUE1dFpoX2h5VVE1dXlGOTUxUVJ6cGFYai1OOHNYcmZZSWNCcVdFb2JQd0JyVTBfMFg0ZnEtWkJlZFp6U3hWT2N1OE5mZE54eF9tX0JJYko2Y1h6OHF6TlhfanJCMW1za0w5Sm15cGhnLUFoTk9OWGRwQ2RFVnhzaTJpcDJwVm5ZYk9UTjBXclB2V3BWT2kwMjRWb0xKbVVmTmRBYmdfdmlsR3NlcVVHNnc2WjcxZHlDZGtYbDZFWGRFS3huVHg3YTk5V3ZfR0hfSjF3bmxvTE1rSFlrUjVlczJyWXhVOVFqWFBMNW5Qc25lUGpmcW1oTnp2Q1RNMTRxV3g4R3lQTzVaXzBKOTlVekhSUmYtSHJyWE95Y0oxRW5NWjlrMC13aUNGZ2ZnSkJ2RWFqVDhGSUx6Q1pqVmRfSzB6NGd3MVFRIiwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFHTVZOQ0xUVFFXQlBOSjJYUjVORk8zR0dYNk5WUUVYWjc0SkpFV0FHWkJCWEZRRklIUzRXS0lNRU41WTdBU1hMWkNVUDdNMlJIMzQ3NVZJN0hKUzVFUEtLTUJLRkZBWUxUUEFORVpKVDJaUE82NTJRTUxXVU1JTkw1RDU3QUdUUkxOQTRCRE1ENTQzSTJGUlJUWFdBWjRBU0hTTUc1V0ZGVE9CVkpFN0FVU0pDTEJTUEpHUkMiLCJ1c2VySWQiOiJhbXpuMS5hc2suYWNjb3VudC5BRkQ1UUNIQUlORzRFR1E0S0tYQTZRUE9QQU9HQlJOTjNUWFpVN0RaWkZYSVFLU1FZTldLTkZWRlZHN05USldKRlJDWVYzSjZRSlpEVFhFTEZPTU1CRVo1RkdaT0dZRERXQ0s1VkMzQkdCWklJM1RUVlVUTERGTEFIUVc2RjdSQU5GVTNTQkpDVkJKM1BBWlE0RlVQRzNBMjc0NE43NUNTTUtGRkVNVUU2UkM3U0JaNUpYUVo2SEdNSENRMkxSSkc3SlJWTFVONkFDN0ZLWlkifX0.C2RYcynX1E-XcSvA9fKlxhjNyhtNMSosn7-uvqvLyAJtIuxPexyehMp073V-ztnEhxnWAEXHhfNKGCqow5eW8bqzlI8nooFTYc5mqmgwyqayY_0lfwDqHdpjOXH4eTLBUZ8YAkx-8gG1G2nsp_mQ3EJA-qVimn0qnxG_5qo8lav98Mf6VpYLSjolo-l-P0yAku6ICrbcUqa93w2sxtCLyG2_CBkekvjv-L8hWUB_3viaAd8YO1V4v2__p10LhnbANR6cVLC5ueFU9UfBVzW_34U_tDR-5KP2dITtSD3Gy4vhRx8Tc0vLaS0CrIJm-HUWD4XKyoww-9J6Li93aYw1Ew"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			]
		}
	},
	"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.0847317a-622d-42b3-9354-877cf198721f",
		"timestamp": "2019-04-24T00:55:39Z",
		"locale": "en-GB",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "An exception occurred while dispatching the request to the skill."
		}
	}
}

**Comment by rishilaughs** [comment]
i do also face the same problem

**Comment by Joshiloveyou** [comment]
> i do also face the same problem

I have tried deleting the skill and remaking it but that didn't work. It literally stopped working just like that

**Comment by Joshiloveyou** [comment]
Update.
I can ask YouTube to play any live videos but that's all she will play.
What is going on plz someone help

**Comment by ndg63276** [comment]
Hi, I'm on holiday at the moment but back on Friday. Had a quick look, it's not managing to get the stream URLs from YouTube, and then timing out.

Probably YouTube changed something, hopefully an update to Pytube will fix it.

**Comment by Joshiloveyou** [comment]
Everything seems to be working now.

**Comment by ndg63276** [comment]
Looks like it is this problem:

https://github.com/nficano/pytube/issues/381

So I've done the comment out that people suggest.

**Comment by Joshiloveyou** [comment]
I feel bad now I know you was on holiday.

**Comment by ndg63276** [comment]
Heh no worries, I have to sit in my room while my kid naps, so it gave me something to do!

**Comment by Joshiloveyou** [comment]
Well thanks for sorting it out so fast. Enjoy the rest of your holiday 😁

**Comment by Joshiloveyou** [comment]
> Heh no worries, I have to sit in my room while my kid naps, so it gave me something to do!

I know this has nothing to do with the thread but I was thinking you said in order to use your own YouTube playlist you have to have your own Lambda server, can you have more than one YouTube ID on the Lambda server? So I can use my own playlist and say bf could play his.

**Comment by ndg63276** [comment]
Not at the moment.

**Comment by coolduebtn** [comment]
@ndg63276 I have followed your instructions and setup a lamda function on aws. It worked perfectly for some time. Suddenly I have started to get the error message "There was a problem with the requested skill's response" Any idea what am i doing wrong. arn:aws:lambda:eu-west-1:013353909778:function:youtube This is my generated arn for you to test. thanks

**Comment by ndg63276** [comment]
Strange, it works for me.

What are you saying to Alexa?

**Comment by coolduebtn** [comment]
> Strange, it works for me.
> 
> What are you saying to Alexa?

Alexa ask youtube to play abc song.

**Comment by coolduebtn** [comment]
@ndg63276 I found the problem. in invocation menu I had given the name youtube, however the rule is that it should be minimum two words. so when i changed the name to you tube it started working. I guess you should update about this in your instructions. thanks for creating this skill, its a great help with our baby who loves it.
