### ISSUE TITLE
Skill is timing out for some queries (Unable to get URL error)

### ISSUE THREAD

**Issue by 9yzh** [ndg63276/alexa-youtube#62]
I've noticed that more and more videos, especially related to music, cannot be retrieved by anymore.  The logs show the skill attempting to get a video, and then getting an "Unable to get URL" error.  I assumed it was due to Youtube locking down the API for copyrighted music, but more and more videos seem to no longer work.  Eventually, the skill hits the timeout setting (30 secs) that I've set for the lambda instance.  Other videos work, like asking "play news videos," etc.  I was wondering if this was just a limitation with the Youtube API or something wrong with my setup.

1. What are you saying to Alexa?
e.g., "ask youtube [wait for prompt] play videos by the beatles"

2. What video are you trying to play? Please provide the youtube URL.
In the logs, the first video when making the above query is https://www.youtube.com/watch?v=kle2xHhRHg4

The other videos that are tried are:
https://www.youtube.com/watch?v=srwxJUXPHvE
https://www.youtube.com/watch?v=b-VAxGJdJeQ
https://www.youtube.com/watch?v=yYvkICbTZIQ
https://www.youtube.com/watch?v=1OJHVZ7qhwI
https://www.youtube.com/watch?v=Jzy4R8EbWJ4
https://www.youtube.com/watch?v=8Kx4xVKo9z8

3. Are you running your own lambda instance, or are you using mine?
My own instance.

4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
I've updated to the latest

5. What language are you using?
English

**Comment by ndg63276** [comment]
Hi there. There's been a few problems with Pytube recently, see https://github.com/nficano/pytube/issues/381. It should have now been fixed, and I updated the lambda_function.zip file last night. Can you try re-downloading https://github.com/ndg63276/alexa-youtube/blob/master/lambda_function.zip and re-uploading it to lambda?

Also, make sure you have allocated 512mb of memory for your lambda function, if you have less, it may run out of time.

I'm not by an Alexa device right now, but it works for me through lambda testing, for https://www.youtube.com/watch?v=kle2xHhRHg4

**Comment by 9yzh** [comment]
Nice.  I uploaded the new lamba file and it's working now!

**Comment by 9yzh** [comment]
Thanks again for the quick reply and for working on this great project!!
