### ISSUE TITLE
Command for own channel / playlist

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#64]
My ask is how I can tell Alexa in the yt skill that I want to hear my own playlist on my yt account in German language. 

I tried with play my playlist (Spiele meine Playlist / Start Playlist) etc. but every time Alexa play other and not my own playlist. 

On yt I create a own playlist and this I want to play with the skill.

I created a own lamdba instance on my aws account and set my own endpoint. The skill works fine with my own instance. I can see at aws that it works.

Only my own playlists Alexa cannot find and play for me. 

I have created a own google api key for yt. Have I set this anywhere on my yt account too. I don't find something there. 

On my lambda instance I set my api key to on the right position. This seems to working too because Alexa execute the skill with my arn. 

What and where I have to set in the code etc that it plays my own playlist from my own yt account? 

I am interested in what for playlist the skill play if I say start playlist. Where Alexa takes this data? 

Thank you for help

**Comment by ndg63276** [comment]
Hi there, can you send me the link to the YouTube playlist you want to play? Thanks.

**Comment by Fantasymerlin** [comment]
Hi there,

this is the link to my personal Playlist:
https://www.youtube.com/playlist?list=PLBuM22qqig8kzVHjV6t6Y35aOi5TITkLJ

Thank you very much for help

**Comment by ndg63276** [comment]
Unfortunately Youtube returns no playlists when I search using your channelId. Obviously you have a playlist, so I don't know why it doesn't find it.

If you go to https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.search.list?part=id%252Csnippet&channelId=UCdAJnXFpTz5QtVa1O9a4a2Q&type=playlist&_h=1&

and click Execute Without OAuth at the bottom, you will see you get totalResults: 0. I don't know why this is, but that's why it doesn't work.

**Comment by Fantasymerlin** [comment]
Ohh. OK.

I have check this too. You have right. I get this as answer from googleapis Explorer:

`
Request
GET https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&channelId=UCdAJnXFpTz5QtVa1O9a4a2Q&type=playlist&key={YOUR_API_KEY}
 
Response
200 OK
- Show headers -
{
 "kind": "youtube#searchListResponse",
 "etag": "\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/5FnikxKwZdsRDemtugKx3gJK4bo\"",
 "regionCode": "DE",
 "pageInfo": {
  "totalResults": 0,
  "resultsPerPage": 5
 },
 "items": [
 ]
}
`

Do you have check it at youtube directly, too. I checked my settings and it set to public. But Api Explorer don´t can find it.

Can you say me the right command for Alexa, that I can search for my own playlist (I know it don´t will works, but maybe I use the wrong command. This I don´t know really.

**Comment by ndg63276** [comment]
It hasn't been translated into German yet. Can you translate for me? Assuming your playlist is called Schlager, can you translate:

"Start my playlist Schlager",
"Listen to my playlist Schlager",
"Play my playlist Schlager"
"Shuffle my playlist Schlager"

**Comment by Fantasymerlin** [comment]
Ohh yes this isn´t a problem...

The name Schlager is a own word in german. Cannot translate. It is specific music for my country.
But in the USA "Schlager" is how Music from Tina Turner for example. Schlager is the specific Music Genre in my Country, also how for example Country Music in the USA. I think other I can't explain but I think you understand what I mean.

The Command in German also have to be:

"Start my playlist Schlager", = "Starte meine Playlist Schlager"
"Listen to my playlist Schlager", = Höre meine Playlist Schlager"
"Play my playlist Schlager" = "Spiele meine Playlist Schlager"
"Shuffle my playlist Schlager" = "Mische meine Playlist Schlager"

I will try it in some days again. Maybe there is a problem at youtube or it takes some days till the list will be find from yt.

**Comment by ndg63276** [comment]
Ok, you'll need to update your Interaction model:

1. Go to https://developer.amazon.com/alexa/console/ask, and click on your YouTube skill
2. Scroll down and find in the left hand column where it says "JSON Editor", click that.
3. Delete everything in the box on the right, replace it with the contents of https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_de.json
4. Click 'Save Model' at the top, then 'Build Model'. Wait for it to build (2 minutes).

Then try again with your German commands.

**Comment by Fantasymerlin** [comment]
Ok I have done this.

I have test with the 4 commands in german language. It works better now. I get response now with other playlists but I get a response and it play a title now.

I have seen that I have 467 / 468 rows now. ca. 30 rows more as before.

The issue that it don´t play my playlist I will wait some days. Maybe we have to wait some time till it will be listed (Somewhere I have read this in a community board). Maybe yt needs some time.

I will write in some days again.

Thank you very much for help. Now it works some better and I can use to hear music.
