### ISSUE TITLE
Say Timestamp from the current video does not working

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#65]
Hello, 

I use my own lambda. I have modified some in the skill. The skill working fine and Alexa hear commands now better. 

But one command don't want to working. I take saytimestampintent into the json and modified the commands for this for German language.

If I ask for the current video what is the current position (in German "aktuelle position" ) I get the response "error with the skill" in German language.

What could the reason for this error response. For example autoplayonintent or autoplayoffintent it works and say OK and do it fine.

Other commands work too.

Thanks for helping

**Comment by ndg63276** [comment]
Hi, I have a few questions:
1) What Alexa device do you have?
2) What happens if you ask when nothing is playing?
3) Are you able to test it through https://developer.amazon.com/alexa/console/ask#/skills ? Go to your YouTube skill, click on Test at the top, and where it says to "Type or click and hold the mic", type "ask youtube what is the current time" in German.
4) Can you provide the translations for saytimestampintent in the json file? Either in this ticket, or in a pull request.

**Comment by Fantasymerlin** [comment]
Hi there...

1. I have Echo dot 2 gen.

2. When I ask my device directly and nothing is playing in the moment I get the response that there is a failure with the Skill. If there is playing music from yt on my echo and I ask then the response is that there is a failure in the skill but the music plays further after the response. 

When I ask the Alexa app it say that there is a failure too and it shows me that the target of the lambda app returned a failure response.

And at the Alexa developer I get the response "nothing is playing"

4. The translations for the commands for say Timestamp intent are the following...

How far into this video are we
What is the current timestamp
What is the time
What is the timestamp

For German...
An welcher Position sind wir
Was ist die aktuelle Position
Aktuelle Zeit
Aktuelle Position
Zeitstempel

**Comment by ndg63276** [comment]
Ok, thanks for that. I have included your code in the json file.

If you go to https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions, click on your YouTube skill, and then in the top right, there is a dropdown for test events, it probably says "Select a test event." Click the dropdown, then click "Configure Test Events". Under "Event Name", put SayTimestampIntent, and then in the main box, put this code:

```
{
  "session": {},
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "device": {
          "supportedInterfaces": {}
      }
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "",
    "timestamp": "2019-05-25T21:58:59Z",
    "locale": "de-DE",
    "intent": {
      "name": "SayTimestampIntent",
      "confirmationStatus": "NONE"
    }
  }
}
```
then click Create. The dropdown should now say SayTimestampIntent, if you click Test next to it, you should get a message saying it succeeded or failed. Click "details", and copy any error messages you get, and post them here.

**Comment by Fantasymerlin** [comment]
Hi...

So I do that...

I get this response with this test:

Response:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "text": "Es wird momentan kein Song abgespielt.",
      "type": "PlainText"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}

Request ID:
"fb74b76b-50ca-460d-a0f9-30e4c2ecd6f3"

Function Logs:
START RequestId: fb74b76b-50ca-460d-a0f9-30e4c2ecd6f3 Version: $LATEST
END RequestId: fb74b76b-50ca-460d-a0f9-30e4c2ecd6f3
REPORT RequestId: fb74b76b-50ca-460d-a0f9-30e4c2ecd6f3	Duration: 0.44 ms	Billed Duration: 100 ms 	Memory Size: 512 MB	Max Memory Used: 63 MB	

I tested it in my alexa app too and there I get this response:
Skill response was marked as failure
Request Identifier: amzn1.echo-api.request.c101fff5-2893-4432-a560-e7c4256158c9
The target Lambda application returned a failure response

**Comment by ndg63276** [comment]
Ok, so that test proves the code is all correct. Something is going wrong when you speak to Alexa. Can I confirm that you get the failure if you say:

Alexa, open YouTube, (wait for response), what is the current timestamp?

**Comment by Fantasymerlin** [comment]
Yes...

I get the failure if I say:
Alexa, öffne youtube (wait), what is the current timestamp? and if I say...
Alexa, ask youtube, what is the current timestamp? too.

I tried this in german and also in english language too. I get the same error at both language and in all variants.

**Comment by ndg63276** [comment]
Ok, you'll have to look at some logs. Ask Alexa for the timestamp, then go to https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logs:. Click on /aws/lambda/YouTube, and then click on the most recent log stream. Hopefully you can see an error there.

**Comment by Fantasymerlin** [comment]
Hello...

yes I have delete all and make a new test. Only so I could find a report for that. I hope it is the right one but this is that what I think which can help to find the failure...

> [INFO] 2019-05-26T20:02:33.363Z f9d0f7bf-f780-40e0-a7f3-c35917b3e5f3 {u'version': u'1.0', u'request': {u'offsetInMilliseconds': 0, u'locale': u'de-DE', u'timestamp': u'2019-05-26T20:02:33Z', u'token': u'v30=1q1Ub4xUlWc&v31=JJz92IB5Zjc&v18=1VXGRhdW_i4&v19=c4AJR5NCepg&v34=xp5X3kA0S1g&v35=JtLy_mn7aB4&v36=otd7Q3THHhI&v37=F5zEhd4E7wE&v12=x7mvEakz3Uw&v13=0dLf0XXMjx8&v10=sSK7fkA4z8c&v11=zI5EEF_wFv0&v16=QqVP5vIa-8g&v17=AjtGlAad_e0&v14=Zw6omUFQm48&v15=2Zm47XuZBos&v33=4SPJZ3S8J68&query=ben_zucker&s=0&v41=D2pFA38Ozhs&v40=bv2U5nteiDk&v43=GWVBAyGvZ-8&v42=1eKOC3B-ihY&v45=ml2MwSkSMro&v44=zpUdSyVk4Ug&v47=NXp_wmmkNC4&v39=7BUFLeB-y4w&v49=Os0P8dHzUkM&v48=G3EEKy_kQGs&v32=rTX2u5vLvJw&v23=J29T9E4CSLY&v22=gAYBG_cXkSM&v21=IQwrGqpC8-Y&v20=k4KOlnkPMHM&v27=1FMj8CSuOSA&v26=M1Z3HMFs8g8&v25=weYkKQJfhz8&v24=5mQGmqrSdBg&v29=e2Z_eBkyxbU&v28=1yJoDv8zCWM&v0=n8NYD5qHdBw&v46=RCKWswBMZT8&v2=kAsAoyaqh1Y&v3=lc4oUzjtj7I&v4=vZzlcRBs4yc&v5=fIDxb7xjMik&v6=ALdivljP7fg&v7=i0YSXAJt0FA&v8=6vxZ4mEWkqg&v9=hLHVZ7JCMQQ&a=1&v1=Vu403ZAEtxE&i=Search&sr=0&l=0&p=4&v38=I2OmX5t1GGA', u'requestId': u'amzn1.echo-api.request.7825bc21-4062-4659-9353-2eea65f2ee6d', u'type': u'AudioPlayer.PlaybackStarted'}, u'context': {u'AudioPlayer': {u'token': u'v30=1q1Ub4xUlWc&v31=JJz92IB5Zjc&v18=1VXGRhdW_i4&v19=c4AJR5NCepg&v34=xp5X3kA0S1g&v35=JtLy_mn7aB4&v36=otd7Q3THHhI&v37=F5zEhd4E7wE&v12=x7mvEakz3Uw&v13=0dLf0XXMjx8&v10=sSK7fkA4z8c&v11=zI5EEF_wFv0&v16=QqVP5vIa-8g&v17=AjtGlAad_e0&v14=Zw6omUFQm48&v15=2Zm47XuZBos&v33=4SPJZ3S8J68&query=ben_zucker&s=0&v41=D2pFA38Ozhs&v40=bv2U5nteiDk&v43=GWVBAyGvZ-8&v42=1eKOC3B-ihY&v45=ml2MwSkSMro&v44=zpUdSyVk4Ug&v47=NXp_wmmkNC4&v39=7BUFLeB-y4w&v49=Os0P8dHzUkM&v48=G3EEKy_kQGs&v32=rTX2u5vLvJw&v23=J29T9E4CSLY&v22=gAYBG_cXkSM&v21=IQwrGqpC8-Y&v20=k4KOlnkPMHM&v27=1FMj8CSuOSA&v26=M1Z3HMFs8g8&v25=weYkKQJfhz8&v24=5mQGmqrSdBg&v29=e2Z_eBkyxbU&v28=1yJoDv8zCWM&v0=n8NYD5qHdBw&v46=RCKWswBMZT8&v2=kAsAoyaqh1Y&v3=lc4oUzjtj7I&v4=vZzlcRBs4yc&v5=fIDxb7xjMik&v6=ALdivljP7fg&v7=i0YSXAJt0FA&v8=6vxZ4mEWkqg&v9=hLHVZ7JCMQQ&a=1&v1=Vu403ZAEtxE&i=Search&sr=0&l=0&p=4&v38=I2OmX5t1GGA', u'playerActivity': u'PLAYING', u'offsetInMilliseconds': 0}, u'System': {u'device': {u'deviceId': u'amzn1.ask.device.AH2NQ3MZDA2WIW4JSGC5EQYCO2DNBR3SHUVGOIY7V6J7ZUGLUOG4DZ6ZG5QUEFY2XQYWKB3K4ZKEGBEHGBUDYK545CNDCTPIU6PFVGSJXCXE524CRQRYHVIFPBZD2HY7A6OBQH2GLR3JC5AJ7DU5N74N3ATULWB2EQKIZBQ6IPQGJUKSEN2JW', u'supportedInterfaces': {u'AudioPlayer': {}}}, u'application': {u'applicationId': u'amzn1.ask.skill.e878c39b-c698-4582-8eb2-3579c96d7c12'}, u'apiAccessToken': u'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmU4NzhjMzliLWM2OTgtNDU4Mi04ZWIyLTM1NzljOTZkN2MxMiIsImV4cCI6MTU1ODkwMTI1MywiaWF0IjoxNTU4OTAwOTUzLCJuYmYiOjE1NTg5MDA5NTMsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjoiQXR6YXxJd0VCSU5BRG9yb0pXMUN1V1NvRm1fdmUyTXJiVm5jaWV3SmpnZ1RyZGV3QmZaY2Fady1IVUlwX0pKNnZkbXBaQ1dmUFE0SUZJYlNXdlREVnlNVTNjLWthdUFrUE9NM25vSmdwaVpJMmc0OHh3WHkyMW5rVEx5bVRxVHdhZzJwTnpMVXI1aWZydXl5S3ZMdTMzMWJ5c1l1S3d4TGZtaFZ3TktCMFhZaGJqNmk0ZVR3MGFJTk1XdWlGdWdfRm1jSU4zZXdvVzVKTkJSS190Zm90ZEdJaWcyRWZRbS1faDViZkUteEFPaTNDQ2JXVGJBb2tBQkRRZVNfWE92T2xic2xGcUlSSDQwcmljUTdNRzczYjNyYjhVSEFBaENKUVhFbElXd2s4TjducTFMUEJHX0J1MC1sYzV5WnZ2YU5ZYmdMenlsZzRkTGtra0pNazRxQ3dieXczUDJKNkVuZXJsRkhwbDEzeUxwSkFZTTdTM0xzTVpqN1NYUzF5YnVGc2xPa2c4am9Ob1VkOVdZN1p5amZYeDhqQ2pyTERzdzhNeVpMdGJzd19SWi1aeVhJYjkzTzFYenY2VEZUUXdFLXVYbzR0czQ5RVNOQlV4MWk4a2UtM3BmdUNOZnlmX3FScDFLUGpxbVlTWm0tUFk5RXRfOHVGSXhaUEgxbGtnQV8yRTI0ZG4xb0toTVJOSjZ0Z1ptcmFvVTNGVjUzeE5rUU1pN3RFY2VuZURqcS1iV3pDQXJFZXpONGdPYnZTZFo5VmZnZ0RpZWxURW9zIiwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFIMk5RM01aREEyV0lXNEpTR0M1RVFZQ08yRE5CUjNTSFVWR09JWTdWNko3WlVHTFVPRzREWjZaRzVRVUVGWTJYUVlXS0IzSzRaS0VHQkVIR0JVRFlLNTQ1Q05EQ1RQSVU2UEZWR1NKWENYRTUyNENSUVJZSFZJRlBCWkQySFk3QTZPQlFIMkdMUjNKQzVBSjdEVTVONzROM0FUVUxXQjJFUUtJWkJRNklQUUdKVUtTRU4ySlciLCJ1c2VySWQiOiJhbXpuMS5hc2suYWNjb3VudC5BSFBKNFdINlczVllJVjMzQ1ZaSzdZQ1dJNFJIMjdYTFJaVTVZTk9XRDNQTkZGRkdFNkw2M1RaWFhGUEhFR0tXSVNSTzc2VUg0SlVDUFBMNlhWSk9YRVZSUkpNU1hXTFBMNU1aM1g3T0dHQVRCSDJPMllOVVRUU0NFVkVCT1dQQTNPNU1HS09MV0hJVE4zTTZWR1hBREk0M1hMUkNLSjZNSlhOTFNNRFZWMjdWRUxGR0NOUkg2WkZTSkFDN1RSWk9IV0hLNVBWRzZBNU4zTkkifX0.EJspDxkAIXAjTjJ7IblQxQcheyexn5Imzza0Jivvaq8B17aDMK-y62tPzECgMuJUS-kT2wuxz1lUDaZOG4-a7m59wq8GTmEpsNrFaGSYy9se8g-I2nyFMI83SHcd4PTFBXFpBrebUri83oBjA0eFYn0mGUgn9X83aBtCnu3UCT9M34j_fqx6uYskydOPd059ddb5JCnG8ZMjkVRUg8oykNGXXOStTrvZa8afzYd6Alv90nEqEa-J0z0fCPnbUhHZ_J94WzOcTAjRpnpFO8X6nAF75zpyqmAmXMlhf0AzibXUptW27TMqnic344c_PmCrvxuav8X8ar-ATG9Vflp4nQ', u'user': {u'userId': u'amzn1.ask.account.AHPJ4WH6W3VYIV33CVZK7YCWI4RH27XLRZU5YNOWD3PNFFFGE6L63TZXXFPHEGKWISRO76UH4JUCPPL6XVJOXEVRRJMSXWLPL5MZ3X7OGGATBH2O2YNUTTSCEVEBOWPA3O5MGKOLWHITN3M6VGXADI43XLRCKJ6MJXNLSMDVV27VELFGCNRH6ZFSJAC7TRZOHWHK5PVG6A5N3NI', u'permissions': {u'consentToken': u'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmU4NzhjMzliLWM2OTgtNDU4Mi04ZWIyLTM1NzljOTZkN2MxMiIsImV4cCI6MTU1ODkwNDU1MywiaWF0IjoxNTU4OTAwOTUzLCJuYmYiOjE1NTg5MDA5NTMsInByaXZhdGVDbGFpbXMiOnsiaXNEZXByZWNhdGVkIjoidHJ1ZSIsImNvbnNlbnRUb2tlbiI6IkF0emF8SXdFQklOQURvcm9KVzFDdVdTb0ZtX3ZlMk1yYlZuY2lld0pqZ2dUcmRld0JmWmNhWnctSFVJcF9KSjZ2ZG1wWkNXZlBRNElGSWJTV3ZURFZ5TVUzYy1rYXVBa1BPTTNub0pncGlaSTJnNDh4d1h5MjFua1RMeW1UcVR3YWcycE56TFVyNWlmcnV5eUt2THUzMzFieXNZdUt3eExmbWhWd05LQjBYWWhiajZpNGVUdzBhSU5NV3VpRnVnX0ZtY0lOM2V3b1c1Sk5CUktfdGZvdGRHSWlnMkVmUW0tX2g1YmZFLXhBT2kzQ0NiV1RiQW9rQUJEUWVTX1hPdk9sYnNsRnFJUkg0MHJpY1E3TUc3M2IzcmI4VUhBQWhDSlFYRWxJV3drOE43bnExTFBCR19CdTAtbGM1eVp2dmFOWWJnTHp5bGc0ZExra2tKTWs0cUN3Ynl3M1AySjZFbmVybEZIcGwxM3lMcEpBWU03UzNMc01aajdTWFMxeWJ1RnNsT2tnOGpvTm9VZDlXWTdaeWpmWHg4akNqckxEc3c4TXlaTHRic3dfUlotWnlYSWI5M08xWHp2NlRGVFF3RS11WG80dHM0OUVTTkJVeDFpOGtlLTNwZnVDTmZ5Zl9xUnAxS1BqcW1ZU1ptLVBZOUV0Xzh1Rkl4WlBIMWxrZ0FfMkUyNGRuMW9LaE1STko2dGdabXJhb1UzRlY1M3hOa1FNaTd0RWNlbmVEanEtYld6Q0FyRWV6TjRnT2J2U2RaOVZmZ2dEaWVsVEVvcyIsImRldmljZUlkIjoiYW16bjEuYXNrLmRldmljZS5BSDJOUTNNWkRBMldJVzRKU0dDNUVRWUNPMkROQlIzU0hVVkdPSVk3VjZKN1pVR0xVT0c0RFo2Wkc1UVVFRlkyWFFZV0tCM0s0WktFR0JFSEdCVURZSzU0NUNORENUUElVNlBGVkdTSlhDWEU1MjRDUlFSWUhWSUZQQlpEMkhZN0E2T0JRSDJHTFIzSkM1QUo3RFU1Tjc0TjNBVFVMV0IyRVFLSVpCUTZJUFFHSlVLU0VOMkpXIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUhQSjRXSDZXM1ZZSVYzM0NWWks3WUNXSTRSSDI3WExSWlU1WU5PV0QzUE5GRkZHRTZMNjNUWlhYRlBIRUdLV0lTUk83NlVINEpVQ1BQTDZYVkpPWEVWUlJKTVNYV0xQTDVNWjNYN09HR0FUQkgyTzJZTlVUVFNDRVZFQk9XUEEzTzVNR0tPTFdISVROM002VkdYQURJNDNYTFJDS0o2TUpYTkxTTURWVjI3VkVMRkdDTlJINlpGU0pBQzdUUlpPSFdISzVQVkc2QTVOM05JIn19.MsUYIVtmgCgdGku1numN4XnFaCDncUkF0HOfdQDb3Z5ANWXndTl0FxraM0qfPPDZY5j8VG5IdaM67nkG4SiNS-oMYWYYQSEI1BZ2b3xC4ce83n4LXpz9aAcwoKOc_CTkzJYzSeeu7aZ-oYjixc99klOCTj9QnC_LwQPMcMz5gxXRRBtQwisskXXN8Z9U9Rvmr7ekDC0oxvdC24AqaHhuxi8U4uTAvySHBGD4V0gh0mQWyj2wVsAXrnSfoebG5pyASNEuHgZZms1TfBJnJOeDTyvClNyKt311dgnZllVdNf4pT7vXaC1cThZtG8xUGtZnP3bvQTDbaLxTWFFe2_8WFw'}}, u'apiEndpoint': u'https://api.eu.amazonalexa.com'}}}

**Comment by ndg63276** [comment]
Aha! Well done, that is the error message, and it tells me the problem exactly. It is missing some German translations. I need:
"The current position is 1 hour 1 minute 1 second"
"The current position is 2 hours 2 minutes 2 seconds"

**Comment by Fantasymerlin** [comment]
you need the translations for it. It´s no problem...

"The current position is 1 hour 1 minute 1 second"
in German = "Die aktuelle Position ist: 1 Stunde 1 Minute und 1 Sekunde

"The current position is 2 hours 2 minutes 2 seconds"
in German = "Die aktuelle Position ist: 2 Stunden 2 Minuten und 2 Sekunden

This is what you mean right?

**Comment by ndg63276** [comment]
That's perfect. I have uploaded a new version of lambda_function.zip to https://github.com/ndg63276/alexa-youtube/raw/master/lambda_function.zip, if you can upload that to your lambda, hopefully it should fix your problem. Step by step instructions:
1) go to https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions
2) click on YouTube
3) scroll down to the "Function Code" section
4) change "Code Entry Type" to "Upload a zip file"
5) click "Upload", and select the zip file saved from the address above
6) click "Save" in the top right

**Comment by Fantasymerlin** [comment]
It works perfect.

Alexa says:
"Die aktuelle Position ist 0 Minuten 47 Sekunden"

The skill will be better and better.

You are PERFECT!!!
