### ISSUE TITLE
Error when creating the lambda function for personal youtube api key deployment

### ISSUE THREAD

**Issue by Laxaeus** [ndg63276/alexa-youtube#66]
Not exactly a bug but I wonder if someone can help, I'm trying to deploy my own youtube key but when I access AWS console under one of the region provided by the guide and I start creating a new lambda function from blueprints, I can never find the alexa blueprint. Any idea on how to solve this? Thank you.

**Comment by ndg63276** [comment]
Yeah looks like it disappeared. I'll have to rewrite the wiki.

**Comment by ndg63276** [comment]
Ok have removed references to blueprints. You should be able to Author From Scratch, then select Alexa Skills Kit as the trigger. That is all the blueprint did anyway.

**Comment by Laxaeus** [comment]
In the triggers' list Alexa Skills Kit is not there apparently.

**Comment by ndg63276** [comment]
Which region are you using? Alexa Skills Kit will only be there in Ireland, Tokyo, Oregon and N Virginia.

**Comment by Laxaeus** [comment]
Thank you, I fixed it, it was another issue I had :) I successfully updated the endpoint for Alexa, I will try it out asap and if you want I can notify you as feedback to let you know if everything works correctly. Thank you for your help.
