### ISSUE TITLE
Anker Zolo Speaker Support

### ISSUE THREAD

**Issue by rbmanian75** [ndg63276/alexa-youtube#68]
Hi,
I have followed the procedure and setup the skill and lambda instance. I tested in iphone alexa and its working fine.

But when i try to test the skill in Anker Zolo Speaker it does not work. The skill is activated and it is asking for playing video. When i ask for video it find the video and saying playing the video. But no audio is coming from speaker.

Is there any way to fix this issue. Or this will only work with official amazon echo speakers.

Thank You

**Comment by ndg63276** [comment]
If you go to https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logs: , click on "/aws/lambda/youtube", and then click on the most recent log. Can you see any errors?

I can't really tell if this should work on Zolo. I have been told it doesn't work on Sonos.

**Comment by rbmanian75** [comment]
I checked the error and here is the log
START RequestId: 21f609ff-2507-4ae3-8234-769009b8031a Version: $LATEST

20:42:10
[INFO] 2019-05-29T20:42:10.352Z 21f609ff-2507-4ae3-8234-769009b8031a
Playback failed

20:42:10
[INFO] 2019-05-29T20:42:10.353Z 21f609ff-2507-4ae3-8234-769009b8031a
{u'version': u'1.0', u'request': {u'locale': u'en-US', u'timestamp':
u'2019-05-29T20:42:10Z', u'currentPlaybackState': {u'playerActivity':
u'IDLE'}, u'token': u'v30=xxxxxx

20:42:10
[INFO] 2019-05-29T20:42:10.353Z 21f609ff-2507-4ae3-8234-769009b8031a
{u'message': u'streamingError', u'type':
u'MEDIA_ERROR_INTERNAL_DEVICE_ERROR'}

Thanks

**Comment by ndg63276** [comment]
Thanks for that. Unfortunately it's just a generic error, that says the Zolo cannot play this file. So I don't think this skill will work with that hardware.
