### ISSUE TITLE
Translations for the german strings

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#69]
I had checked the translations for the correct responses in german.

I had found some incorrect translations...

> strings_de = {
'welcome1':"Herzlich willkommen bei Youtube. Was kann ich für Dich tun? Sage zum Beispiel 'spiel Videos von The Beatles'.",
'welcome2':"Oder sag misch Songs von Michael Jackson.",
'help':"Sag zum Beispiel 'spiel Videos von Fall Out Boy ab' um Videos von Fall Out Boy abzuspielen.",
'illegal':"Das kannst Du mit diesen Skill nicht tun.",
'gonewrong':"Das tut mir Leid, das hat nicht funktioniert",
'playlist':"Die Wiedergabeliste",
'channel':"Der Kanal",
'video':"Das Video",
'notworked':"hat nicht funktioniert, soll ich das nächste Element versuchen?",
'playing':"Spiele",
'pausing':"Pausieren",
'nomoreitems':"Die Wiedergabeliste enthält keine weiteren Elemente.",
'resuming':"Fortsetzen",
'noresume':"Leider konnte ich nicht weiter spielen.",
'novideo':"Dieses Video konnte ich nicht abspielen.",
'notitle':"Ich kann den Namen des aktuellen Videos nicht finden.",
'nowplaying':"Es läuft gerade",
'nothingplaying':"Es wird momentan kein Song abgespielt.",
'sorryskipby':"Entschuldigung, ich habe nicht verstanden, wie viel ich überspringen soll",
'sorryskipto':"Entschuldigung, ich habe nicht verstanden, wohin ich springen soll",
'ok':"OK",
'currentposition':"Die aktuelle Position ist",
'hours':"Stunden",
'hour':"Stunde",
'minutes':"Minuten",
'minute':"Minute",
'seconds':"Sekunden",
'second':"Sekunde",
}

Examples:
* The Welcome-Message I define more friendly for the User. Alexa make a greetings in german language now. "Welcome to Youtube. What can I do for you? Say, for example, 'play videos of The Beatles'"! In german we don´t say only welcome (Willkommen), we say "Herzlich willkommen". This is more friendly.

* The word "Spielen" was wrong. For a Song we ask for there everytime the response was "Spielen". In english language this is the same "playing" = "spielen" and "spiele". In german language the word for one song everytime is "spiele". For the german user it hearing with the response "spiele" with a better german and the skill is more professional.

* for skipto and skipby the translations I could not understand as only a normal user what Alexa meaning. Therefore I translate it other now that everybody understand what is meaning with this responses.

* for pausing this was right. You can say "pausieren". You can also say "pausiere". You also can say "Stop". But I think "pausieren" is better because the user can understand it so that he can later come back and hear on the same position further again. Therefore "Pausieren" is right here.

Therefore I gives now the right translations for your skill in german language. I had changed in my lambda and test it before. So it sounds perfect for the german ears and I could help you for your skill.

**Comment by ndg63276** [comment]
Thanks, have updated the file.
