### ISSUE TITLE
Could not find any enabled video skills

### ISSUE THREAD

**Issue by jbritz** [ndg63276/alexa-youtube#7]
Hi Guys,

Thank you for the YouTube skill.
When I try it out on my device I get a response along the lines of "Could not find any enabled video skills to play that?", I am most probably just doing something wrong.

Anyone else experience this?

Thanks

Details:
I am trying this on the new generation Echo Dot.
My command is "Alexa, ask youtube to play summer of 69"

**Comment by prasenjithaty** [comment]
@jbritz refer this https://stackoverflow.com/questions/39068523/alexa-skill-not-recognized-when-tested-on-echo

**Comment by ndg63276** [comment]
I've had this mentioned elsewhere, normally means you didn't enable Testing for the skill. Make sure to follow instruction 15 (which I've now made more prominent.)
