### ISSUE TITLE
New playlist or renamed playlist unplayable 

### ISSUE THREAD

**Issue by kunicmarko20** [ndg63276/alexa-youtube#70]
1. What are you saying to Alexa? Alexa, ask youtube to play my playlist NAME_HERE
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? my own
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? yes
5. What language are you using? English

Not sure if there is maybe a wait time but I created a new playlist and it is not playable, I am getting "I wasn't able to play a video". Same thing happened with a playlist which name I changed.

**Comment by kunicmarko20** [comment]
So a small update, after I changed the name of a playlist it is still playable under the old name. So I guess the youtube API is returning old data?

**Comment by kunicmarko20** [comment]
Created a new list, same issue but I checked the data youtube API is returning and the new playlists are there, am I missing something? Do I need to rebuild skill when I create a new playlist?

**Comment by kunicmarko20** [comment]
Works now. My best guess is that there is some cache?

**Comment by ndg63276** [comment]
As you may have guessed, I use this API to get results from YouTube: https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.search.list

Whatever it returns is not my fault! I do no caching, but Google might. Mostly it just seems slow to update, for example if you create a new playlist.

**Comment by kunicmarko20** [comment]
Ah, didn't check in detail what endpoint you were using. Thank you for your work on this!
