### ISSUE TITLE
YT Skill don´t play my own playlists. Find playlist with google explorer with other settings

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#71]
Hello,

I tried again that Alexa can play my own playlists on Youtube. I created a Testplaylist. This is my link:
https://www.youtube.com/channel/UCdAJnXFpTz5QtVa1O9a4a2Q/playlists

On this link I can see my Playlist. I marked it as official playlist that all can find it.

If I search on youtube for this playlist I can´t find it. If I search for my own channel I can find.

I test it with this command "start meine Playlist "Renes Schlager2K19". I tried with "start meine Wiedergabeliste". --> translation is "start my playlist Renes Schlager 2K19".

I get this response "Dieses Video konnte ich nicht finden". This is in english "I cannot find this Video".

I don´t know why I can´t play my own playlist.

I tried with "Spiel mein Kanal..." --> "play my channel..." too. Alexa plays then a channel but it is not my channel. It is a channel from a other person.

Did I have set on my channel something?

On the lambda I set this:

DEVELOPER_KEY = My Api Key

and I tried with this too...
MY_CHANNEL_ID = UCdAJnXFpTz5QtVa1O9a4a2Q

UPDATE:

I have found something. I tested it with the google explorer.

With the settings...
https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.search.list?part=id%252Csnippet&channelId=UCdAJnXFpTz5QtVa1O9a4a2Q&type=playlist&_h=2&

youtube.search.list, id,snippet, channelId and playlist it doesn't find my playlist. I get total results = 0

But with this I find my playlist...
https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.playlists.list?part=snippet&mine=true&_h=4&

youtube.playlists.list, snippet, mine=true and only with OAuth I find my playlist. I get results of 1

But also this seems to work to find my playlist...
https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.playlists.list?part=id%252Csnippet&channelId=UCdAJnXFpTz5QtVa1O9a4a2Q&_h=3&

youtube.playlists.list, id,snippet, channelId. I get results of 1

Therefore I had take a look at the code and saw at...
def my_playlists_search(query, sr, do_shuffle='0')

that it make a searching about youtube.search.list When the searching goes about youtube.playlists.list I think it can working with own playlists. A searching with the google explorer gives me a result with my playlist. You can see it here...
  

`200 OK

 
- Show headers -
  

{
 "kind": "youtube#playlistListResponse",
 "etag": "\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/M1vDi9mvApTq6dyoQItE-d7V1x4\"",
 "pageInfo": {
  "totalResults": 1,
  "resultsPerPage": 5
 },
 "items": [
  {
   "kind": "youtube#playlist",
   "etag": "\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/B3pEo1IKw8bvZy5ScIp7wB4n1XU\"",
   "id": "PLBuM22qqig8kzVHjV6t6Y35aOi5TITkLJ",
   "snippet": {
    "publishedAt": "2019-05-16T22:14:27.000Z",
    "channelId": "UCdAJnXFpTz5QtVa1O9a4a2Q",
    "title": "Renes Schlager2k19",
    "description": "",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/a3EgWAriu28/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/a3EgWAriu28/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/a3EgWAriu28/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Rene Mar",
    "localized": {
     "title": "Renes Schlager2k19",
     "description": ""
    }
   }
  }
 ]
}`

**Comment by ndg63276** [comment]
Yes, you are right to an extent. I also get the same results, your playlist appears under youtube.playlists.list.

But that API does not let you search by playlist name, it just provides a list of all your playlists. In theory, I could get the list of your playlists, then try to do fuzzy string matching to find the one you want, but that is horrible code to write. Plus, google only returns 50 per page, so how many pages do I have to look through?

If it helps, I made a public playlist in February, and it now appears in search results, so hopefully yours will appear soon!

You are of course able to edit the code in your lambda instance, if you just have one playlist, you could do:

```
def my_playlists_search(query, sr, do_shuffle='0'):
    channel_id = None
    playlist_id = None
    if 'MY_CHANNEL_ID' in environ:
        channel_id = environ['MY_CHANNEL_ID']
    search_response = youtube.playlists().list(
        part='id,snippet',
        maxResults=10,
        channelId=channel_id
        ).execute()
    playlist_id = search_response.get('items')[sr]['id']
    logger.info('Playlist info: https://www.youtube.com/playlist?list='+playlist_id)
    playlist_title = search_response.get('items')[sr]['snippet']['title']
    videos = []
    data={'nextPageToken':''}
    while 'nextPageToken' in data and len(videos) < 200:
        next_page_token = data['nextPageToken']
        data = youtube.playlistItems().list(part='snippet',maxResults=50,playlistId=playlist_id,pageToken=next_page_token).execute()
        for item in data['items']:
            try:
                videos.append(item['snippet']['resourceId']['videoId'])
            except:
                pass
    if do_shuffle == '1':
        shuffle(videos)
    return videos[0:50], playlist_title, sr
```

**Comment by Fantasymerlin** [comment]
Hello,

uii... it works perfectly.

Now I can fill my own playlist with some songs. I can start it now with the name of the playlist.

Thank you very much

**Comment by Fantasymerlin** [comment]
Hello,

now I find my playlists in the google api explorer. This is what I find now:

https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.search.list?part=id%252Csnippet&channelId=UCdAJnXFpTz5QtVa1O9a4a2Q&type=playlist&_h=2&

If I test in alexa dev console I get the response that it play this pl what I want. This I can see on the right side. If I test the link url I only get a white side. Cannot see there the audio how at other songs.

						"stream": {
							"token": "a=1&v1=sOnqjkJTMaA&i=SearchMyPlaylists&sr=0&l=0&v0=Zi_XLOBDo_Y&p=0&s=0&v3=4kHl4FoK1Ys&v4=OBwS66EBUcY&v5=KFq4E9XTueY&v6=Ju9TkM83tyk&v7=HeWF_fy8tLE&v2=btPJPFnesV4&query=my_80er",
							"url": "https://r1---sn-aigl6nl7.googlevideo.com/videoplayback?expire=1560104346&ei=Ovn8XLa5JsP-1gKAyqHICQ&ip=52.215.204.43&id=o-ACblzZ8gNDxnRJ6j3lj4euJ-xnb2sai_GYXuzBbPkAJV&itag=140&source=youtube&requiressl=yes&mm=31,26&mn=sn-aigl6nl7,sn-4g5e6nsr&ms=au,onr&mv=m&pl=13&gcr=ie&initcwndbps=348750&mime=audio/mp4&gir=yes&clen=4789410&dur=295.891&lmt=1557010821868896&mt=1560082588&fvip=1&keepalive=yes&beids=9466587&c=WEB&txp=5532432&sparams=expire,ei,ip,id,itag,source,requiressl,gcr,mime,gir,clen,dur,lmt&lsparams=mm,mn,ms,mv,pl,initcwndbps&lsig=AHylml4wRgIhANLYdSRzXYKZaubJzKEBZ5CxlzAHirkeeiXlSJx3Wk1BAiEAmrEOYQ1gL2yU-vt-Ska_Nkw1zVQ2yTQ23uRQNKfFZPk=&signature=ALgxI2wwRQIhAOlx-eqbXGEJeuOvTuJ3S831xyy1M9-NRu91jaO1ro-uAiBvJpO8MZHbYQEieRCbD2GVnOWF5rT8ZKGdoMjpcK89aA==",
							"offsetInMilliseconds": 0

If I ask my Echo or the Alexa App I ever get the respinse that the video can´t play.

I test it with MY_CHANNEL_ID in environ and also with "channel_id = 'UCdAJnXFpTz5QtVa1O9a4a2Q'".

It seems there is something wrong. It has to play my playlists now with my_playlists search but it don´t want to do this.

I used the normal code to play it.

Please help to find out what is the reason for this. Your regularly code has to work right now.

Thank you very much

**Comment by Fantasymerlin** [comment]
I solved it now...

I setting new the name of the playlists to "My own" + Genre. It seems that al better name of the playlists solved the issue
