### ISSUE TITLE
cant find any enabled video skills 

### ISSUE THREAD

**Issue by ss4sgoku** [ndg63276/alexa-youtube#72]
1. What are you saying to Alexa?
alexa ask youtube to play queen(this is an example) 
alexa dile a youtube ponme salsa (this is what i normaly use)
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
im was using mine arn:aws:lambda:eu-west-1:507444230335:function:YouTube and then i try yours with the same result
4. If you are running your own lambda instance, have you uploaded the latest 
lambda_function.zip file? This changes regularly to fix problems.
yes
5. What language are you using?
spanish and try english too with the same result

i have 2 echo dot 3 the skill was working awesome until 1 month ago and then it said that something wrong happen and later it started to say that cant find video skills etc
i deleted my old skill and made a new one using your guide and tal9000v2 guide too
but nothing happens i remake everything 10 times and delete everthing the same
in the aws console i enable an amazon alexa start session and this is what it gives me back:
{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      228,
      "lambda_handler",
      "return get_welcome_response(event)"
    ],
    [
      "/var/task/lambda_function.py",
      415,
      "get_welcome_response",
      "list_created = create_list(event, 'YouTube')"
    ],
    [
      "/var/task/lambda_function.py",
      315,
      "create_list",
      "headers = get_headers(event)"
    ],
    [
      "/var/task/lambda_function.py",
      307,
      "get_headers",
      "apiAccessToken = event['context']['System']['apiAccessToken']"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'apiAccessToken'"
}

![Captura de pantalla (90)](https://user-images.githubusercontent.com/51476506/59095741-d63dc380-88de-11e9-9a21-25c402554b62.png)

**Comment by ndg63276** [comment]
Some sort of problem with creating a list of songs played. I've updated lambda_function.zip, can you try again?

**Comment by ss4sgoku** [comment]
Okey I will do it in a couple of hours because I'm working now , I will let
you know how it goes

**Comment by ss4sgoku** [comment]
ok i made it again and try to use it but the same happend and said that the skill dont answer in spanish or the cant find video skills etc in english, i test it again in the lambda with the alexa start sesion and everthing was right, then i goes to the cloudwatch register and i found an error there something about 'token': KeyError

![Captura de pantalla (91)](https://user-images.githubusercontent.com/51476506/59141282-80fdc280-896f-11e9-817e-a92a9e357f9e.png)

i hope it can help you to find a fix for it :)

**Comment by ss4sgoku** [comment]
i try again but no i said alexa open youtube and it welcome me and told me how to use it.....and then alexa say to youtube......., and again the skill doesnt work in spanish or cant find video skill etc.. in english i lookup again in the cloudwatch register and i found another error list permision not granted....
![Captura de pantalla (93)](https://user-images.githubusercontent.com/51476506/59141367-5876c800-8971-11e9-9924-39e7d286ee24.png)

**Comment by ndg63276** [comment]
"List permission not granted" is fine.

"Key error: token" is the problem, it thinks you are asking "Play more like this", but nothing is playing. I have added some code to tell you nothing is playing, but I guess that is not what you meant to do?

Can you try:
"Alexa, abrir YouTube" (wait while she says "Bienvenido")
"Pon musica de salsa"

**Comment by ss4sgoku** [comment]
hi its me again, okey i try the new version and test it in usa_en and  es_mx , the spanish version its still giving me headaches and doesnt work.... dont know why, but the english version works in some strange bad bad really baddd way....i change my alexa to english from us and the skill too and use the right json for en, if i ask to play queen it said that will play bohemian rapsody but it never does in the cloudwatch records show me this
![Captura de pantalla (94)](https://user-images.githubusercontent.com/51476506/59249298-08ef0100-8bea-11e9-9fd9-5474807d3b48.png)

it try to play the song but it fail and it search again to try to play another one, and another one time after time ...... and maybe.... maybe if i find all the dragon balls or  10-30 minutes pass, later after so many tryings it plays a song 

this is the error that show up in the tryings

![Captura de pantalla (96)](https://user-images.githubusercontent.com/51476506/59249521-96325580-8bea-11e9-8b07-3ce4da9e7e37.png)

![Captura de pantalla (97)](https://user-images.githubusercontent.com/51476506/59249600-c7128a80-8bea-11e9-88f3-461d34d98294.png)

**Comment by ndg63276** [comment]
Looks like this https://github.com/nficano/pytube/issues/399

**Comment by ss4sgoku** [comment]
the "List permission not granted" doesnt show in the en version but in the spanish_mx appear, the only way to get rid off it its to open the skill in my alexa app in my cellphone get in the skill section open the youtube skill and give it the permissions
in the spanish mx if i use the skill console test i always have to say abrir youtube for the skill to start or will never work my comands(the old versions dont need that)
after that if i said as the example it give me and i said "ponme salsa" or "ponme boleros" in the skill console test, the order goes fine with out errors and in the cloudwatch logs doest show error but, if i say to my echo abrir youtube (that its something that i never have to do in the version i use months ago) and then i give the order to "ponme boleros" or "pon musica de salsa" it said : la skill solicitada no responde(the called skill doesnt work... its like the no video skill error in english) and in the cloudwatch showme an 'AudioPlayer': KeyError

![Captura de pantalla (98)](https://user-images.githubusercontent.com/51476506/59255680-0bf0ee00-8bf8-11e9-8d10-8d4d7a247e63.png)

:( im really sorry if im bothering you

**Comment by ss4sgoku** [comment]
i just try what its said by changing &signature= in line 64 of mixins.py to &sig= but doesnt make any diference...

**Comment by ndg63276** [comment]
Ok, I've uploaded a new lambda_function.zip, with the fix from pytube, and a fix for the AudioPlayer Keyerror. I'm not at home so I can't test it, but let me know how you get on.

Don't worry about the list permissions error, it should ignore it.

**Comment by ss4sgoku** [comment]
hi i tested again in english and spanish and it works.... but........
first if i test it in the aws console it using the amazo alexa start session it runs fine but show an apiAccessToken not found dont know if thats right...
![Captura de pantalla (99)](https://user-images.githubusercontent.com/51476506/59290004-15e91000-8c3d-11e9-827d-e7d91bf8d77a.png)

okey another error, the skill only work if i say alexa to launch or abrir youtube if i dont do that it doesnt work, the old version (2 months ago) didnt need that
after the skill its launch i can ask to play some music but it jump from one video to another arround 6 times before it finally start play and the cloudwatch show play back fail
![Captura de pantalla (100)](https://user-images.githubusercontent.com/51476506/59290251-bdfed900-8c3d-11e9-8ba3-857a2409a6d8.png)

and the bigger error, after that it plays the song and everthing goes fine until i change my mind and want to hear something diferent, if i said alexa, ask to youtube play .........  it said im not sure what went wrong , and in the cloudwatch doesnt show any error or i didnt find it..
so to play something diferent i have to say alexa stop or finish and launch again the skill etc wich is a lil annoying

**Comment by ndg63276** [comment]
1) ApiAccessToken not found - don't worry, that is only in testing, the skill will continue.
2) If you say "Alexa ask Youtube to play Gangnam Style" (in whatever language), and she says she can't find any video skills, that means Alexa is not invoking my skill. There is nothing I can do about that.
3) There are lots of problems with PyTube at the moment, see https://github.com/nficano/pytube/issues. I have put in a fix as best I can, but I think there are still problems. Make sure you are using today's version of lambda_function.zip. When the developers of PyTube fix the problems, I will apply the fix to this skill.

**Comment by ss4sgoku** [comment]
mmm so there is nothing that can i do to leave the skill open so i can use it any time without the need of launch it again an again??
its there another way to make it change the songs that is playing for something diferent or new that i want than stop or finish the skill and relaunch it again....or i have to wait for the pytube solution to fix it??

**Comment by ndg63276** [comment]
If the skill worked 2 months ago, maybe the Spanish changes that were made 2 months ago broke it?

You could try this version of the interaction model? https://raw.githubusercontent.com/ndg63276/alexa-youtube/7c15873626aa1eebff19bf5cf49fa5cc78c220a0/InteractionModel_es.json

**Comment by ss4sgoku** [comment]
hi, i try it and doesnt work.... i edit it on the skill and the lambda but doesnt work, the english version works fine i only have to say alexa ask to youtube to play rock and it does and while its playing if i want something diferent i only have to say again ask to youtube to play salsa for example and it makes the change without problems  but if i try the same on the spanish version alexa dile a youtube ponme rock she say Lo siento, ha ocurrido un error ... and i need to launch the skill to make it work...

**Comment by ndg63276** [comment]
"ponme" doesn't seem to work very well. Can you try "pon musica de rock"?

**Comment by ss4sgoku** [comment]
and nothing.... i even add my own word "quiero" had the same result..... only works when first launch the skill  in the moment that she say to me that i can use for example blablabla...... in that moment i can use whatever i want to play a song or give her any kind of order otherwise she said that something goes wrong...

**Comment by ss4sgoku** [comment]
an update i use the english json file for my spanish config an only use the word play as i use in english to search for a new song and had the same result as the spanish file only play a song in the moment i launch the skill :(

**Comment by ss4sgoku** [comment]
hi i tested the last 2 versions and everything works awesome finally :) you are greate, i made in my  spanish json file a lil mod, i add some extra ways to ask for music some works better than others, i delete some extra spaces made with tab thanks for all, this error is solved

**Comment by ss4sgoku** [comment]
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "youtube",
            "intents": [
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PauseIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ResumeIntent",
                    "samples": []
                },
                {
                    "name": "SearchIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Que quiero musica de {query}",
                        "Que quiero escuchar musica de {query}",
                        "Que quiero escuchar canciones de {query}",
                        "Que quiero canciones de {query}",
                        "Que quiero escuchar {query}",
                        "Que quiero {query}",
                        "Quiero escuchar musica de {query}",
                        "Quiero escuchar canciones de {query}",
                        "Quiero canciones de {query}",
                        "Quiero escuchar {query}",
                        "Quiero {query}",
                        "Ponme candiones de {query}",
                        "Ponme una cancion de {query}",
                        "Ponme {query}",
                        "Play {query}",
                        "Pon musica de {query}",
                        "Pon canciones de {query}",
                        "Pon temas de {query}",
                        "Pon tracks de {query}",
                        "Pon videos de {query}",
                        "Pon sonidos de {query}",
                        "Busca musica de {query}",
                        "Busca canciones de {query}",
                        "Busca temas de {query}",
                        "Busca tracks de {query}",
                        "Busca videos de {query}"
                    ]
                },
                {
                    "name": "PlayOneIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Pon la cancion {query}",
                        "Pon una cancion de {query}",
                        "Pon el tema {query}",
                        "Pon un tema de {query}",
                        "Pon el video {query}",
                        "Pon un video de {query}",
                        "Pon el track {query}",
                        "Pon un track de {query}"
                    ]
                },
                {
                    "name": "ShuffleIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Aleatorio canciones de {query}",
                        "Canciones en aleatorio de {query}",
                        "Canciones aleatorias de {query}",
                        "Temas en aleatorio de {query}",
                        "Temas aleatorios de {query}",
                        "Tracks en aleatorio de {query}",
                        "Tracks aleatorios de {query}",
                        "Videos en aleatorio de {query}",
                        "Videos aleatorios de {query}",
                        "Pon canciones en aleatorio de {query}",
                        "Pon canciones aleatorias de {query}",
                        "Pon musica en aleatorio de {query}",
                        "Pon musica aleatoria de {query}",
                        "Pon temas en aleatorio de {query}",
                        "Pon temas aleatorios de {query}",
                        "Pon tracks en aleatorio de {query}",
                        "Pon tracks aleatorios de {query}"
                    ]
                },
                {
                    "name": "PlaylistIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Pon playlist {query}",
                        "Pon lista {query}",
                        "Pon una playlist de {query}",
                        "Pon una lista de {query}",
                        "Pon la playlist {query}",
                        "Pon la lista {query}",
                        "Reproduce playlist de {query}"
                    ]
                },
                {
                    "name": "ShufflePlaylistIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Aleatorio playlist de {query}",
                        "Pon playlist aleatoria {query}",
                        "Pon lista aleatoria {query}",
                        "Pon una playlist aleatoria de {query}",
                        "Pon una lista aleatoria de {query}",
                        "Pon en aleatorio la lista {query}",
                        "Pon en aleatorio la playlist {query}",
                        "Haz una mezcla de la lista {query}",
                        "Haz un remix de la lista {query}",
                        "Lista aleatoria {query}",
                        "Aleatorio lista {query}",
                        "Mezcla la lista {query}",
                        "Remezcla la lista {query}",
                        "Playlist aleatoria {query}"
                    ]
                },
                {
                    "name": "SearchMyPlaylistsIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Pon mi lista {query}",
                        "Pon mi playlist {query}",
                        "Abre mi lista {query}",
                        "Reproduce mi lista {query}",
                        "Reproduce mi playlist {query}"
                    ]
                },
                {
                    "name": "NextPlaylistIntent",
                    "slots": [],
                    "samples": [
                        "Siguiente playlist",
                        "Siguiente lista"
                    ]
                },
                {
                    "name": "ShuffleMyPlaylistsIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Remueve mi lista {query}",
                        "Mezcla mi lista {query}",
                        "Remezcla mi lista {query}",
                        "Haz una mezcla de mi lista {query}",
                        "Haz una remix de mi lista {query}",
                        "Pon en aleatorio mi lista {query}"
                    ]
                },
                {
                    "name": "ChannelIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Pon el canal {query}",
                        "Abre el canal {query}",
                        "Reproduce el canal {query}"
                    ]
                },
                {
                    "name": "ShuffleChannelIntent",
                    "slots": [
                        {
                            "name": "query",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": [
                        "Pon en aleatorio el canal {query}",
                        "Pon en aleatorio el canal de {query}",
                        "Canal en aleatorio {query}",
                        "Canal aleatorio {query}"
                    ]
                },
                {
                    "name": "NowPlayingIntent",
                    "slots": [],
                    "samples": [
                        "Que esta sonando",
                        "Que suena",
                        "Quien es",
                        "Quien canta",
                        "Quien toca",
                        "Quien suena",
                        "Que video es",
                        "Que cancion es",
                        "Que cancion suena",
                        "Que es esto",
                        "Que se oye",
                        "Que se esta oyendo"
                    ]
                },
                {
                    "name": "PlayMoreLikeThisIntent",
                    "slots": [],
                    "samples": [
                        "Similar",
                        "Parecido",
                        "Pon mas de esto",
                        "Pon mas como esto",
                        "Pon mas videos como este",
                        "Pon mas videos parecidos a este",
                        "Pon mas musica como esta",
                        "Pon mas musica parecida a esta",
                        "Pon una cancion similar",
                        "Pon una cancion parecida",
                        "Pon una cancion como esta",
                        "Pon un tema similar",
                        "Pon un tema parecido",
                        "Pon un tema como este",
                        "Pon videos similares",
                        "Pon videos parecidos",
                        "Pon videos como este",
                        "Pon canciones similares",
                        "Pon canciones parecidas",
                        "Pon canciones como esta",
                        "Pon temas similares",
                        "Pon temas parecidos",
                        "Pon temas como este",
                        "Pon artistas similares",
                        "Pon artistas parecidos",
                        "Pon artistas como este",
                        "Pon musica parecida",
                        "Pon musica similar",
                        "Pon musica como esta",
                        "Busca mas de esto",
                        "Busca mas como esto",
                        "Busca mas videos como este",
                        "Busca mas videos parecidos a este",
                        "Busca mas musica como esta",
                        "Busca mas musica parecida a esta",
                        "Busca una cancion similar",
                        "Busca una cancion parecida",
                        "Busca una cancion como esta",
                        "Busca un tema similar",
                        "Busca un tema parecido",
                        "Busca un tema como este",
                        "Busca videos similares",
                        "Busca videos parecidos",
                        "Busca videos como este",
                        "Busca canciones similares",
                        "Busca canciones parecidas",
                        "Busca canciones como esta",
                        "Busca temas similares",
                        "Busca temas parecidos",
                        "Busca temas como este",
                        "Busca artistas similares",
                        "Busca artistas parecidos",
                        "Busca artistas como este",
                        "Busca musica parecida",
                        "Busca musica similar",
                        "Busca musica como esta"
                    ]
                },
                {
                    "name": "AutoplayOnIntent",
                    "slots": [],
                    "samples": [
                        "Enciende autoplay",
                        "Enciende el autoplay"
                    ]
                },
                {
                    "name": "AutoplayOffIntent",
                    "slots": [],
                    "samples": [
                        "Apaga autoplay",
                        "Apaga el autoplay"
                    ]
                },
                {
                    "name": "SayTimestampIntent",
                    "slots": [],
                    "samples": [
                        "Que minuto es",
                        "Que minuto del video es",
                        "Que minuto de la cancion es",
                        "Cual es la marca de tiempo"
                    ]
                },
                {
                    "name": "SkipToIntent",
                    "slots": [
                        {
                            "name": "minutes",
                            "type": "AMAZON.NUMBER"
                        },
                        {
                            "name": "seconds",
                            "type": "AMAZON.NUMBER"
                        },
                        {
                            "name": "hours",
                            "type": "AMAZON.NUMBER"
                        }
                    ],
                    "samples": [
                        "Hora {hours}",
                        "Minuto {minutes}",
                        "Segundo {seconds}",
                        "Minuto {minutes} segundo {seconds}",
                        "Hora {hours} minuto {minutes}",
                        "Hora {hours} minuto {minutes} segundo {seconds}",
                        "Salta {minutes} {seconds}",
                        "Salta {hours} {minutes} {seconds}",
                        "Salta a la hora {hours}",
                        "Salta al minuto {minutes}",
                        "Salta al segundo {seconds}",
                        "Salta al minuto {minutes} y al segundo {seconds}",
                        "Salta a la hora {hours} y al minuto {minutes}",
                        "Salta a la hora {hours} al minuto {minutes} y al segundo {seconds}",
                        "Ve a {minutes} {seconds}",
                        "Ve a {hours} {minutes} {seconds}",
                        "Ve a la hora {hours}",
                        "Ve al minuto {minutes}",
                        "Ve al segundo {seconds}",
                        "Ve a la hora {hours} y al minuto {minutes}",
                        "Ve a la hora {hours} al minuto {minutes} y al segundo {seconds}"
                    ]
                },
                {
                    "name": "SkipForwardIntent",
                    "slots": [
                        {
                            "name": "minutes",
                            "type": "AMAZON.NUMBER"
                        },
                        {
                            "name": "seconds",
                            "type": "AMAZON.NUMBER"
                        },
                        {
                            "name": "hours",
                            "type": "AMAZON.NUMBER"
                        }
                    ],
                    "samples": [
                        "Avanza {minutes} {seconds}",
                        "Avanza {hours} {minutes} {seconds}",
                        "Avanza {hours} hora",
                        "Avanza {hours} horas",
                        "Avanza {minutes} minuto",
                        "Avanza {minutes} minutos",
                        "Avanza {seconds} segundo",
                        "Avanza {seconds} segundos",
                        "Avanza {hours} hora y {minutes} minuto",
                        "Avanza {hours} hora y {minutes} minutos",
                        "Avanza {hours} horas y {minutes} minuto",
                        "Avanza {hours} horas y {minutes} minutos",
                        "Avanza {hours} hora {minutes} minuto y {seconds} segundo",
                        "Avanza {hours} hora {minutes} minuto y {seconds} segundos",
                        "Avanza {hours} hora {minutes} minutos y {seconds} segundos",
                        "Avanza {hours} horas {minutes} minuto y {seconds} segundo",
                        "Avanza {hours} horas {minutes} minuto y {seconds} segundos",
                        "Avanza {hours} horas {minutes} minutos y {seconds} segundos",
                        "Adelanta {minutes} {seconds}",
                        "Adelanta {hours} {minutes} {seconds}",
                        "Adelanta {hours} hora",
                        "Adelanta {hours} horas",
                        "Adelanta {minutes} minuto",
                        "Adelanta {minutes} minutos",
                        "Adelanta {seconds} segundo",
                        "Adelanta {seconds} segundos",
                        "Adelanta {hours} hora y {minutes} minuto",
                        "Adelanta {hours} hora y {minutes} minutos",
                        "Adelanta {hours} horas y {minutes} minuto",
                        "Adelanta {hours} horas y {minutes} minutos",
                        "Adelanta {hours} hora {minutes} minuto y {seconds} segundo",
                        "Adelanta {hours} hora {minutes} minuto y {seconds} segundos",
                        "Adelanta {hours} hora {minutes} minutos y {seconds} segundos",
                        "Adelanta {hours} horas {minutes} minuto y {seconds} segundo",
                        "Adelanta {hours} horas {minutes} minuto y {seconds} segundos",
                        "Adelanta {hours} horas {minutes} minutos y {seconds} segundos",
                        "Salta {hours} hora",
                        "Salta {hours} horas",
                        "Salta {minutes} minuto",
                        "Salta {minutes} minutos",
                        "Salta {seconds} segundo",
                        "Salta {seconds} segundos",
                        "Salta {hours} hora y {minutes} minuto",
                        "Salta {hours} hora y {minutes} minutos",
                        "Salta {hours} horas y {minutes} minuto",
                        "Salta {hours} horas y {minutes} minutos",
                        "Salta {hours} hora {minutes} minuto y {seconds} segundo",
                        "Salta {hours} hora {minutes} minuto y {seconds} segundos",
                        "Salta {hours} hora {minutes} minutos y {seconds} segundos",
                        "Salta {hours} horas {minutes} minuto y {seconds} segundo",
                        "Salta {hours} horas {minutes} minuto y {seconds} segundos",
                        "Salta {hours} horas {minutes} minutos y {seconds} segundos"
                    ]
                },
                {
                    "name": "SkipBackwardIntent",
                    "slots": [
                        {
                            "name": "minutes",
                            "type": "AMAZON.NUMBER"
                        },
                        {
                            "name": "seconds",
                            "type": "AMAZON.NUMBER"
                        },
                        {
                            "name": "hours",
                            "type": "AMAZON.NUMBER"
                        }
                    ],
                    "samples": [
                        "Retrocede {minutes} {seconds}",
                        "Retrocede {hours} {minutes} {seconds}",
                        "Retrocede {hours} hora",
                        "Retrocede {hours} horas",
                        "Retrocede {minutes} minuto",
                        "Retrocede {minutes} minutos",
                        "Retrocede {seconds} segundo",
                        "Retrocede {seconds} segundos",
                        "Retrocede {hours} hora y {minutes} minuto",
                        "Retrocede {hours} hora y {minutes} minutos",
                        "Retrocede {hours} horas y {minutes} minuto",
                        "Retrocede {hours} horas y {minutes} minutos",
                        "Retrocede {hours} hora {minutes} minuto y {seconds} segundo",
                        "Retrocede {hours} hora {minutes} minuto y {seconds} segundos",
                        "Retrocede {hours} hora {minutes} minutos y {seconds} segundos",
                        "Retrocede {hours} horas {minutes} minuto y {seconds} segundo",
                        "Retrocede {hours} horas {minutes} minuto y {seconds} segundos",
                        "Retrocede {hours} horas {minutes} minutos y {seconds} segundos",
                        "Atrasa {minutes} {seconds}",
                        "Atrasa {hours} {minutes} {seconds}",
                        "Atrasa {hours} hora",
                        "Atrasa {hours} horas",
                        "Atrasa {minutes} minuto",
                        "Atrasa {minutes} minutos",
                        "Atrasa {seconds} segundo",
                        "Atrasa {seconds} segundos",
                        "Atrasa {hours} hora y {minutes} minuto",
                        "Atrasa {hours} hora y {minutes} minutos",
                        "Atrasa {hours} horas y {minutes} minuto",
                        "Atrasa {hours} horas y {minutes} minutos",
                        "Atrasa {hours} hora {minutes} minuto y {seconds} segundo",
                        "Atrasa {hours} hora {minutes} minuto y {seconds} segundos",
                        "Atrasa {hours} hora {minutes} minutos y {seconds} segundos",
                        "Atrasa {hours} horas {minutes} minuto y {seconds} segundo",
                        "Atrasa {hours} horas {minutes} minuto y {seconds} segundos",
                        "Atrasa {hours} horas {minutes} minutos y {seconds} segundos"
                    ]
                },
                {
                    "name": "AMAZON.YesIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NoIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                }
            ],
            "types": []
        }
    }
}
