### ISSUE TITLE
How to play Playlist from beginning titel by titel?

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#73]
Hello,

Now the playlists are to find with the normal code for youtube.search. I say "Alexa, frag youtube, start meine Playlist #Name#" / "Alexa, ask youtube, start my playlist #Name#.

I put to environ in the lambda...
DEVELOPER_KEY = my dev key
MY_CHANNEL_ID = my channel id

With this I can search for all my Playlists and I can find all my playlists by saying the name of the list.

But I find out, that Alexa beginning the playlist on any point of the playlist. This isn´t a problem for me when Alexa shuffle the songs. But Alexa plays some songs (maybe 3 or 4) and then she is at the end of the playlist.

I think I have to put more songs into the playlist right?
How can I reset the playlist that it starts at the beginning again if I reached the end (The problem is if Alexa starts for example at the last song I reached the end again and I have to start again)?
Some songs are in the playlist I never hear by Alexa. Why? (I tested and on searching for a song from the playlist it plays)

Only this little problems! The playlist search works now.

I take a look into playlist items from a playlist. It seems okey. I done this with the google api explorer with youtube.playlistsitems.list

https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.playlistItems.list?part=id%252Csnippet&maxResults=50&playlistId=PLBuM22qqig8n1hM4nQJIOJdyayRlpckfx&_h=2&

**Comment by ndg63276** [comment]
Have you tried turning on loop mode? "Alexa, loop mode on"

**Comment by Fantasymerlin** [comment]
No I think this I do not. I did it now and turn loop on. I test it now if this works.

**Comment by Fantasymerlin** [comment]
yes the loop mode is on now. It seems that it starts at titel 5 now if the end is reached.

When I say "Alexa..., back" Alexa says the titel but it don´t plays and goes to titel 5.

It is possible, that it seems some time after creating a new playlist till all songs playable? I don´t know why it don´t plays titel 1 till 4. The loop mode seems to work now. After the end is reached it takes 10 seconds and the playlist begins at titel 5 again.

But what is with titel 1, 2, 3 and 4? Titel 5 till 8 are playing without problems,

**Comment by ndg63276** [comment]
Some videos just don't play, I don't know why. The best thing to do is:
1) Ask for the song you want ("Alexa, ask Youtube for Michael Jackson Billie Jean")
2) Skip to a suitable version (I get a live version initially)
3) Ask what is playing ("Alexa, ask YouTube what song is playing")
4) Find the video with the exact same title. I find this one https://www.youtube.com/watch?v=B02LXuKWGTI
5) Put that one in your playlist, instead of the official one.

**Comment by Fantasymerlin** [comment]
Ok. I understand. Some videos stucks. Then I put other version of this songs which don´t plays.

The loop mode don´t works fine. Some time later Alexa forgotten it and stops after reaching the end of the playlist.

Now I am unable to get loop mode on again. It stucks if I want to try now.

**Comment by ndg63276** [comment]
When I test with your playlist, Alexa thinks I say "My own 80s", but the playlist is called "My own eighties".

It might be worth renaming your playlist to "My own 80s", or something without numbers in.

**Comment by Fantasymerlin** [comment]
Oh yes. I had the problem, too. I renamed the playlist first from "My own 80er" to "My own 80s". Alexa don´t understand this. Therefore I called it to "My own Eighties". Because the german version of Alexa understand this "eighties" better than "80er" or "80s". Normally we say "80er" in germany but Alexa have problems with this. My Echo understand "My own Eighties" without problems! Maybe the english Alexa understand "My own 80s" better but the german Alexa play this without problems.

It seems that everyone have to test the best name for the playlist because I think every language have other results of understanding from Alexa.

To the other I look for german command to get loop mode on! The english command she don´t accept. But if I say "Alexa, starte den loop modus" she do it. I test it with the playlist and she begins from the beginning again. Now I don´t have a problem anymore when Alexa starts for example in the middle of the playlist.

**Comment by ndg63276** [comment]
Ok, that makes sense. It just makes it harder to test in English!

**Comment by Fantasymerlin** [comment]
ok. I created for you for testing a playlist "my own 80s" and filled it with the same content. It needs some time till it is in the api. But I think tomorrow you can see it and can test.

**Comment by Fantasymerlin** [comment]
Good morning,

I tried to hear this morning some music from my playlist. But something there is wrong. I ask youtube to play one of my playlist and Alexa says "Play #Name#". The first Titel was playing fine but from the beginning of the second Titel Alexa says me "play #Name of the Titel#" and nothing is to hear. I go to next Titel but nothing is to hear. I test a song by saying "ask youtube play a video from #Name of Interpret#. Alexa says me "play #Name of Interpret and song#" But nothing is to hear.

After I can´t hear something of all songs I test it in the Alexa developer under Test in the skill. I take a look of the URL from the response. In the URL itself there is nothing. This seems the reason that there is nothing to hear.

Here I give you a example:
https://r2---sn-q0cedn7s.googlevideo.com/videoplayback?expire=1560255743&ei=n0j_XPLjKsiQgAfRnY6oAw&ip=52.211.80.232&id=o-ALet81Vms9OsQwYIRwNra0Zcee1ljQQtuZ0qidOX1lux&itag=140&source=youtube&requiressl=yes&mm=31,26&mn=sn-q0cedn7s,sn-aigl6n7z&ms=au,onr&mv=u&pl=20&mime=audio/mp4&gir=yes&clen=9012887&dur=556.860&lmt=1556979520592451&mt=1560232903&fvip=6&keepalive=yes&c=WEB&txp=5535432&sparams=expire,ei,ip,id,itag,source,requiressl,mime,gir,clen,dur,lmt&lsparams=mm,mn,ms,mv,pl&lsig=AHylml4wRgIhAJrM1FB4ekuAxCO41Ti5bUGwO_2H6yPWwRil-LSxWgprAiEAqhqQT2J3fcZ3L5SjT82kbClKygRdvzt37eJ3gaL02NM=&signature=ALgxI2wwRgIhAKga9mwrifaNNUApFus8lMjdWGRHUAWsdvwfROF30iuVAiEA3_FssduhvvP3dgufJDLymTLkv9HD1NKb7GIoXoc89RA=

In this link there is nothing inside. Normally I can se a small player and can hear a the Song which I have ask for but in this example there is only a white page to see. The Link is right but is empty. I see this very oft in the last 2 days.

Also I get often the response "This Video I cannot play". After some Minutes I get the response (with the same ask" "Play #Name#" but nothing is to hear.

Is there something with google? Do you have this often too?

Do you know the reason why this is?
