### ISSUE TITLE
The stream is empty since today. Alexa accept the command and make the response correctly but nothing is to hear

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#74]
Good morning,

I tried to hear this morning some music from my playlist. But something there is wrong. I ask youtube to play one of my playlist and Alexa says "Play #Name#". The first Titel was playing fine but from the beginning of the second Titel Alexa says me "play #Name of the Titel#" and nothing is to hear. I go to next Titel but nothing is to hear. I test a song by saying "ask youtube play a video from #Name of Interpret#. Alexa says me "play #Name of Interpret and song#" But nothing is to hear.

The Problem is at all commands for playing songs (For example when I ask "Alexa ask my youtube, play videos by..., play a song from, start my playlist #Name#, etc.)

After I can´t hear something of all songs I test it in the Alexa developer under Test in the skill. I take a look of the URL from the response. In the URL itself there is nothing. This seems the reason that there is nothing to hear.

Here I give you a example:
https://r2---sn-q0cedn7s.googlevideo.com/videoplayback?expire=1560255743&ei=n0j_XPLjKsiQgAfRnY6oAw&ip=52.211.80.232&id=o-ALet81Vms9OsQwYIRwNra0Zcee1ljQQtuZ0qidOX1lux&itag=140&source=youtube&requiressl=yes&mm=31,26&mn=sn-q0cedn7s,sn-aigl6n7z&ms=au,onr&mv=u&pl=20&mime=audio/mp4&gir=yes&clen=9012887&dur=556.860&lmt=1556979520592451&mt=1560232903&fvip=6&keepalive=yes&c=WEB&txp=5535432&sparams=expire,ei,ip,id,itag,source,requiressl,mime,gir,clen,dur,lmt&lsparams=mm,mn,ms,mv,pl&lsig=AHylml4wRgIhAJrM1FB4ekuAxCO41Ti5bUGwO_2H6yPWwRil-LSxWgprAiEAqhqQT2J3fcZ3L5SjT82kbClKygRdvzt37eJ3gaL02NM=&signature=ALgxI2wwRgIhAKga9mwrifaNNUApFus8lMjdWGRHUAWsdvwfROF30iuVAiEA3_FssduhvvP3dgufJDLymTLkv9HD1NKb7GIoXoc89RA=

In this link there is nothing inside. Normally I can se a small player and can hear the Song which I have ask for but in this example there is only a white page to see. The Link is right but is empty. I see this very oft in the last 2 days. You can see very good at the alexa developer console because there we can see the url for the streaming.

Also I get often the response "This Video I cannot play". After some Minutes I get the response (with the same ask" "Play #Name#" but nothing is to hear.

Is there something with google? Do you have this often too?

Do you know the reason why this is? In the moment I cannot hear music but I didn´t make changes in the lambda or in the skill.

I test again and I ask for the position. All Songs are at 0min and 00sec. Therefore I think the problem must be when I get the stream https://r2---sn-q0cedn7s.googlevideo.com/videoplayback? and a white page (link is created but empty)

**Comment by ndg63276** [comment]
Looks like this https://github.com/nficano/pytube/issues/399

**Comment by Fantasymerlin** [comment]
Yeeahh. I changed line 64 in mixins.py the variable &signature to &sig. It works again.

I tested it with one of my playlist. The first Titel works fine. I ask for next Titel. Also works fine and sofortly.

Thank you very much...

**Comment by ndg63276** [comment]
Actually it might be https://github.com/nficano/pytube/issues/398, so I've put the fix for that in lambda_function.zip. 398 and 399 are very similar though.

**Comment by kunicmarko20** [comment]
And I thought it was something on my side, will redeploy! Need to watch this repo :smile:

**Comment by kunicmarko20** [comment]
works like a charm, thank you @ndg63276 !

**Comment by Fantasymerlin** [comment]
I test it with more playlists as one. In this playlists are more then 1000 songs.

I test it with a playlist with some megamixes with a lenght about 1 hour per video.

Also I test it with "start my playlist" and with "mix my playlist...".

For me it works perfectly now.

**Comment by kunicmarko20** [comment]
I am still getting random failures and playback not wanting to start:

![Screenshot from 2019-06-12 20-25-19](https://user-images.githubusercontent.com/13528674/59380144-52f1f700-8d50-11e9-8a5f-0c4eec6e0a1d.png)

besides that I see:

> [INFO] 2019-06-12T19:17:10.270Z fe32abce-a842-4cb2-a5d3-76adf4b06393 {u'message': u'Response code: 403 : DataSpec[https://r2---sn-aigzrn7l.googlevideo.com/videoplayback?expire=1560388626&ei=sk8BXcGhJ9uYgAeYlobIDw&ip=54.154.228.167&id=o-APRNj41GDVa0XcIs_PmX_TmV7I5YICC4rvzEK_yKxpjW&itag=140&source=youtube&requiressl=yes&mm=31,26&mn=sn-aigzrn7l,sn-4g5ednsl&ms=au,onr&mv=m&pl=16&gcr=ie&initcwndbps=6112
[INFO] 2019-06-12T19:17:10.270Z fe32abce-a842-4cb2-a5d3-76adf4b06393 {u'message': u'Response code: 403 : DataSpec[https://r2---sn-aigzrn7l.googlevideo.com/videoplayback?expire=1560388626&ei=sk8BXcGhJ9uYgAeYlobIDw&ip=54.154.228.167&id=o-APRNj41GDVa0XcIs_PmX_TmV7I5YICC4rvzEK_yKxpjW&itag=140&source=youtube&requiressl=yes&mm=31,26&mn=sn-aigzrn7l,sn-4g5ednsl&ms=au,onr&mv=m&pl=16&gcr=ie&initcwndbps=611250&mime=audio/mp4&gir=yes&clen=3244187&dur=204.219&lmt=1518963411414812&mt=1560366917&fvip=2&keepalive=yes&c=WEB&sparams=expire,ei,ip,id,itag,source,requiressl,gcr,mime,gir,clen,dur,lmt&lsparams=mm,mn,ms,mv,pl,initcwndbps&lsig=AHylml4wRgIhAKV7Q7J4_JCeaPziN51VoTyvS93qmL5M7KqOqjgvMVLWAiEA7P6CmMv7uo8Mz-Cm7U9IABa8AZ-8YOjou3DW9ZuM7lI=, null, 0, 0, -1, null, 0]', u'type': u'MEDIA_ERROR_INVALID_REQUEST'}

In logs, should I open a new issue?

**Comment by Fantasymerlin** [comment]
I believe that you have to change in mixins.py the variable &signature to &sig. I have read that the change doing in the lambda_function.zip. Change it or download the lambda_function.zip and save this new in your lambda. Then try it.

**Comment by ndg63276** [comment]
Try the latest lambda_function.zip, I've tried a few combinations of &sig, &lsig and &signature, this seems to work best for me.
