### ISSUE TITLE
Official songs wont play

### ISSUE THREAD

**Issue by brussli1** [ndg63276/alexa-youtube#76]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
Alexa, ask youtube play gorillaz. or rival dealer by burial. unfinished sympathy massive attack, etc.
2. What video are you trying to play? Please provide the youtube URL.
https://www.youtube.com/watch?v=Uuwc6MzbB9w

3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
arn:aws:lambda:us-east-1:3228???0504:function:YouTube

4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
Yes

5. What language are you using?
English
 

Alexa just chooses something related to the song.

Edit: it was working as of yesterday.

**Comment by Fantasymerlin** [comment]
Yes I have this bug too!

**Comment by ndg63276** [comment]
Unfortunately this is just one of those things, covered by this statement in the Readme:

> Some videos just fail, it's not clear why

If you install pytube, add the latest fixes, and run this code:
```
>>> from pytube import YouTube
>>> yt=YouTube('https://www.youtube.com/watch?v=Uuwc6MzbB9w')
>>> yt.streams.filter(only_audio=True, subtype='mp4').first().url
```
You get a url, when you load it in a browser, it gives an error, access denied. You'd have to take it up with pytube, nothing I can do I'm afraid.

**Comment by Fantasymerlin** [comment]
it is possible that this is the problem for this bug?

https://github.com/nficano/pytube/issues/410

**Comment by ndg63276** [comment]
Don't think so, I can play https://www.youtube.com/watch?v=tOMPGQP1G8o

**Comment by Fantasymerlin** [comment]
please try...

https://www.youtube.com/watch?v=yBJ0Ex5aPq8

yesterday this works. Today don´t works

**Comment by ndg63276** [comment]
Doesn't work for me either.

**Comment by Fantasymerlin** [comment]
I have found the problem...

        match_patterns = [
            r'\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'(?P<name>[a-zA-Z0-9$]+)\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)',
            r'(["\'])signature\1\s*,\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\.sig\|\|(?P<name>[a-zA-Z0-9$]+)\(',
            r'yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*'
            r'(?P<name>[a-zA-Z0-9$]+)\(',
            r'\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\bc\s*&&\s*a\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\('
]

This code has changed in cipher.py

**Comment by ndg63276** [comment]
Good to hear, where did you get that code?

**Comment by Fantasymerlin** [comment]
I make a look into the cipher.py from nficano at pytube.

The Idea comes if I read the issues there and then I understand that the bug has come from the signatures.

Therefore I compaires my cipher.py with this from nficano. Then I found it and tried with this code.

And it works sofortly

**Comment by ndg63276** [comment]
I get an error with the line

 > r'(["'])signature\1\s*,\s*(?P[a-zA-Z0-9$]+)(',

**Comment by Fantasymerlin** [comment]
I have this on my lambda...

def get_initial_function_name(js):
    """Extract the name of the function responsible for computing the signature.

    :param str js:
        The contents of the base.js asset file.

    """
    # c&&d.set("signature", EE(c));
    pattern = [
            r'\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'(?P<name>[a-zA-Z0-9$]+)\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)',
            r'(["\'])signature\1\s*,\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\.sig\|\|(?P<name>[a-zA-Z0-9$]+)\(',
            r'yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*'
            r'(?P<name>[a-zA-Z0-9$]+)\(',
            r'\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\bc\s*&&\s*a\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\(',
            r'\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<name>[a-zA-Z0-9$]+)\('
    ]
    
    
    logger.debug('finding initial function name')
    return regex_search(pattern, js, group=1)

**Comment by ndg63276** [comment]
I see, there was a missing '\\'. That now works for your video.

Did you write these regex's? I don't want to deploy it without testing further.

**Comment by Fantasymerlin** [comment]
I write it into my lambda and test it on my echo. It works.

try it. It really works.

**Comment by ndg63276** [comment]
OK, changed cipher.py and reuploaded lambda_function.zip.

**Comment by brussli1** [comment]
that fixed it. Thanks a lot for this!.

**Comment by rybot666** [comment]
@ndg63276 Close?
