### ISSUE TITLE
Hosting on my Lambda

### ISSUE THREAD

**Issue by rybot666** [ndg63276/alexa-youtube#78]
I'm happy to help host this skill with my lambda (also free tier). @ndg63276

**Comment by ndg63276** [comment]
That's great. What is your endpoint?

eg arn:aws:lambda:eu-west-1:1234567890:function:YouTube

**Comment by rybot666** [comment]
arn:aws:lambda:us-west-2:827204026059:function:YouTube

**Comment by mreassassin** [comment]
would I be able to copy/paste this into my endpoint default region field and have the skill work?  I'm running into the 'null' error if I try to play a video.  saying alexa launch youtube seems to work fine.  like #77 

any help appreciated!

**Comment by ndg63276** [comment]
@rybot666 - I get an error if I try and play a video using your endpoint. Does it work ok for you? Can you check you have the latest version of lambda_function.zip uploaded, and check your Google API key is working ok?

**Comment by ndg63276** [comment]
@mreassassin - the problem on #77 was with the Google API key. I updated lambda_function.zip on friday to check for this, so you could try using that.

**Comment by rybot666** [comment]
@ndg63276 @mreassassin Sorry, the problem was that I hadn't saved my memory and timeout changes. I just set them and verified - the endpoint now works. Do you want me to make a PR to modify the readme or something?

**Comment by ndg63276** [comment]
Thanks, that's great.

Keep an eye on your Amazon account, if you start getting charges, we can remove your ARN from the readme.
