### ISSUE TITLE
Making Sure I Don't Incur Charges on AWS 

### ISSUE THREAD

**Issue by coot66** [ndg63276/alexa-youtube#79]
I signed up for the free tier using the instruction provided and found it pretty easy to set up. Is there something I need to do to make sure I don't get charged for my AWS Lambda? 

I don't remember setting a limit anywhere and am curious if there's something I can do to make sure I don't end up going over the free tier usage.

**Comment by ndg63276** [comment]
I'm not sure you can set a limit, but you are extremely unlikely to get charged anything, the free tier covers a lot. For example. the lambda free tier is 400,000 GB-Seconds per month. This skill uses half a Gigabyte, so you have 800,000 seconds a month. Each time the skill plays a new song, it takes about 5 seconds, so unless you play 160,000 songs a month, you won't be charged for lambda usage. You can check your estimated bill for the month at any time by going to https://console.aws.amazon.com/billing/home#/bills .
