### ISSUE TITLE
AudioPlayer is currently an unsupported namespace

### ISSUE THREAD

**Issue by jbritz** [ndg63276/alexa-youtube#8]
Hi all,

Just a quick question, is anyone else experience the following error when trying to test the youtube skill from the browser: "AudioPlayer is currently an unsupported namespace"

It seems to be just an emulator problem but I though let me just check with you as well. (See [https://stackoverflow.com/questions/49764431/error-while-playing-audio-file-for-alexa-audioplayer-is-currently-an-unsupporte])

Cheers

**Comment by ndg63276** [comment]
Yeah I get the same, don't worry. It's just the emulator.
