### ISSUE TITLE
Rewrite in Nodejs to make an Alexa-hosted Skill

### ISSUE THREAD

**Issue by Robert-K** [ndg63276/alexa-youtube#81]
First of all a huge thank you for developing and maintaining this skill. It has become one of my favorite Alexa features.
I noticed that Amazon also offers "Alexa-hosted skills", basically nodejs-only AWS skills, deployable without an AWS account.
Do you think it would be possible to port alexa-youtube to this format? I imagine it would take the load of your AWS instances and make deploying this skill easier/possible for "normal" users.

Keep up the great work & cheers,
Robert

**Comment by ndg63276** [comment]
It's a good idea, but it would mean rewriting in nodejs. I don't know nodejs, though I would like to.

So it's a 'maybe', if anyone out there is good at nodejs and wants to help, let me know.

**Comment by Barbaro** [comment]
Hi,

I think I could help you if you have (a lot of) time to put in it :)

**Comment by ndg63276** [comment]
I think we could at least make a simple one, to play one video at a time. Do you have any thoughts about the best way to collaborate? Should I make a new github repository?

**Comment by Barbaro** [comment]
A new github would be a good idea to start :)
Then, you could list the existing py files we would need to adapt in nodejs, or at least the workflow to follow to play one video.

**Comment by ndg63276** [comment]
Ok, created at https://github.com/ndg63276/alexa-youtube-nodejs, added you as a Collaborator. Have started with some nodejs files I found in a tutorial, but they do basically nothing at the moment (haven't even tested)!

**Comment by Barbaro** [comment]
Hey, how do you want to discuss ? Discord, mails etc.. ?
________________________________
De : ndg63276 <notifications@github.com>
Envoyé : lundi 12 août 2019 12:28
À : ndg63276/alexa-youtube <alexa-youtube@noreply.github.com>
Cc : Barbaro <barbaro7@hotmail.fr>; Comment <comment@noreply.github.com>
Objet : Re: [ndg63276/alexa-youtube] Rewrite in Nodejs to make an Alexa-hosted Skill (#81)


Ok, created at https://github.com/ndg63276/alexa-youtube-nodejs, added you as a Collaborator. Have started with some nodejs files I found in a tutorial, but they do basically nothing at the moment (haven't even tested)!

**Comment by ndg63276** [comment]
Have made a discord server at https://discord.gg/N234DZ for further discussions.

**Comment by ndg63276** [comment]
Well, I never got very far with this, but now it is not necessary. You can now have Alexa hosted skills in Python.
