### ISSUE TITLE
issue with Keeping a list of what you have played

### ISSUE THREAD

**Issue by raj2ras** [ndg63276/alexa-youtube#84]
From guide - [https://github.com/ndg63276/alexa-youtube#keeping-a-list-of-what-you-have-played](https://github.com/ndg63276/alexa-youtube#keeping-a-list-of-what-you-have-played)

> "3. Then press on "Manage Settings", and tick the boxes marked "Lists Read Access" and "Lists Write Access", and press "Save Settings".

I don't see the "manage settings" link on the Developer skills on the new Alexa app?

**Comment by ndg63276** [comment]
Odd, I still see "Manage settings", and the app updated 19th July for me. What do you see when you click Settings?

**Comment by raj2ras** [comment]
I am on the android app. It seems the settings have moved uner "main app settings". From there it takes you to this webpage - [https://www.amazon.com/hz/mycd/alexaPrivacy/home](https://www.amazon.com/hz/mycd/alexaPrivacy/home)

**Comment by raj2ras** [comment]
I am getting somewhere. Found some settings under https://developer.amazon.com/ -> Build ->Permissions

![image](https://user-images.githubusercontent.com/610490/61813340-4f936600-adfa-11e9-92dd-a855c0a1f212.png)

**Comment by ndg63276** [comment]
Brilliant.
