### ISSUE TITLE
All the answers are nothing is sounding

### ISSUE THREAD

**Issue by Shiro-pol** [ndg63276/alexa-youtube#85]
I have followed all the steps, with the json in spanish and is all good i can open the skill, saying youtube, and alexa answer with an example, but then i say some command and the answer is the one in the title. "nothing is sounding"

**Comment by ndg63276** [comment]
Is this testing on the website or with a real Alexa device?

Can you tell me (in Spanish) exactly what you say and what Alexa replies?

**Comment by Shiro-pol** [comment]
Ok, yes is in both.
You say the invocation command, in my case youtube, and alexa says "bienvenido a youtube di por ejemplo pon musica de mozart", and when i reply that or another thing, all the answers are "no esta sonando nada".

Thanks for your reply.

**Comment by ndg63276** [comment]
What endpoint are you using? arn:aws:lambda:us-west-2:827204026059:function:YouTube, or your own?

**Comment by Shiro-pol** [comment]
This one "arn:aws:lambda:eu-west-1:175548706300:function:YouTube", is the one for EU?

**Comment by ndg63276** [comment]
Yes, that's a valid one. And it works fine from here:

![image](https://user-images.githubusercontent.com/24956497/62077566-4e22cd00-b242-11e9-8d77-aff5766435e9.png)

So it must be something in your skill. Can you go to the Build tab, go to the JSON editor, and re-upload everything from https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_es.json ? Then Build Model, and test again.

**Comment by Shiro-pol** [comment]
ok, i am goinfg to do that

**Comment by Shiro-pol** [comment]
Now i have othe error, 

![image](https://user-images.githubusercontent.com/49410931/62109024-b8bc2300-b2ab-11e9-8314-05b4c6ad7080.png)

I don't no why i have this problems.

**Comment by ndg63276** [comment]
I'm getting that error now, looks like a general problem. I'll look into it.

**Comment by lucifer0909** [comment]
I'm getting that error

**Comment by ndg63276** [comment]
Yeah, there's a problem getting the title from youtube, see https://github.com/nficano/pytube/issues/434

I've put a quick hack into arn:aws:lambda:eu-west-1:175548706300:function:YouTube, so it will say "playing video" instead of "playing mozart", so @Shiro-pol you can test now.

**Comment by lucifer0909** [comment]
its not working 
same issuse

**Comment by ndg63276** [comment]
If using your own endpoint, re-upload lambda_function.zip.

**Comment by lucifer0909** [comment]
its worked thanks

**Comment by Shiro-pol** [comment]
No, sorry  i still have the problem.
![image](https://user-images.githubusercontent.com/49410931/62160779-0b7df500-b315-11e9-9408-14b837719c92.png)

**Comment by ndg63276** [comment]
It still seems to come and go a bit, but it should be working now.

**Comment by Shiro-pol** [comment]
ok, i am going to wait untill tomorrow because its not working, thanks for all.

**Comment by ndg63276** [comment]
As best I can tell, YouTube is throttling requests, as this skill is getting too popular. So it comes and goes as the day goes on. I have tried to put in a message about this, let me know if you still get "There was a problem with the requested skills response".

**Comment by Shiro-pol** [comment]
Yes now i get the message that you said.
![image](https://user-images.githubusercontent.com/49410931/62240917-590f6600-b3d8-11e9-9f7a-57c6801396d7.png)

**Comment by ndg63276** [comment]
Well that is progress of a sort!

**Comment by edusal100** [comment]
Hello @ndg63276 I'm experiencing the same issues as @Shiro-pol I'm using my own endpoint, and on test in the website I got all working, this is the exact answer from Alexa: "Sonando The Best of Mozart". But when I try it on my echo device or alexa app on the phone I got the following error: "No esta sonando nada". I already re-upload the function zip file and delete the json on the editor and build the skill again but with same results. Hopefully its an issue on my end and or this could be resolved, its a great skill, Thank you in advance for all the hardwork and help :)

**Comment by ndg63276** [comment]
If I say "Alexa, pide a YouTube pon musica de mozart", Alexa thinks I am saying "Play more like this." If I delete that intent, she thinks I am saying "Skip forward". If I delete that intent, she thinks I am saying "Next playlist". If I delete that intent, she thinks I am saying "What song is playing". If I delete that intent, she refuses to use the YouTube skill.

However, if I say "Alexa, pide a YouTube pon canciones de Mozart", it works. Can you confirm if it works for you? If so, I will change the welcome message.

**Comment by edusal100** [comment]
Yes it works!! Thank you so much!

**Comment by ndg63276** [comment]
Great, I've updated the welcome message, if you re-upload lambda_function.zip you should hear it.

**Comment by mauricioville** [comment]
> If using your own endpoint, re-upload lambda_function.zip.

Could someone share me the lambda zip file. I think i have trouble with mine

**Comment by ndg63276** [comment]
> Could someone share me the lambda zip file. I think i have trouble with mine

I'm afraid the skill is now behind a paywall, for $3 / month. You can click Sponsor at the top of this page for access.
