### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by TheHungryGeek** [ndg63276/alexa-youtube#86]

**Comment by hxpq13** [comment]
have the same Proble. What was your soulution?

**Comment by TheHungryGeek** [comment]
You have to change the AWS Lambda ARN under the Endpoint section. Sometimes it fills up and doesn't work anymore.

After that do a rebuild.

**Comment by hxpq13** [comment]
i already did that. but it diddnt worked. strange Thing: when I write :"ask youtube play rammstein" I get a response. When I write "ask youtube play matrix" I did not.

maybe I have another Problem :-/

**Comment by TheHungryGeek** [comment]
Open a new issue
