### ISSUE TITLE
Does not work any more

### ISSUE THREAD

**Issue by hxpq13** [ndg63276/alexa-youtube#87]
Hello everybody,

first of all thanks for your hard work. I appriciate this alot. in my optinion this skill is a must have!!!

It worked like a charm for a while but now i do not get an response from the skill.

in the Alexa simulator i recieve a NULL response with the text "There was a problem in your skill response (freely translated sorry)"

	"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.9a607ee8-4d5e-4c5e-b94e-dab5947f7e79",
		"timestamp": "2019-07-30T09:30:07Z",
		"locale": "de-DE",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "An exception occurred while dispatching the request to the skill."
		}
	}

Can anybosy confirm this?

I already tried your Endpoint. But it still behaves in the same way.

**Comment by ndg63276** [comment]
Was a problem with pytube getting the video title (https://github.com/nficano/pytube/issues/434) Hopefully fixed now. You'll need to re-upload lambda_function.zip to lambda.

**Comment by hxpq13** [comment]
That did the trick! Thank you very much!
