### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by gabbiano69** [ndg63276/alexa-youtube#88]
**Questions you need to answer**
Please provide the following information:

3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
yes

5. What language are you using?
italian

alexa say :
This skill is being throttled by YouTube, 
what to do?

**Comment by ndg63276** [comment]
This skill is getting so popular that the YouTube API limits the number of times it can be used. If you deploy your own endpoint, this is less likely to happen. Or just wait a few minutes and try again.

**Comment by gabbiano69** [comment]
*             thanks, *
*sorry can you tell me if i can pubblish this skill but only for you tube
channell,? i explain:*
*i have a channel in you tube, than with this skill i add the id channel
 and  submit to pubblication to amazon, is possible?*
*if not do you now some repository to do this?*

*last episode, nest episote*
*all directly from you tube*
*can you tell me about it?*
*thanks so much*




Il giorno sab 3 ago 2019 alle ore 10:22 ndg63276 <notifications@github.com>
ha scritto:

**Comment by ndg63276** [comment]
That would definitely be possible, although I can't guarantee Amazon would accept the skill into the Alexa skill store.

If you deploy the skill yourself, set an environment variable MY_CHANNEL_ID with your youtube channel id, and it should play your channel. Then just remove the intents you don't want from InteractionModel_it.json.

**Comment by dungkhuc** [comment]
I got similar problem trying this skill today. I deployed my own endpoint. Google API returns HTTP 429 after about 40 requests.
