### ISSUE TITLE
Skill gives me error when I try to hear music

### ISSUE THREAD

**Issue by Fantasymerlin** [ndg63276/alexa-youtube#91]
Since some days I try to hear music but it don´t works anymore...

If I try I get an error that there is a problem with the skill.

I have read that there is something with the arn lambda. What I have to do to fix the error?

How I can chance the arn name at the aws lambda?

Or is there another problem with the skill?

**Comment by maranathait** [comment]
this is the error   [audio mp3] https://we.tl/t-Zq3g4dDA6l

**Comment by Fantasymerlin** [comment]
no this is not the error.

The error is...
there was a problem with the response of the skill

**Comment by ndg63276** [comment]
When you created this bug report, did it give you a list of questions to answer? Why did you not answer those questions? I cannot fix the problem if you don't give me the relevant information.

**Comment by ndg63276** [comment]
**Questions you need to answer Please provide the following information:**

1. What are you saying to Alexa?
2. What video are you trying to play? Please provide the youtube URL.
3. Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)
4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.
5. What language are you using?

**Comment by Fantasymerlin** [comment]
oh yes. I have forgotten it to answer the questions.

But I tried to reload the lambda_function.zip and after that it works again
