### ISSUE TITLE
Not able play I am getting response : Nothing is playing

### ISSUE THREAD

**Issue by manjsm** [ndg63276/alexa-youtube#92]
**Questions you need to answer**
Please provide the following information:

1. What are you saying to Alexa?
Frist open youtube next I am saying to ask YouTube to play hindi songs

2. What video are you trying to play? Please provide the youtube URL.

I am using eco dot( 3rd generation). URL : https://youtu.be/PGaREkyfKPs . 

3.Are you running your own lambda instance, or are you using mine? (ie What is your endpoint? Is it "arn:aws:lambda:eu-west-1:175548706300:function:YouTube"?)

I am using yours, as I am located in India "arn:aws:lambda:ap-northeast-1:175548706300:function:YouTube "

4. If you are running your own lambda instance, have you uploaded the latest lambda_function.zip file? This changes regularly to fix problems.

5. What language are you using?
This was my first trial .. I was trying to hindi language songs

**Comment by manjsm** [comment]
I got these instructions from https://www.techjunkie.com/

**Comment by ndg63276** [comment]
There are 2 ways to ask YouTube to play a song:
1. Say "Alexa, open YouTube", wait while she replies, then say "Play Hindi songs".
2. Say "Alexa, ask YouTube to play Hindi songs."

Don't get the two mixed up.

**Comment by manjsm** [comment]
Hi, thank you for your reply..  I am following your instructions.. it's working without no issues.

**Comment by manjsm** [comment]
HI,

From 2020, I am not able get the codes working for Alexa to use Youtube

When I say " Alexa ask youtube to play Hindi songs" its not working.

Please help me if I need to change some codes.

Thanks
Manjunath S M

**Comment by ndg63276** [comment]
Hi there, I've had to make the skill only available to sponsors and patreons. There are instructions at https://github.com/sponsors/ndg63276 or https://www.patreon.com/alexayoutube

Mark
