### ISSUE TITLE
Outdate Deploying yourself (optional) tutorial

### ISSUE THREAD

**Issue by oraziocontarino** [ndg63276/alexa-youtube#93]
Hello,
i have created the lambda function as reported in the tutorial.
The tutorial also says to set an "Alexa Skills Kit" trigger.
This type of trigger is not available anymore, so what should i set ?
I'm stuck at this point of the tutorial

**Comment by ndg63276** [comment]
"Alexa Skills Kit" is still the correct type of trigger. However, it is only available in certain locations. Make sure your lambda region is set to one of:

US East (N. Virginia)
EU (Ireland)
US West (Oregon)
Asia Pacific (Tokyo)
