### ISSUE TITLE
This App is Being Throttled By Youtube - Please Try Again Later

### ISSUE THREAD

**Issue by coot66** [ndg63276/alexa-youtube#94]
Do you have any guidance on what generates this error?

It pops up occasionally and I haven't been able to figure out what triggers it. I'm running my own Lambda. Is it just playing music for X amount of time or what? Do you have any visibility into how long the throttling lasts?

**Comment by ndg63276** [comment]
Not really, just that pytube fails with HTTPError 429 - Too many requests. I've seen mention online of YouTube counting requests in 100 seconds, so you might not have to wait long.

If it continues, and given that it probably blocks by IP, you could try a lambda instance in another location.

**Comment by ntm397** [comment]
I have the same issue. Just installed. It played some music. Then I didn't use it for about  an hour and after which I tried again and it says "This App is Being Throttled By Youtube - Please Try Again Later"

**Comment by dungkhuc** [comment]
I have the same problem. I got HTTP 429 every 15-20 videos. I had to wait for rather long time for it to work again (~15 mins). I'm suspecting new limitations were introduced for new accounts. Looking at Quota page on developer site, I'm still well within the limits shown.

**Comment by ndg63276** [comment]
It is based on IP I believe, so if the same Amazon server does a lot of requests, it gives 429. It is not on a part which uses your Google developer key, just the PyTube request, so it is like a web browser loading lots of YouTube pages all at once.

**Comment by dungkhuc** [comment]
I guess then the only reliable solution would be using an elastic IP attached to a NAT Gateway. This setup would cost $30/month :(

**Comment by RVINAA** [comment]
Any solution?

**Comment by ndg63276** [comment]
You could try changing the region lambda runs in, but I don't know if it would work. It is tricky to catch and test.

**Comment by dungkhuc** [comment]
@RVINAA you can create a NAT instance running t2.micro. That should be within 12-month free tier, and $6/month afterwards. Working on a CF template to deploy both lambda and NAT instance.

**Comment by gahan76** [comment]
Can someone provide lamda for east or south east Europe to test

**Comment by dungkhuc** [comment]
> Can someone provide lamda for east or south east Europe to test

EU (Ireland) is the only support region in Europe. I deployed a lambda there and have same issue.

**Comment by Aprania** [comment]
Hi, how can run python code on a VPS and use it with https on alexa skill?

**Comment by BopItFreak** [comment]
I have the same issue. First time I used this skill and i get the error.

**Comment by SunSatION** [comment]
Getting the same error myself.

Created pull request #111 to support proxies

**Comment by jvoxel** [comment]
Same here, how do I fix it?

**Comment by ndg63276** [comment]
If you have uploaded the latest lambda_function.zip, you can set an environment variable in lambda of "youtube_dl" to "true", that should switch you from pytube to youtube_dl, which seems to work better.

**Comment by jvoxel** [comment]
Thanks that is working better for me

**Comment by mariodmmariodm** [comment]
From 2 days for any reproduction: "This skill is being throttled by YouTube, please try again later" tips? where should I change the variable in lambda of "youtube_dl" to "true?

**Comment by ndg63276** [comment]
@mariodmmariodm - in lambda, there is a section called 'Environment variables', where you should already have one called "DEVELOPER_KEY". Add one below that, with a key of "youtube_dl", and a value of "true".

It may not fix the problem though.

**Comment by raj2ras** [comment]
I encountered the dreaded "throttle" for the 1st time! _youtube_dl=true_, resolved it for now.

@ndg63276 , Any downsides to using **youtube_dl** rather than **pytube**?

**Comment by ndg63276** [comment]
@raj2ras No, no downsides to using youtube_dl. If you have the ability and knowhow to run youtube_dl on your own server, you can set the youtube_dl variable to the server address, and it will call that any time it fails. eg youtube_dl=http://myserver.com/cgi-bin/youtube_dl. Will try and put some code online for that at some point.

**Comment by mariodmmariodm** [comment]
thank you, with a "youtube_dl" key and a value of "true" does it work, seems to solve the problem, what does this variable involve in the skill?

**Comment by ndg63276** [comment]
The skill needs a way to get the URL of the audio of a Youtube video, there are 2 ways to do this, PyTube and YouTube-dl. By default, it uses PyTube, but this makes it use YouTube-dl. YouTube-dl seems to make more effort to pretend to be a human, so it seems to work better. When YouTube suspects it is an automated process, you get the "throttled" problem.
