### ISSUE TITLE
Can we Play our saved playlist

### ISSUE THREAD

**Issue by manjsm** [ndg63276/alexa-youtube#95]
I wanted to play my own playlist that has been already created in my channel/account in you tube. I am not sure if this option is there. If it is yes, then can you tell me how to use it. How should I say to play my playlists from my channel/account

**Comment by ndg63276** [comment]
Yes, there are instructions for this in the Readme.

First you need to deploy the skill in your own lambda instance, you can't use mine for this. There is a guide at https://github.com/ndg63276/alexa-youtube/wiki/Running-your-own-lambda-instance

Then get your channel ID from youtube. Find a video you have uploaded, then click on your name beneath it, it should take you to eg https://www.youtube.com/channel/UCDVYQ4Zhbm3S2dlz7P1GBDg, in which case your channel ID is UCDVYQ4Zhbm3S2dlz7P1GBDg. Then, when you add the environment variable DEVELOPER_KEY, add another environment variable called MY_CHANNEL_ID, with the value of that your channel ID. Then you can say, "Alexa, ask YouTube to play my playlist {name of your playlist}".

**Comment by manjsm** [comment]
Hi,

I tired to create lambda function, as it is mentioned in instruction to add
trigger "alexa skills kit" ( as below) however I could not find in it.
Could you please help me with this?

"When it has done the creation, on the new screen, under "Add Triggers",
click "Alexa Skills Kit". Down below select "Disable" on the Skill ID
Verification."

[image: image.png]

**Comment by ndg63276** [comment]
Make sure your region is one of:
US East (N. Virginia)
EU (Ireland)
US West (Oregon)
Asia Pacific (Tokyo)

These are the only ones that have Alexa Skills Kit in the list of triggers.

**Comment by manjsm** [comment]
Hi,

Yes, now I was able to find the "Alexa skill set" :)

However Now I am stuck with last step which states like below

"Log into your Developer Console and go into your *Alexa Skill *and update
the Endpoint using YOUR arn #"
[image: image.png]
How can I navigate to this step/screen "Alexa skills".

**Comment by ndg63276** [comment]
The Developer Console is at https://developer.amazon.com/alexa/console/ask. Then click on your YouTube skill that you should have created already, then on the right hand side click "4. Endpoint". Change the default region to your ARN, then click Save Endpoint. Then click back and click "3. Build Model".
