### ISSUE TITLE
Can you add canfulfillintentrequest Please

### ISSUE THREAD

**Issue by amitdvir1122** [ndg63276/alexa-youtube#96]
https://developer.amazon.com/docs/custom-skills/understand-name-free-interaction-for-custom-skills.html

**Comment by ndg63276** [comment]
This is only available for skills in the Amazon skill store.

**Comment by amitdvir1122** [comment]
I have it published but on  private. Is it possible like that?

**Comment by ndg63276** [comment]
No, sorry, it has to be in the Amazon store.

**Comment by amitdvir1122** [comment]
Why? I read everything I can about it and didn't say anything that says it has to be in Amazon store.

**Comment by ndg63276** [comment]
https://forums.developer.amazon.com/questions/194500/how-to-test-canfulfillintentrequest.html

Feel free to do the coding yourself if you disagree, I'm not wasting my time.

**Comment by amitdvir1122** [comment]
Kk
