### ISSUE TITLE
Is it possible to make an alternative youtube key for more stability 

### ISSUE THREAD

**Issue by amitdvir1122** [ndg63276/alexa-youtube#97]
The title is the question

**Comment by ndg63276** [comment]
Yes, you can follow the instructions in the wiki (https://github.com/ndg63276/alexa-youtube/wiki/Running-your-own-lambda-instance) to deploy your own lambda, and you can get a Google API by following the instructions at https://www.slickremix.com/docs/get-api-key-for-youtube/.
