### ISSUE TITLE
ask you tube to play the last video from a channel

### ISSUE THREAD

**Issue by gabbiano69** [ndg63276/alexa-youtube#98]
i add   environment variable  MY_CHANNEL_ID.
can i ask to play the last video pubblished on this channel? and it's possible to filter that channel with desc date of pubblished?

**Comment by ndg63276** [comment]
I've added a new Intent, called PlayMyLatestVideoIntent, to the lambda_function files. I've added it to the English interaction model, I guess you want it in Italian? What is Italian for "Play my latest video"?

**Comment by gabbiano69** [comment]
en= Play my latest video
it=   Riproduci il mio ultimo video

than what i need to do?

**Comment by ndg63276** [comment]
1. Go to https://developer.amazon.com/edw/home.html#/skills, click on your YouTube skill, then click at the bottom left where it says JSON Editor.
2. Delete the current contents, and copy the file https://raw.githubusercontent.com/ndg63276/alexa-youtube/master/InteractionModel_it.json into the JSON editor.
3. Click Build Model.
4. Download this file https://github.com/ndg63276/alexa-youtube/blob/master/lambda_function.zip.
5. Go to Lambda, usually https://eu-west-1.console.aws.amazon.com/lambda/, but it might be a different address if you used a different region.
6. Click on your Youtube function, half way down under Function Code, change the dropdown from 'Edit Code Inline' to 'Upload a zip file'.
7. Click Upload, then select the zip file you saved in step 4, and then press Save at the top.
8. Say "Alexa, ask YouTube to play my latest video" in Italian.

**Comment by gabbiano69** [comment]
ok thanks i'm trying to pubblish the skill with variable of channel_id i hope amazon pubblish it

**Comment by gabbiano69** [comment]
can you add apl to lanch request?

**Comment by ndg63276** [comment]
Not easily :-)
